// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/activities" | "/condition-diet-rules" | "/daily-nutrition" | "/daily-value-profiles" | "/data-validation-rules" | "/foods" | "/human-type-qa" | "/human-type-surveys" | "/login" | "/meal-logs" | "/nutrient-intake-rules" | "/nutrition-constraints" | "/nutrition-terminology" | "/recipe-ingredients" | "/recipes" | "/reference-sources" | "/risk-assessment-rules" | "/users"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/activities": {}
  "/condition-diet-rules": {}
  "/daily-nutrition": {}
  "/daily-value-profiles": {}
  "/data-validation-rules": {}
  "/foods": {}
  "/human-type-qa": {}
  "/human-type-surveys": {}
  "/login": {}
  "/meal-logs": {}
  "/nutrient-intake-rules": {}
  "/nutrition-constraints": {}
  "/nutrition-terminology": {}
  "/recipe-ingredients": {}
  "/recipes": {}
  "/reference-sources": {}
  "/risk-assessment-rules": {}
  "/users": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
