// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/(admin)/activities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/activities">> = Specific
  const handler = {} as typeof import("../../app/(admin)/activities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin)/condition-diet-rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/condition-diet-rules">> = Specific
  const handler = {} as typeof import("../../app/(admin)/condition-diet-rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin)/daily-value-profiles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/daily-value-profiles">> = Specific
  const handler = {} as typeof import("../../app/(admin)/daily-value-profiles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin)/data-validation-rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-validation-rules">> = Specific
  const handler = {} as typeof import("../../app/(admin)/data-validation-rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin)/foods/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/foods">> = Specific
  const handler = {} as typeof import("../../app/(admin)/foods/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin)/human-type-qa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/human-type-qa">> = Specific
  const handler = {} as typeof import("../../app/(admin)/human-type-qa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin)/human-type-surveys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/human-type-surveys">> = Specific
  const handler = {} as typeof import("../../app/(admin)/human-type-surveys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin)/meal-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/meal-logs">> = Specific
  const handler = {} as typeof import("../../app/(admin)/meal-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin)/nutrient-intake-rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nutrient-intake-rules">> = Specific
  const handler = {} as typeof import("../../app/(admin)/nutrient-intake-rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin)/nutrition-constraints/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nutrition-constraints">> = Specific
  const handler = {} as typeof import("../../app/(admin)/nutrition-constraints/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin)/nutrition-terminology/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nutrition-terminology">> = Specific
  const handler = {} as typeof import("../../app/(admin)/nutrition-terminology/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(admin)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin)/recipe-ingredients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recipe-ingredients">> = Specific
  const handler = {} as typeof import("../../app/(admin)/recipe-ingredients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin)/recipes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recipes">> = Specific
  const handler = {} as typeof import("../../app/(admin)/recipes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin)/reference-sources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reference-sources">> = Specific
  const handler = {} as typeof import("../../app/(admin)/reference-sources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin)/risk-assessment-rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/risk-assessment-rules">> = Specific
  const handler = {} as typeof import("../../app/(admin)/risk-assessment-rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin)/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users">> = Specific
  const handler = {} as typeof import("../../app/(admin)/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/(admin)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(admin)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
