import mongoose, { Schema, type Model } from "mongoose";
import {
  dailyValuePercentByProfileSchema,
  dailyValuePercentSchema,
  macroSchema,
  mineralSchema,
  reviewFlag,
  vitaminSchema
} from "./common.js";

const foodSchema = new Schema(
  {
    koreanName: { type: String, required: true, trim: true, index: true },
    chineseName: { type: String, trim: true, index: true },
    fdcId: { type: Number, unique: true, sparse: true, index: true },
    sourceFoodId: { type: String, trim: true, index: true },
    dataType: { type: String, trim: true, index: true },
    brand: { type: String, trim: true },
    category: { type: String, required: true, trim: true, index: true },
    foodGroup: { type: String, trim: true, index: true },
    foodSubgroup: { type: String, trim: true, index: true },
    servingSize: { type: String, required: true },
    calories: { type: Number, required: true, min: 0 },
    macros: { type: macroSchema, default: {} },
    saturatedFat: { type: Number, default: 0 },
    transFat: { type: Number, default: 0 },
    unsaturatedFat: { type: Number, default: 0 },
    omega3: { type: Number, default: 0 },
    omega6: { type: Number, default: 0 },
    cholesterolMg: { type: Number, default: 0 },
    sugar: { type: Number, default: 0 },
    glycemicIndex: { type: Number, default: 0 },
    oiliness: { type: String, trim: true },
    oilinessScore: { type: Number, min: 0, max: 5, default: 0 },
    vitamins: { type: vitaminSchema, default: {} },
    minerals: { type: mineralSchema, default: {} },
    bestTimeToEat: [{ type: String, trim: true }],
    goodPairings: [{ type: String, trim: true }],
    avoidPairings: [{ type: String, trim: true }],
    cautionGroups: [{ type: String, trim: true }],
    cautions: { type: String, trim: true },
    koreanCautions: { type: String, trim: true },
    benefits: { type: String, trim: true },
    allergens: [{ type: String, trim: true }],
    ingredients: [{ type: String, trim: true }],
    additives: [{ type: String, trim: true }],
    dailyValuePercent: { type: dailyValuePercentSchema, default: {} },
    dailyValuePercentByProfile: { type: [dailyValuePercentByProfileSchema], default: [] },
    dietUseCases: [{ type: String, trim: true }],
    dietUseNote: { type: String, trim: true },
    dataSource: { type: String, trim: true },
    sourceNutrition: { type: Schema.Types.Mixed, default: {} },
    sourceNote: { type: String, trim: true },
    tags: [{ type: String, trim: true }],
    barcode: { type: String, trim: true },
    imageUrl: { type: String, trim: true },
    imageSource: { type: String, trim: true },
    imageSourceUrl: { type: String, trim: true },
    imagePageUrl: { type: String, trim: true },
    imageLicense: { type: String, trim: true },
    imageStatus: { type: String, trim: true, index: true },
    icon: { type: String, trim: true },
    ...reviewFlag
  },
  { timestamps: true }
);

export const Food = (mongoose.models.Food || mongoose.model("Food", foodSchema)) as Model<any>;
