-- Migration 009: Seed recipes for baby (all age groups) and mum (all meal slots)

-- ═══════════════════════════════════════════════════════════════════════════
-- BABY RECIPES
-- Age groups: 0-6 | 7-11 | 12-17 | 18-24 | 25-30 | 31-36
-- Meal slots: breakfast | lunch | dinner | snack
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── Age 0-6 months (breast milk / formula only) ─────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, nutrition_info) VALUES
('Breast Milk Feed',       'Exclusive breastfeeding on demand — the perfect complete nutrition for 0–6 months.', 'baby', 'breakfast', '0-6', 0, 6, 'puree', ARRAY['Breast milk'], ARRAY['Feed on demand, typically every 2–3 hours.'], 0, '{"note":"Complete nutrition — no solids needed at this stage"}'),
('Formula Feed',           'Iron-fortified infant formula as alternative to breast milk.', 'baby', 'breakfast', '0-6', 0, 6, 'puree', ARRAY['Infant formula powder','Boiled cooled water'], ARRAY['Measure water first.','Add correct scoops of formula.','Shake gently and feed at body temperature.'], 5, '{"note":"Follow tin instructions for correct ratio"}'),
('Breast Milk — Midday',   'Daytime breastfeeding session.', 'baby', 'lunch',     '0-6', 0, 6, 'puree', ARRAY['Breast milk'], ARRAY['Feed on demand.'], 0, '{}'),
('Formula — Midday',       'Midday formula bottle.', 'baby', 'lunch', '0-6', 0, 6, 'puree', ARRAY['Infant formula powder','Boiled cooled water'], ARRAY['Prepare as per tin instructions.'], 5, '{}'),
('Evening Breast Milk',    'Evening breastfeeding session.', 'baby', 'dinner', '0-6', 0, 6, 'puree', ARRAY['Breast milk'], ARRAY['Feed on demand.'], 0, '{}'),
('Bedtime Formula Bottle', 'Settling formula feed before sleep.', 'baby', 'snack', '0-6', 0, 6, 'puree', ARRAY['Infant formula powder','Boiled cooled water'], ARRAY['Prepare a slightly larger feed before bed to promote longer sleep.'], 5, '{}');

-- ─── Age 7-11 months — Breakfast ─────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('Rice Cereal Porridge',   'Smooth iron-fortified rice cereal — ideal first breakfast.', 'baby', 'breakfast', '7-11', 7, 11, 'puree', ARRAY['2 tbsp iron-fortified rice cereal','3–4 tbsp breast milk or formula'], ARRAY['Mix cereal with warm breast milk or formula.','Stir to smooth consistency.','Serve warm.'], 3, 0, '{"iron":"high","calories":60}'),
('Banana & Oat Puree',     'Naturally sweet banana blended with soft cooked oats.', 'baby', 'breakfast', '7-11', 7, 11, 'puree', ARRAY['½ ripe banana','2 tbsp rolled oats','3 tbsp water or formula'], ARRAY['Cook oats in water until soft (5 min).','Mash banana.','Mix together and blend until smooth.'], 5, 5, '{"potassium":"high","fiber":"medium","calories":90}'),
('Apple Cinnamon Porridge','Gently spiced apple and oat puree rich in fibre.', 'baby', 'breakfast', '7-11', 7, 11, 'puree', ARRAY['1 small apple (peeled)','2 tbsp oats','Pinch of cinnamon','Water'], ARRAY['Peel, core and chop apple.','Steam or simmer until soft (8 min).','Cook oats separately.','Blend apple with oats and a pinch of cinnamon.'], 5, 10, '{"fiber":"high","vitamin_c":"medium","calories":85}'),
('Sweet Potato Mash',      'Naturally sweet and creamy sweet potato puree.', 'baby', 'breakfast', '7-11', 7, 11, 'puree', ARRAY['1 small sweet potato','2 tbsp breast milk or formula'], ARRAY['Peel and cube sweet potato.','Steam for 15 min until tender.','Mash well adding milk to reach smooth consistency.'], 5, 15, '{"vitamin_a":"high","potassium":"high","calories":95}');

-- ─── Age 7-11 months — Lunch ─────────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('Carrot & Lentil Soup',   'Iron-rich lentils with sweet carrot — perfect first protein meal.', 'baby', 'lunch', '7-11', 7, 11, 'puree', ARRAY['2 tbsp red lentils','1 small carrot','2 cups water'], ARRAY['Rinse lentils.','Peel and chop carrot.','Simmer together 20 min until soft.','Blend to smooth puree.'], 5, 20, '{"iron":"high","protein":"medium","vitamin_a":"high","calories":110}'),
('Pea & Potato Puree',     'Mild and creamy pea and potato blend packed with vitamins.', 'baby', 'lunch', '7-11', 7, 11, 'puree', ARRAY['¼ cup frozen peas','1 small potato','Water'], ARRAY['Peel and cube potato; steam 15 min.','Add peas for last 5 min.','Blend together to smooth puree.'], 5, 15, '{"vitamin_c":"high","fiber":"medium","calories":95}'),
('Butternut Squash & Apple','Sweet squash with apple makes a naturally tasty combo.', 'baby', 'lunch', '7-11', 7, 11, 'puree', ARRAY['¼ butternut squash','½ apple'], ARRAY['Peel and cube squash; steam 15 min.','Peel, core and chop apple; steam 8 min.','Blend together until smooth.'], 5, 15, '{"vitamin_a":"very_high","fiber":"medium","calories":80}'),
('Chicken & Vegetable Puree','First protein introduction with mild chicken and vegetables.', 'baby', 'lunch', '7-11', 7, 11, 'puree', ARRAY['30g chicken breast','1 small carrot','¼ cup peas','Water'], ARRAY['Simmer chicken in water 15 min until cooked.','Steam carrot and peas separately.','Blend everything together adding cooking water for consistency.'], 5, 20, '{"protein":"high","iron":"medium","zinc":"medium","calories":120}');

-- ─── Age 7-11 months — Dinner ────────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('Broccoli & Cheese Mash', 'Calcium-rich cheese mixed into smooth broccoli.', 'baby', 'dinner', '7-11', 7, 11, 'puree', ARRAY['4 broccoli florets','1 tbsp mild cheddar (grated)','1 tbsp milk'], ARRAY['Steam broccoli 8 min until tender.','Blend with cheese and milk to smooth puree.'], 5, 8, '{"calcium":"high","vitamin_c":"high","calories":85}'),
('Lentil & Spinach Dal',   'Iron-packed dal — easy first taste of legumes.', 'baby', 'dinner', '7-11', 7, 11, 'puree', ARRAY['2 tbsp red lentils','Handful baby spinach','½ tsp mild cumin','Water'], ARRAY['Cook lentils in water 20 min.','Add spinach last 3 min.','Blend with a pinch of cumin to smooth consistency.'], 5, 20, '{"iron":"very_high","folate":"high","calories":105}'),
('Fish & Sweet Potato',    'Omega-3 rich white fish with sweet potato for brain development.', 'baby', 'dinner', '7-11', 7, 11, 'puree', ARRAY['40g white fish fillet','1 small sweet potato'], ARRAY['Steam sweet potato 15 min.','Poach fish in water 8 min; check for bones.','Blend together to smooth puree.'], 5, 15, '{"omega3":"high","vitamin_a":"high","protein":"high","calories":130}');

-- ─── Age 7-11 months — Snack ─────────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, nutrition_info) VALUES
('Mango Puree',            'Ripe mango puree — naturally sweet vitamin C snack.', 'baby', 'snack', '7-11', 7, 11, 'puree', ARRAY['½ ripe mango'], ARRAY['Peel and remove seed.','Blend to smooth puree.'], 3, '{"vitamin_c":"high","vitamin_a":"medium","calories":65}'),
('Pear & Ginger Puree',    'Gentle pear with a hint of ginger to aid digestion.', 'baby', 'snack', '7-11', 7, 11, 'puree', ARRAY['1 ripe pear','Tiny pinch of ginger'], ARRAY['Peel, core and chop pear.','Steam 8 min.','Blend with pinch of ginger.'], 3, '{"fiber":"medium","calories":55}'),
('Avocado Mash',           'Creamy avocado rich in healthy fats for brain development.', 'baby', 'snack', '7-11', 7, 11, 'puree', ARRAY['¼ ripe avocado'], ARRAY['Scoop out avocado flesh.','Mash with fork to smooth consistency.'], 2, '{"healthy_fats":"high","calories":80}');

-- ─── Age 12-17 months — Breakfast ────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('Egg & Toast Soldiers',   'Soft scrambled egg with toast fingers — great self-feeding practice.', 'baby', 'breakfast', '12-17', 12, 17, 'finger_food', ARRAY['1 egg','1 slice wholegrain bread','1 tsp butter'], ARRAY['Scramble egg gently in butter over low heat.','Toast bread and cut into strips.','Serve egg alongside toast soldiers.'], 5, 5, '{"protein":"high","iron":"medium","calories":160}'),
('Banana Pancakes',        'Two-ingredient banana egg pancakes — no sugar needed.', 'baby', 'breakfast', '12-17', 12, 17, 'finger_food', ARRAY['1 ripe banana','1 egg','1 tsp coconut oil'], ARRAY['Mash banana; whisk with egg.','Heat oil in pan over medium heat.','Pour small rounds; cook 2 min per side.','Serve cut into strips.'], 5, 10, '{"potassium":"high","protein":"medium","calories":140}'),
('Overnight Oats',         'Creamy oats soaked overnight with fruit — no cooking needed.', 'baby', 'breakfast', '12-17', 12, 17, 'meal', ARRAY['3 tbsp rolled oats','½ cup whole milk','¼ banana','1 tbsp mashed berries'], ARRAY['Mix oats and milk; refrigerate overnight.','Top with mashed banana and berries in the morning.'], 3, 0, '{"calcium":"high","fiber":"high","calories":175}'),
('Cheesy Veggie Omelette', 'Mini omelette loaded with soft vegetables and cheese.', 'baby', 'breakfast', '12-17', 12, 17, 'meal', ARRAY['1 egg','1 tbsp grated cheese','2 tbsp finely chopped soft veg (pea, carrot)','Butter'], ARRAY['Whisk egg; stir in cheese and veg.','Cook in buttered pan 3 min until set.','Cut into strips for easy eating.'], 5, 5, '{"protein":"high","calcium":"medium","calories":150}');

-- ─── Age 12-17 months — Lunch ────────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('Mini Pasta with Tomato', 'Soft pasta stars in mild tomato sauce — a toddler favourite.', 'baby', 'lunch', '12-17', 12, 17, 'meal', ARRAY['¼ cup small pasta','2 tbsp no-salt tomato puree','1 tsp olive oil','Pinch of basil'], ARRAY['Cook pasta as per packet until very soft.','Warm tomato puree with olive oil and basil.','Toss pasta in sauce and serve.'], 5, 10, '{"carbs":"high","iron":"medium","calories":165}'),
('Lentil Veggie Patties',  'Soft lentil and vegetable patties — easy to hold and rich in iron.', 'baby', 'lunch', '12-17', 12, 17, 'finger_food', ARRAY['¼ cup red lentils (cooked)','2 tbsp mashed carrot','2 tbsp mashed pea','1 tbsp breadcrumbs','1 egg'], ARRAY['Mash lentils; mix with veg, breadcrumbs and egg.','Form into small flat patties.','Bake at 180°C for 15 min, flipping halfway.'], 10, 15, '{"iron":"high","protein":"high","fiber":"medium","calories":145}'),
('Chicken Rice Bowl',      'Tender shredded chicken with soft rice and steamed veg.', 'baby', 'lunch', '12-17', 12, 17, 'meal', ARRAY['30g cooked chicken (shredded)','¼ cup cooked rice','Steamed broccoli florets','1 tsp olive oil'], ARRAY['Shred cooked chicken finely.','Mix warm rice and chicken.','Top with small broccoli pieces and drizzle oil.'], 5, 0, '{"protein":"high","zinc":"medium","calories":180}'),
('Hummus & Veggie Strips', 'Creamy hummus with soft steamed vegetable strips for dipping.', 'baby', 'lunch', '12-17', 12, 17, 'finger_food', ARRAY['2 tbsp hummus','Soft steamed carrot strips','Soft cucumber strips','Pita triangle (soft)'], ARRAY['Serve hummus in small bowl.','Arrange steamed carrot strips and cucumber.','Add soft pita triangle for dipping.'], 5, 5, '{"protein":"medium","iron":"medium","fiber":"high","calories":130}');

-- ─── Age 12-17 months — Dinner ───────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('Mini Fish Pie',          'Flaky fish in creamy sauce topped with mashed potato.', 'baby', 'dinner', '12-17', 12, 17, 'meal', ARRAY['40g white fish','½ cup mashed potato','2 tbsp milk','1 tsp butter','Peas'], ARRAY['Poach fish 8 min; flake and check for bones.','Mix fish with peas and milk sauce.','Top with mashed potato.','Bake 10 min at 180°C.'], 10, 20, '{"omega3":"high","protein":"high","calcium":"medium","calories":195}'),
('Beef & Vegetable Stew',  'Slow-cooked beef with root vegetables — great for iron.', 'baby', 'dinner', '12-17', 12, 17, 'meal', ARRAY['40g lean beef mince','1 small carrot (diced)','¼ cup potato (diced)','¼ cup peas','Water or no-salt stock'], ARRAY['Brown mince in pan.','Add vegetables and stock; simmer 25 min.','Mash slightly for appropriate texture.'], 10, 30, '{"iron":"very_high","protein":"high","zinc":"high","calories":200}'),
('Tofu & Broccoli Stir',   'Soft tofu and tender broccoli with gentle sesame.', 'baby', 'dinner', '12-17', 12, 17, 'meal', ARRAY['50g soft tofu (cubed)','4 broccoli florets','1 tsp sesame oil','1 tsp low-sodium soy sauce'], ARRAY['Steam broccoli 8 min until tender.','Pan-fry tofu in sesame oil 3 min per side.','Toss together with tiny amount of soy sauce.','Cut into small pieces before serving.'], 5, 12, '{"protein":"high","calcium":"high","iron":"medium","calories":150}');

-- ─── Age 12-17 months — Snack ────────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, nutrition_info) VALUES
('Cheese & Apple Slices',  'Mild cheese with sweet apple — calcium and fibre combo.', 'baby', 'snack', '12-17', 12, 17, 'snack', ARRAY['2 slices mild cheddar','½ small apple (soft sliced)'], ARRAY['Slice apple thinly and remove skin if needed.','Serve with cheese slices.'], 3, '{"calcium":"high","fiber":"medium","calories":105}'),
('Yogurt & Berry Bowl',    'Full-fat yogurt with mashed fresh berries.', 'baby', 'snack', '12-17', 12, 17, 'snack', ARRAY['4 tbsp full-fat plain yogurt','Handful strawberries or blueberries'], ARRAY['Mash or halve berries.','Stir into yogurt and serve.'], 3, '{"calcium":"high","vitamin_c":"high","probiotics":"yes","calories":90}'),
('Rice Cake with Avocado', 'Unsalted rice cake topped with creamy avocado.', 'baby', 'snack', '12-17', 12, 17, 'snack', ARRAY['1 unsalted rice cake','¼ ripe avocado'], ARRAY['Mash avocado onto rice cake.','Cut into smaller pieces if needed.'], 2, '{"healthy_fats":"high","calories":85}');

-- ─── Age 18-24 months — Breakfast ────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('French Toast',           'Egg-dipped wholegrain bread fried golden — a classic toddler favourite.', 'baby', 'breakfast', '18-24', 18, 24, 'finger_food', ARRAY['1 slice wholegrain bread','1 egg','2 tbsp milk','½ tsp cinnamon','Butter'], ARRAY['Whisk egg, milk and cinnamon.','Dip bread both sides.','Fry in buttered pan 2 min per side until golden.','Cut into fingers.'], 5, 5, '{"protein":"high","calcium":"medium","calories":180}'),
('Smoothie Bowl',          'Thick fruit smoothie bowl with soft toppings.', 'baby', 'breakfast', '18-24', 18, 24, 'meal', ARRAY['½ banana','½ cup frozen mango','¼ cup yogurt','Toppings: soft banana slices, blueberries'], ARRAY['Blend banana, mango and yogurt to thick consistency.','Pour into bowl.','Top with soft fruit pieces.'], 5, 0, '{"vitamin_c":"high","calcium":"medium","calories":160}'),
('Mini Veggie Frittata',   'Bite-size egg frittata with hidden vegetables.', 'baby', 'breakfast', '18-24', 18, 24, 'meal', ARRAY['2 eggs','2 tbsp milk','2 tbsp peas','2 tbsp corn','2 tbsp grated cheese'], ARRAY['Whisk eggs and milk.','Stir in veg and cheese.','Pour into greased muffin tin.','Bake 15 min at 180°C.'], 5, 15, '{"protein":"high","iron":"medium","calories":165}');

-- ─── Age 18-24 months — Lunch ────────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('Cheese Quesadilla',      'Melted cheese in soft tortilla — easy finger food packed with calcium.', 'baby', 'lunch', '18-24', 18, 24, 'finger_food', ARRAY['1 small flour tortilla','¼ cup grated cheese','2 tbsp black beans (mashed)'], ARRAY['Spread beans on half the tortilla.','Sprinkle cheese; fold in half.','Cook in dry pan 2 min per side.','Cut into wedges.'], 5, 5, '{"calcium":"high","protein":"medium","calories":210}'),
('Lentil Soup with Bread', 'Warming lentil soup with soft bread pieces for dipping.', 'baby', 'lunch', '18-24', 18, 24, 'meal', ARRAY['¼ cup red lentils','1 small carrot','1 small potato','½ tsp cumin','Low-sodium stock'], ARRAY['Simmer lentils and veg in stock 20 min.','Blend half for texture; leave rest chunky.','Serve with soft bread for dipping.'], 5, 20, '{"iron":"high","protein":"high","fiber":"high","calories":190}'),
('Tuna Pasta Salad',       'Flaked tuna with soft pasta and peas — high protein lunch.', 'baby', 'lunch', '18-24', 18, 24, 'meal', ARRAY['¼ cup small pasta (cooked)','30g canned tuna in water','2 tbsp peas','1 tbsp cream cheese'], ARRAY['Cook pasta until very soft.','Mix warm pasta with drained tuna, peas and cream cheese.','Serve warm or room temperature.'], 5, 10, '{"protein":"high","omega3":"medium","calories":200}');

-- ─── Age 18-24 months — Dinner ───────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('Chicken & Vegetable Curry','Mild toddler-friendly curry with rice.', 'baby', 'dinner', '18-24', 18, 24, 'meal', ARRAY['50g chicken breast','½ cup mixed veg','¼ cup coconut milk','½ tsp mild curry powder','Cooked rice'], ARRAY['Cut chicken into small pieces; cook in pan 8 min.','Add veg and curry powder; stir 2 min.','Add coconut milk; simmer 10 min.','Serve over soft rice.'], 10, 20, '{"protein":"high","iron":"medium","calories":220}'),
('Beef Meatballs',         'Mini soft beef meatballs with pasta and tomato sauce.', 'baby', 'dinner', '18-24', 18, 24, 'meal', ARRAY['50g lean beef mince','1 tbsp breadcrumbs','1 egg yolk','No-salt tomato sauce','Small pasta'], ARRAY['Mix beef, breadcrumbs and egg yolk; roll into small balls.','Bake at 180°C 12 min.','Simmer in tomato sauce.','Serve over soft-cooked pasta.'], 10, 20, '{"iron":"very_high","protein":"high","zinc":"high","calories":240}'),
('Veggie Dhal',            'Comforting toor dal with mild spices and roti.', 'baby', 'dinner', '18-24', 18, 24, 'meal', ARRAY['¼ cup toor dal','1 small tomato','½ tsp turmeric','½ tsp mild cumin','Soft roti'], ARRAY['Cook dal in water until very soft (25 min).','Add tomato, turmeric and cumin; simmer 5 min.','Mash slightly for texture.','Serve with torn soft roti.'], 5, 30, '{"iron":"high","protein":"high","folate":"high","calories":210}');

-- ─── Age 18-24 months — Snack ────────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, instructions, ingredients, prep_time_minutes, nutrition_info) VALUES
('Banana & Peanut Butter', 'Sliced banana with smooth peanut butter — energy-packed snack.', 'baby', 'snack', '18-24', 18, 24, 'snack', ARRAY['Slice banana.','Spread thin layer of peanut butter on each piece.'], ARRAY['1 banana','1 tbsp smooth peanut butter'], 3, '{"protein":"medium","healthy_fats":"high","potassium":"high","calories":140}'),
('Mini Muffin',            'Soft wholegrain banana mini muffin — no added sugar.', 'baby', 'snack', '18-24', 18, 24, 'snack', ARRAY['Mash 2 bananas.','Mix with 1 egg, ½ cup oats.','Fold in blueberries.','Bake at 180°C 12 min.'], ARRAY['2 ripe bananas','1 egg','½ cup rolled oats','¼ cup blueberries'], 5, '{"fiber":"high","potassium":"high","calories":110}');

-- ─── Age 25-30 months — Breakfast ────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('Whole Grain Cereal & Milk','Fibre-rich cereal with whole milk and fresh berries.', 'baby', 'breakfast', '25-30', 25, 30, 'meal', ARRAY['½ cup whole grain cereal','½ cup whole milk','Handful of berries'], ARRAY['Pour cereal into bowl.','Add milk and top with berries.'], 2, 0, '{"fiber":"high","calcium":"high","calories":185}'),
('Veggie Egg Wrap',        'Scrambled egg with spinach and cheese in a soft wrap.', 'baby', 'breakfast', '25-30', 25, 30, 'meal', ARRAY['1 egg','1 tbsp spinach (chopped)','1 tbsp cheese','1 small soft wrap'], ARRAY['Scramble egg with spinach and cheese.','Spoon onto wrap and roll.','Cut in half.'], 5, 5, '{"protein":"high","iron":"medium","calcium":"medium","calories":195}'),
('Porridge with Seeds',    'Creamy oat porridge with chia seeds and honey-free fruit topping.', 'baby', 'breakfast', '25-30', 25, 30, 'meal', ARRAY['½ cup oats','1 cup whole milk','1 tsp chia seeds','Sliced strawberries'], ARRAY['Cook oats in milk 5 min stirring.','Top with chia seeds and strawberries.'], 2, 5, '{"fiber":"high","calcium":"high","omega3":"medium","calories":200}');

-- ─── Age 25-30 months — Lunch ────────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('Chicken Sandwich',       'Shredded chicken with avocado in soft wholegrain bread.', 'baby', 'lunch', '25-30', 25, 30, 'finger_food', ARRAY['2 slices wholegrain bread','40g cooked chicken','¼ avocado','Cucumber slices'], ARRAY['Mash avocado; spread on bread.','Layer chicken and cucumber.','Cut into small squares.'], 5, 0, '{"protein":"high","healthy_fats":"high","calories":225}'),
('Mini Veggie Pizza',      'English muffin pizza with hidden vegetable tomato sauce.', 'baby', 'lunch', '25-30', 25, 30, 'meal', ARRAY['1 wholegrain English muffin','2 tbsp tomato puree','¼ cup grated cheese','Mixed soft veg toppings'], ARRAY['Spread tomato on muffin halves.','Add veg toppings and cheese.','Grill 5 min until cheese melts.'], 5, 5, '{"calcium":"high","fiber":"medium","calories":220}'),
('Bean & Rice Burrito',    'Soft tortilla filled with mashed black beans and rice.', 'baby', 'lunch', '25-30', 25, 30, 'meal', ARRAY['1 small flour tortilla','3 tbsp black beans (mashed)','¼ cup cooked rice','2 tbsp cheese','Mild salsa'], ARRAY['Warm tortilla.','Layer beans, rice, cheese and small amount of salsa.','Roll and cut in half.'], 5, 5, '{"protein":"high","iron":"high","fiber":"high","calories":235}');

-- ─── Age 25-30 months — Dinner ───────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('Salmon & Mash',          'Omega-3 rich salmon fillet with creamy mashed potato.', 'baby', 'dinner', '25-30', 25, 30, 'meal', ARRAY['60g salmon fillet','1 medium potato','2 tbsp milk','1 tsp butter','Peas'], ARRAY['Bake salmon at 180°C 15 min; flake.','Boil potato; mash with milk and butter.','Serve salmon on mash with peas.'], 5, 20, '{"omega3":"very_high","protein":"high","calcium":"medium","calories":270}'),
('Tomato & Lentil Pasta',  'Hearty lentil bolognese served with wholegrain pasta.', 'baby', 'dinner', '25-30', 25, 30, 'meal', ARRAY['¼ cup puy lentils','2 tbsp tomato puree','1 small carrot (grated)','½ tsp oregano','Pasta'], ARRAY['Simmer lentils 25 min.','Add tomato, carrot and oregano; cook 10 min.','Serve over pasta.'], 5, 35, '{"iron":"high","protein":"high","fiber":"high","calories":250}'),
('Toddler Shepherd''s Pie', 'Minced lamb with veg under a sweet potato mash crust.', 'baby', 'dinner', '25-30', 25, 30, 'meal', ARRAY['50g lamb mince','Mixed veg (carrot, pea, corn)','½ cup sweet potato mash','Low-sodium stock'], ARRAY['Brown mince; add veg and stock; simmer 15 min.','Top with sweet potato mash.','Bake 15 min at 180°C.'], 10, 30, '{"iron":"very_high","protein":"high","vitamin_a":"high","calories":265}');

-- ─── Age 25-30 months — Snack ────────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, nutrition_info) VALUES
('Trail Mix',              'Small handful of raisins, soft dried mango and pumpkin seeds.', 'baby', 'snack', '25-30', 25, 30, 'snack', ARRAY['1 tbsp raisins','1 tbsp soft dried mango pieces','1 tsp pumpkin seeds'], ARRAY['Mix together in small bowl.','Supervise eating to prevent choking.'], 1, '{"iron":"medium","zinc":"medium","calories":95}'),
('Cucumber & Dip',         'Cucumber sticks with creamy hummus or cream cheese dip.', 'baby', 'snack', '25-30', 25, 30, 'snack', ARRAY['½ cucumber','2 tbsp hummus'], ARRAY['Cut cucumber into sticks.','Serve with hummus for dipping.'], 3, '{"fiber":"medium","protein":"medium","calories":80}');

-- ─── Age 31-36 months — Breakfast ────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('Boiled Egg & Toast',     'Two-minute boiled egg with wholegrain toast — classic nutritious breakfast.', 'baby', 'breakfast', '31-36', 31, 36, 'meal', ARRAY['1 egg','1 slice wholegrain toast','1 tsp butter'], ARRAY['Boil egg 5–6 min for semi-soft yolk.','Toast bread; butter lightly.','Serve egg in cup with toast soldiers.'], 2, 6, '{"protein":"high","iron":"medium","calories":175}'),
('Berry Yogurt Parfait',   'Layered yogurt, granola and fresh berries.', 'baby', 'breakfast', '31-36', 31, 36, 'meal', ARRAY['½ cup full-fat yogurt','2 tbsp low-sugar granola','Mixed fresh berries'], ARRAY['Layer yogurt in cup.','Add granola.','Top with berries.'], 3, 0, '{"calcium":"high","probiotics":"yes","fiber":"high","calories":190}'),
('Spinach Egg Muffin',     'Baked egg muffins with spinach and cheese — meal-prep friendly.', 'baby', 'breakfast', '31-36', 31, 36, 'meal', ARRAY['2 eggs','Handful spinach (chopped)','2 tbsp cheese','1 tbsp milk'], ARRAY['Whisk eggs and milk.','Mix in spinach and cheese.','Pour into greased muffin moulds.','Bake at 180°C 15 min.'], 5, 15, '{"protein":"high","iron":"high","calcium":"medium","calories":165}');

-- ─── Age 31-36 months — Lunch ────────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('Chicken Noodle Soup',    'Warming homemade chicken noodle soup with vegetables.', 'baby', 'lunch', '31-36', 31, 36, 'meal', ARRAY['50g chicken','½ cup egg noodles','1 carrot (diced)','1 celery stalk','Low-sodium stock'], ARRAY['Simmer chicken in stock 15 min; shred.','Add noodles and veg; cook 8 min.','Serve warm.'], 5, 25, '{"protein":"high","zinc":"medium","calories":210}'),
('Cheese & Veggie Sandwich','Wholegrain sandwich with cheese, cucumber and tomato.', 'baby', 'lunch', '31-36', 31, 36, 'finger_food', ARRAY['2 slices wholegrain bread','2 slices mild cheese','Cucumber','Tomato','Lettuce'], ARRAY['Layer ingredients on bread.','Cut into triangles or squares.'], 5, 0, '{"calcium":"high","fiber":"medium","calories":215}'),
('Rainbow Salad Bowl',     'Colourful chopped salad with quinoa and mild dressing.', 'baby', 'lunch', '31-36', 31, 36, 'meal', ARRAY['¼ cup quinoa (cooked)','Cherry tomatoes (halved)','Cucumber (diced)','Sweetcorn','1 tsp olive oil','Squeeze of lemon'], ARRAY['Cook quinoa; cool.','Chop all vegetables.','Toss together with oil and lemon.'], 5, 15, '{"protein":"high","fiber":"high","vitamin_c":"high","calories":200}');

-- ─── Age 31-36 months — Dinner ───────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('Mild Chicken Biryani',   'Fragrant mild biryani with vegetables — family-style meal.', 'baby', 'dinner', '31-36', 31, 36, 'meal', ARRAY['60g chicken','½ cup basmati rice','Mixed veg','½ tsp mild garam masala','Yogurt'], ARRAY['Marinate chicken in yogurt and spice 20 min.','Cook rice.','Brown chicken; add veg; simmer 15 min.','Layer over rice; bake covered 15 min at 180°C.'], 25, 30, '{"protein":"high","iron":"medium","calories":280}'),
('Fish Tacos',             'Soft baked fish in mini tortillas with slaw.', 'baby', 'dinner', '31-36', 31, 36, 'meal', ARRAY['60g white fish','2 mini flour tortillas','¼ cup cabbage (shredded)','1 tbsp yogurt','Squeeze lime'], ARRAY['Bake fish at 180°C 12 min; flake.','Mix cabbage with yogurt and lime.','Fill tortillas with fish and slaw.'], 5, 15, '{"omega3":"high","protein":"high","vitamin_c":"medium","calories":255}'),
('Tomato Soup & Grilled Cheese','Classic tomato soup with mini grilled cheese triangles.', 'baby', 'dinner', '31-36', 31, 36, 'meal', ARRAY['1 cup tomato soup (no salt)','1 slice wholegrain bread','2 tbsp cheese','1 tsp butter'], ARRAY['Warm tomato soup.','Make grilled cheese sandwich; cut into triangles.','Serve together.'], 5, 10, '{"vitamin_c":"high","calcium":"high","calories":245}');

-- ─── Age 31-36 months — Snack ────────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, baby_age_group, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, nutrition_info) VALUES
('Apple Slices & Nut Butter','Crisp apple slices with smooth almond or peanut butter.', 'baby', 'snack', '31-36', 31, 36, 'snack', ARRAY['1 apple','1 tbsp nut butter'], ARRAY['Slice apple.','Serve with nut butter for dipping.'], 3, '{"fiber":"high","protein":"medium","healthy_fats":"high","calories":145}'),
('Fruit Skewers',          'Colourful fruit skewers on short sticks — fun to eat.', 'baby', 'snack', '31-36', 31, 36, 'snack', ARRAY['Strawberries','Grapes (halved)','Melon chunks','Kiwi slices'], ARRAY['Thread fruit onto short skewers.','Serve immediately.'], 5, '{"vitamin_c":"very_high","fiber":"high","calories":75}'),
('Veggie Crackers & Dip',  'Whole grain crackers with cucumber tzatziki dip.', 'baby', 'snack', '31-36', 31, 36, 'snack', ARRAY['4 whole grain crackers','3 tbsp yogurt','¼ cucumber (grated)','Pinch of mint'], ARRAY['Grate cucumber; squeeze out water.','Mix with yogurt and mint.','Serve with crackers.'], 5, '{"calcium":"medium","fiber":"medium","calories":110}');


-- ═══════════════════════════════════════════════════════════════════════════
-- MUM RECIPES
-- Meal slots: early_morning | breakfast | mid_morning | lunch | evening | dinner | bedtime
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── Early Morning ────────────────────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('Warm Lemon Water',        'Start the day with a glass of warm lemon water to kickstart digestion and hydration.', 'mum', 'early_morning', 0, 36, 'meal', ARRAY['1 glass warm water','Juice of ½ lemon'], ARRAY['Warm water to comfortable temperature.','Squeeze in lemon juice.','Drink before eating.'], 2, 0, '{"vitamin_c":"high","hydration":"excellent","calories":5}'),
('Soaked Almonds & Raisins','5 soaked almonds and a few raisins — traditional postpartum energy booster.', 'mum', 'early_morning', 0, 36, 'meal', ARRAY['5 almonds (soaked overnight)','1 tbsp raisins'], ARRAY['Soak almonds overnight in water.','Peel skin and eat with raisins.'], 1, 0, '{"healthy_fats":"high","iron":"medium","calcium":"medium","calories":85}'),
('Methi Seeds Water',       'Fenugreek seed water — traditionally supports breast milk supply and digestion.', 'mum', 'early_morning', 0, 36, 'meal', ARRAY['1 tsp methi (fenugreek) seeds','1 glass warm water'], ARRAY['Soak methi seeds overnight.','Strain and drink the water in the morning.'], 1, 0, '{"iron":"high","galactagogue":"yes","calories":10}'),
('Ajwain Water',            'Carom seed water — helps relieve postpartum gas and bloating.', 'mum', 'early_morning', 0, 36, 'meal', ARRAY['½ tsp ajwain (carom) seeds','1 glass warm water'], ARRAY['Boil seeds in water 5 min.','Strain, cool slightly and drink.'], 1, 5, '{"digestive_aid":"yes","anti_bloat":"yes","calories":5}');

-- ─── Breakfast ───────────────────────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('Oatmeal with Flaxseeds', 'Creamy oat porridge with flaxseeds and berries — high in DHA precursors and fibre.', 'mum', 'breakfast', 0, 36, 'meal', ARRAY['½ cup oats','1 cup whole milk','1 tbsp ground flaxseeds','Fresh berries','1 tsp honey'], ARRAY['Cook oats in milk 5 min.','Stir in flaxseeds.','Top with berries and honey.'], 3, 5, '{"omega3":"high","calcium":"high","fiber":"high","calories":280}'),
('Spinach & Paneer Paratha','Iron-rich spinach and protein-packed paneer stuffed flatbread.', 'mum', 'breakfast', 0, 36, 'meal', ARRAY['2 whole wheat parathas','½ cup spinach (blanched, chopped)','50g paneer (grated)','Pinch cumin','Ghee'], ARRAY['Mix spinach and paneer with cumin.','Stuff into paratha dough and roll.','Cook on tawa with ghee until golden.','Serve with yogurt.'], 10, 10, '{"iron":"high","protein":"high","calcium":"high","calories":320}'),
('Avocado Toast with Egg', 'Smashed avocado on multigrain toast topped with poached egg.', 'mum', 'breakfast', 0, 36, 'meal', ARRAY['2 slices multigrain bread','½ avocado','1 egg','Cherry tomatoes','Pinch chilli flakes'], ARRAY['Toast bread.','Smash avocado with chilli flakes.','Poach egg 3 min.','Assemble and top with tomatoes.'], 8, 5, '{"healthy_fats":"high","protein":"high","folate":"high","calories":340}'),
('Ragi Porridge',          'Finger millet porridge — exceptional calcium source for new mums.', 'mum', 'breakfast', 0, 36, 'meal', ARRAY['3 tbsp ragi flour','1½ cups milk','1 tbsp jaggery','Pinch cardamom','Chopped dates'], ARRAY['Mix ragi in small amount of cold milk.','Heat remaining milk; add ragi paste stirring constantly.','Cook 8 min until thick.','Add jaggery and cardamom.','Top with dates.'], 5, 8, '{"calcium":"very_high","iron":"high","calories":260}'),
('Moong Dal Cheela',       'Protein-packed green moong pancakes — light and easy to digest.', 'mum', 'breakfast', 0, 36, 'meal', ARRAY['½ cup moong dal (soaked 4h)','1 tbsp grated ginger','Green chilli (optional)','Onion','Coriander','Oil'], ARRAY['Blend soaked dal to smooth batter.','Add ginger, onion, coriander.','Pour onto hot oiled pan; spread thin.','Cook 3 min per side.'], 10, 10, '{"protein":"very_high","iron":"high","folate":"high","calories":240}');

-- ─── Mid Morning ─────────────────────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, nutrition_info) VALUES
('Fruit & Nut Bowl',       'Seasonal fruits with a handful of mixed nuts for sustained energy.', 'mum', 'mid_morning', 0, 36, 'snack', ARRAY['1 banana','½ cup papaya (diced)','1 tbsp mixed nuts (almonds, walnuts)','1 tbsp pumpkin seeds'], ARRAY['Dice fruit into bowl.','Top with nuts and seeds.','Enjoy fresh.'], 5, '{"healthy_fats":"high","potassium":"high","omega3":"medium","calories":195}'),
('Yogurt & Granola Cup',   'Probiotic-rich yogurt with wholesome granola and kiwi.', 'mum', 'mid_morning', 0, 36, 'snack', ARRAY['1 cup full-fat yogurt','3 tbsp low-sugar granola','1 kiwi (sliced)'], ARRAY['Layer yogurt in cup.','Add granola.','Top with kiwi slices.'], 3, '{"calcium":"high","probiotics":"yes","vitamin_c":"high","calories":220}'),
('Peanut Butter Banana Toast','Wholegrain toast with peanut butter and banana slices.', 'mum', 'mid_morning', 0, 36, 'snack', ARRAY['1 slice wholegrain toast','1 tbsp peanut butter','½ banana (sliced)','1 tsp chia seeds'], ARRAY['Toast bread.','Spread peanut butter.','Top with banana and chia seeds.'], 3, '{"protein":"medium","healthy_fats":"high","omega3":"medium","calories":240}'),
('Dry Fruits Ladoo',       'Energy-dense sweet balls made from dates, nuts and seeds — traditional postpartum food.', 'mum', 'mid_morning', 0, 36, 'snack', ARRAY['5 dates (pitted)','2 tbsp mixed nuts','1 tbsp sesame seeds','1 tbsp desiccated coconut','Pinch cardamom'], ARRAY['Process dates in blender.','Mix in crushed nuts, seeds and coconut.','Roll into small balls.','Refrigerate 30 min.'], 10, '{"iron":"high","calcium":"high","healthy_fats":"high","calories":175}');

-- ─── Lunch ───────────────────────────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('Dal Rice with Ghee',     'Classic comforting dal and rice — iron, protein and warming for postpartum recovery.', 'mum', 'lunch', 0, 36, 'meal', ARRAY['½ cup toor dal','1 cup basmati rice','1 tsp ghee','Turmeric','Cumin','Tomato','Onion'], ARRAY['Cook rice separately.','Pressure cook dal.','Temper with ghee, cumin, onion and tomato.','Serve dal over rice with a drizzle of ghee.'], 5, 25, '{"protein":"high","iron":"high","carbs":"high","calories":380}'),
('Salmon & Quinoa Bowl',   'Omega-3 packed salmon over quinoa with steamed greens.', 'mum', 'lunch', 0, 36, 'meal', ARRAY['120g salmon fillet','½ cup quinoa','Handful spinach','Cherry tomatoes','Lemon dressing'], ARRAY['Cook quinoa 15 min.','Bake salmon 15 min at 190°C.','Wilt spinach.','Assemble bowl; drizzle with lemon dressing.'], 5, 20, '{"omega3":"very_high","protein":"very_high","iron":"high","calories":420}'),
('Chicken & Chickpea Salad','Protein-rich salad with grilled chicken, chickpeas and leafy greens.', 'mum', 'lunch', 0, 36, 'meal', ARRAY['100g grilled chicken','½ cup chickpeas','Mixed salad leaves','Cherry tomatoes','Cucumber','Tahini dressing'], ARRAY['Grill chicken and slice.','Toss chickpeas and salad.','Add chicken on top.','Drizzle tahini dressing.'], 10, 10, '{"protein":"very_high","iron":"high","fiber":"high","calories":390}'),
('Pumpkin & Lentil Soup',  'Silky pumpkin and lentil soup loaded with vitamins and iron.', 'mum', 'lunch', 0, 36, 'meal', ARRAY['200g pumpkin','¼ cup red lentils','1 onion','2 cloves garlic','Vegetable stock','Cream'], ARRAY['Roast pumpkin at 200°C 20 min.','Sauté onion and garlic.','Add lentils and stock; simmer 20 min.','Blend smooth; stir in cream.'], 10, 40, '{"vitamin_a":"very_high","iron":"high","protein":"medium","calories":290}'),
('Rajma Chawal',           'Kidney beans curry with rice — classic iron and protein powerhouse.', 'mum', 'lunch', 0, 36, 'meal', ARRAY['½ cup rajma (kidney beans, cooked)','1 cup rice','Onion','Tomato','Ginger garlic paste','Spices','Ghee'], ARRAY['Cook rajma in pressure cooker.','Prepare onion-tomato gravy.','Add rajma; simmer 15 min.','Serve over steamed rice with ghee.'], 10, 30, '{"iron":"very_high","protein":"high","fiber":"high","calories":410}');

-- ─── Evening ─────────────────────────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('Masala Chai with Milk',  'Warm spiced tea with full-fat milk — comforting afternoon pick-me-up.', 'mum', 'evening', 0, 36, 'meal', ARRAY['1 cup whole milk','1 tea bag or 1 tsp loose tea','½ tsp ginger','Pinch cinnamon','1 tsp jaggery'], ARRAY['Boil milk with ginger and cinnamon.','Add tea; steep 3 min.','Strain; sweeten with jaggery.'], 2, 5, '{"calcium":"high","anti_inflammatory":"yes","calories":110}'),
('Roasted Makhana',        'Ghee-roasted fox nuts — crunchy calcium-rich snack.', 'mum', 'evening', 0, 36, 'snack', ARRAY['1 cup makhana (fox nuts)','1 tsp ghee','Pinch rock salt','Pinch pepper'], ARRAY['Heat ghee in pan.','Add makhana; roast stirring 5 min until crisp.','Sprinkle salt and pepper.','Cool and serve.'], 2, 5, '{"calcium":"high","protein":"medium","calories":160}'),
('Vegetable Soup',         'Light broth-based vegetable soup to bridge between lunch and dinner.', 'mum', 'evening', 0, 36, 'meal', ARRAY['Mixed veg (carrot, pea, corn, beans)','2 cups vegetable stock','1 tsp olive oil','Herbs'], ARRAY['Sauté veg in oil 3 min.','Add stock; simmer 15 min.','Season with herbs.'], 5, 15, '{"fiber":"high","vitamins":"high","calories":120}'),
('Hummus & Veggie Plate',  'Store-bought or homemade hummus with raw and lightly cooked vegetables.', 'mum', 'evening', 0, 36, 'snack', ARRAY['4 tbsp hummus','Carrot sticks','Cucumber sticks','Bell pepper strips','Multigrain crackers'], ARRAY['Arrange vegetables and crackers.','Serve with hummus for dipping.'], 5, 0, '{"protein":"medium","fiber":"high","iron":"medium","calories":175}');

-- ─── Dinner ──────────────────────────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('Palak Paneer with Roti', 'Iron-loaded spinach curry with protein-rich paneer and whole wheat roti.', 'mum', 'dinner', 0, 36, 'meal', ARRAY['100g paneer','2 cups spinach','Onion','Tomato','Cream','Spices','Whole wheat roti'], ARRAY['Blanch and blend spinach.','Sauté onion, tomato and spices.','Add spinach puree; simmer 10 min.','Add paneer and cream.','Serve with roti.'], 10, 20, '{"iron":"very_high","protein":"high","calcium":"high","calories":380}'),
('Baked Herb Chicken',     'Oven-baked chicken breast with herbs and roasted vegetables.', 'mum', 'dinner', 0, 36, 'meal', ARRAY['150g chicken breast','Mixed herbs','Olive oil','Lemon','Broccoli','Sweet potato','Bell pepper'], ARRAY['Marinate chicken in herbs, oil and lemon 20 min.','Bake at 190°C 25 min.','Roast veg alongside last 20 min.','Serve together.'], 25, 25, '{"protein":"very_high","vitamin_a":"high","iron":"medium","calories":350}'),
('Fish Curry & Brown Rice','DHA-rich fish curry with fibre-packed brown rice.', 'mum', 'dinner', 0, 36, 'meal', ARRAY['150g fish (salmon or mackerel)','Coconut milk','Tomato','Onion','Curry leaves','Mustard seeds','Brown rice'], ARRAY['Cook brown rice 35 min.','Sauté onion with mustard seeds and curry leaves.','Add tomato; cook 5 min.','Add fish and coconut milk; simmer 12 min.','Serve over rice.'], 10, 35, '{"omega3":"very_high","protein":"high","fiber":"high","calories":420}'),
('Methi & Tofu Sabzi',     'Fenugreek leaves with tofu — iron-rich, calcium-packed and traditionally good for lactation.', 'mum', 'dinner', 0, 36, 'meal', ARRAY['1 bunch methi leaves','100g firm tofu','Onion','Tomato','Spices','Oil'], ARRAY['Press and cube tofu; pan-fry until golden.','Sauté onion and tomato with spices.','Add methi leaves; wilt 5 min.','Add tofu; mix gently.','Serve with roti or rice.'], 10, 15, '{"iron":"very_high","calcium":"high","galactagogue":"yes","calories":280}'),
('Pasta Primavera',        'Whole grain pasta with spring vegetables in olive oil and garlic.', 'mum', 'dinner', 0, 36, 'meal', ARRAY['100g whole grain pasta','Mixed veg (zucchini, cherry tomato, asparagus)','3 cloves garlic','Olive oil','Parmesan','Basil'], ARRAY['Cook pasta al dente.','Sauté garlic in oil 1 min.','Add veg; cook 5 min.','Toss pasta with veg.','Top with parmesan and basil.'], 5, 15, '{"fiber":"high","vitamin_c":"high","carbs":"high","calories":360}');

-- ─── Bedtime ─────────────────────────────────────────────────────────────
INSERT INTO recipes (title, description, target, meal_slot, age_range_min_months, age_range_max_months, recipe_type, ingredients, instructions, prep_time_minutes, cooking_time_minutes, nutrition_info) VALUES
('Golden Milk',            'Turmeric milk — anti-inflammatory, promotes sleep and supports recovery.', 'mum', 'bedtime', 0, 36, 'meal', ARRAY['1 cup warm whole milk','½ tsp turmeric','Pinch black pepper','Pinch cinnamon','½ tsp honey'], ARRAY['Warm milk gently.','Whisk in turmeric, pepper and cinnamon.','Sweeten with honey.','Drink warm.'], 3, 3, '{"calcium":"high","anti_inflammatory":"yes","tryptophan":"yes","calories":120}'),
('Warm Milk & Dates',      'Warm milk with soft dates — traditional sleep-promoting bedtime ritual.', 'mum', 'bedtime', 0, 36, 'meal', ARRAY['1 cup warm whole milk','2–3 Medjool dates (pitted)'], ARRAY['Warm milk.','Eat dates alongside warm milk.'], 2, 2, '{"calcium":"high","iron":"medium","magnesium":"high","calories":175}'),
('Chamomile & Honey Tea',  'Calming chamomile tea with honey to wind down before sleep.', 'mum', 'bedtime', 0, 36, 'meal', ARRAY['1 chamomile tea bag','1 cup hot water','1 tsp honey'], ARRAY['Steep chamomile in hot water 5 min.','Remove bag; stir in honey.','Drink while warm.'], 2, 5, '{"calming":"yes","anti_anxiety":"yes","calories":25}'),
('Banana & Almond Snack',  'Half banana with a few almonds — magnesium and tryptophan for better sleep.', 'mum', 'bedtime', 0, 36, 'snack', ARRAY['½ banana','5 almonds'], ARRAY['Slice banana.','Eat with almonds.'], 1, 0, '{"magnesium":"high","tryptophan":"yes","healthy_fats":"medium","calories":95}'),
('Ashwagandha Milk',       'Warm milk with ashwagandha — supports stress reduction and hormonal balance.', 'mum', 'bedtime', 0, 36, 'meal', ARRAY['1 cup warm whole milk','¼ tsp ashwagandha powder','1 tsp honey','Pinch cardamom'], ARRAY['Warm milk.','Whisk in ashwagandha and cardamom.','Sweeten with honey.'], 3, 3, '{"adaptogen":"yes","calcium":"high","stress_relief":"yes","calories":130}');
