-- Migration 012: Seed activities
-- Creates at least 12 activities per month group covering all categories and sub-categories

-- ─── Month range 1-3 ─────────────────────────────────────────────────────────
INSERT INTO activities (title, description, category, sub_category, month_min, month_max, duration_minutes, difficulty_level, benefits, frequency, materials_needed, instructions, done_count, is_premium) VALUES
('Tummy Time', 'Place baby on their tummy while awake and supervised to strengthen neck and shoulder muscles.', 'physical', 'Gross Motor', 1, 3, 5, 'easy', ARRAY['Strengthens neck muscles','Develops upper body strength','Prepares for crawling'], 'Daily', ARRAY['Play mat','Small rolled towel'], 'Place baby face-down on a firm, flat surface. Stay nearby and interact with them. Start with 1-2 minutes and increase gradually.', 28000, false),
('Track the Toy', 'Hold a brightly colored toy 8-12 inches from baby''s face and slowly move it side to side to encourage visual tracking.', 'cognitive', 'Memory and Attention', 1, 3, 10, 'easy', ARRAY['Develops visual tracking','Strengthens eye muscles','Encourages focus'], 'Daily', ARRAY['Brightly colored toy','Rattle'], 'Hold toy in front of baby at eye level. Slowly move it left and right, then up and down. Follow the baby''s gaze.', 25000, false),
('Sing a Lullaby', 'Sing a simple, repetitive song to your baby to stimulate language development and bonding.', 'communication', 'Speech Development', 1, 3, 10, 'easy', ARRAY['Introduces rhythm and language','Promotes bonding','Soothes baby'], 'Daily', ARRAY[]::TEXT[], 'Choose a short simple song. Sing softly and clearly, making eye contact. Repeat the same songs frequently so baby learns to anticipate them.', 24000, false),
('Eye Contact Game', 'Hold baby close and make sustained eye contact, responding to their expressions with smiles and gentle sounds.', 'social', 'Self Esteem', 1, 3, 5, 'easy', ARRAY['Builds secure attachment','Encourages social awareness','Develops emotional recognition'], 'Daily', ARRAY[]::TEXT[], 'Hold baby at face level about 10 inches away. Make eye contact and smile. Mirror baby''s expressions back to them.', 22000, true),
('Hand Grasp Exploration', 'Place your finger in baby''s palm to encourage their natural grasp reflex and develop finger awareness.', 'physical', 'Fine Motor', 1, 3, 5, 'easy', ARRAY['Strengthens grip','Develops hand awareness','Encourages tactile exploration'], 'Daily', ARRAY['Soft rattles','Textured rings'], 'Gently place your clean finger in the center of baby''s open palm. Allow them to curl their fingers around yours. Try with different soft objects.', 20000, true),
('Talk to Me', 'Narrate your daily activities to your baby, describing what you see and do in simple language.', 'communication', 'Language Comprehension', 1, 3, 10, 'easy', ARRAY['Builds vocabulary foundation','Develops listening skills','Strengthens language comprehension'], 'Daily', ARRAY[]::TEXT[], 'As you go about your day, describe what you are doing in simple words. Use a warm, engaging tone. Pause and wait for baby to respond with sounds.', 21000, true),
('Gentle Stretching', 'Gently move baby''s arms and legs through a range of motion during diaper changes or after baths.', 'physical', 'Bilateral Coordination', 1, 3, 5, 'easy', ARRAY['Promotes body awareness','Develops coordination','Eases muscle tension'], '3 times per week', ARRAY['Soft surface','Warm room'], 'During diaper change, gently move baby''s legs in a bicycle motion. Slowly raise arms above head and out to the sides. Always be gentle.', 19000, true),
('Mirror Discovery', 'Hold baby in front of a mirror and let them see their own reflection to build self-awareness.', 'cognitive', 'Thinking Expansion', 1, 3, 8, 'easy', ARRAY['Builds self-awareness','Stimulates visual curiosity','Encourages social engagement'], 'Daily', ARRAY['Safe baby mirror'], 'Hold baby about 8 inches from a baby-safe mirror. Watch their reaction as they discover their reflection. Smile and react alongside them.', 17000, true),
('Texture Touch Blanket', 'Introduce different fabric textures under baby''s hands to stimulate sensory exploration.', 'cognitive', 'Early Knowledge', 1, 3, 8, 'easy', ARRAY['Develops tactile senses','Encourages curiosity','Builds sensory processing'], '3 times per week', ARRAY['Soft blanket','Satin cloth','Terrycloth'], 'Lay baby on their back. Guide their hands across different textured fabrics. Name each texture with a simple word like "soft" or "rough".', 16000, true),
('Baby Coo Response', 'Respond to every sound your baby makes to encourage vocal communication and turn-taking.', 'communication', 'Thought Expression', 1, 3, 10, 'easy', ARRAY['Encourages vocal exploration','Develops conversational turn-taking','Builds confidence'], 'Daily', ARRAY[]::TEXT[], 'When baby makes a sound, respond with an encouraging sound or word. Pause and wait for baby to respond again. Continue this dialogue.', 18000, true),
('Finger Puppet Play', 'Use simple finger puppets to create engaging visual and social interactions with baby.', 'social', 'Social Skills & Awareness', 1, 3, 8, 'easy', ARRAY['Develops social awareness','Stimulates imagination foundation','Encourages eye contact'], 'Daily', ARRAY['Finger puppets'], 'Put a colorful finger puppet on your finger. Move it slowly in front of baby. Make different sounds and voices for each puppet.', 15000, true),
('Reach for Rattle', 'Dangle a rattle within baby''s reach to encourage them to extend their arms and practice grasping.', 'physical', 'Hand-Eye-Spatial', 1, 3, 8, 'easy', ARRAY['Develops hand-eye coordination','Encourages purposeful reaching','Strengthens arm muscles'], 'Daily', ARRAY['Light rattle','Colorful toy'], 'Hold a rattle about 6 inches above baby. Gently shake it to attract attention. Slowly move it until baby reaches for it. Cheer when they touch it.', 14000, true);

-- ─── Month range 4-6 ─────────────────────────────────────────────────────────
INSERT INTO activities (title, description, category, sub_category, month_min, month_max, duration_minutes, difficulty_level, benefits, frequency, materials_needed, instructions, done_count, is_premium) VALUES
('Supported Sitting Practice', 'Help baby practice sitting upright with support to develop core strength and balance.', 'physical', 'Gross Motor', 4, 6, 10, 'easy', ARRAY['Builds core strength','Develops balance','Strengthens back muscles'], 'Daily', ARRAY['Boppy pillow','Cushions'], 'Sit on the floor with legs spread. Place baby between your legs facing out. Provide back support with your body. Let them practice bearing their weight.', 20000, false),
('Object Permanence Peek', 'Hide a toy under a cloth and encourage baby to find it to develop object permanence understanding.', 'cognitive', 'Memory and Attention', 4, 6, 10, 'medium', ARRAY['Develops object permanence','Builds memory skills','Encourages problem-solving'], 'Daily', ARRAY['Soft cloth','Favorite toy'], 'Show baby a toy, then slowly cover it with a cloth while they watch. Ask "Where did it go?" and help them lift the cloth to find it. Celebrate discovery.', 18000, false),
('Babbling Response Game', 'Encourage and respond to baby''s babbling sounds to build early language skills.', 'communication', 'Speech Development', 4, 6, 10, 'easy', ARRAY['Encourages babbling','Develops speech sounds','Builds conversational skills'], 'Daily', ARRAY[]::TEXT[], 'When baby babbles, repeat their sounds back with enthusiasm. Add a simple word that starts with the same sound. Wait for them to respond again.', 17000, false),
('Sensory Bottle Exploration', 'Fill clear bottles with colorful materials for baby to shake and observe, stimulating curiosity.', 'cognitive', 'Early Knowledge', 4, 6, 10, 'easy', ARRAY['Stimulates visual curiosity','Develops cause and effect understanding','Encourages exploration'], 'Daily', ARRAY['Clear plastic bottle','Colored water','Small beads'], 'Fill a sealed bottle with water and colorful glitter. Let baby grasp and shake it. Describe what they see: "Look at the colors swirl!"', 16000, true),
('Rolling Over Practice', 'Encourage baby to roll from back to tummy by placing toys just out of reach on the side.', 'physical', 'Bilateral Coordination', 4, 6, 10, 'medium', ARRAY['Develops core muscles','Encourages rolling motion','Builds body coordination'], 'Daily', ARRAY['Play mat','Colorful toy'], 'Place baby on their back. Put an interesting toy to one side just out of reach. Gently guide their hip if needed. Cheer when they roll.', 15000, true),
('Pat-a-Cake Rhyme', 'Play pat-a-cake with baby, guiding their hands through the motions of the classic rhyme.', 'physical', 'Fine Motor', 4, 6, 8, 'easy', ARRAY['Develops hand coordination','Introduces rhythm','Encourages imitation'], 'Daily', ARRAY[]::TEXT[], 'Hold baby''s hands and clap them together while singing pat-a-cake. Exaggerate movements. Repeat several times. Baby will start anticipating the motions.', 19000, true),
('Cause and Effect Toys', 'Introduce toys that respond to baby''s actions (press button → music plays) to teach cause and effect.', 'cognitive', 'Concept Learning', 4, 6, 10, 'easy', ARRAY['Develops cause-and-effect thinking','Builds problem-solving skills','Encourages exploration'], 'Daily', ARRAY['Activity gym','Pop-up toy'], 'Place baby in front of a cause-and-effect toy. Guide their hand to activate it. Watch their surprise and excitement. Let them repeat the action.', 14000, true),
('Supported Standing', 'Hold baby in a standing position on your lap to develop leg strength and introduce weight-bearing.', 'physical', 'Gross Motor', 4, 6, 5, 'easy', ARRAY['Strengthens leg muscles','Develops balance awareness','Prepares for standing'], 'Daily', ARRAY[]::TEXT[], 'Hold baby upright on your lap facing you. Support their torso as they push down with their legs. Let them bounce gently.', 13000, true),
('Name Recognition Game', 'Repeatedly call baby''s name and reward with a smile when they turn toward you.', 'communication', 'Language Comprehension', 4, 6, 8, 'easy', ARRAY['Teaches name recognition','Builds auditory attention','Encourages responsive communication'], 'Daily', ARRAY[]::TEXT[], 'When baby is distracted, call their name clearly. When they look at you, give a big smile and say "Yes! That''s you!" Repeat from different positions.', 16000, true),
('Stranger Comfort', 'Introduce baby to trusted friends and family to develop healthy social awareness and comfort with others.', 'social', 'Social Skills & Awareness', 4, 6, 15, 'easy', ARRAY['Develops social comfort','Reduces stranger anxiety gradually','Builds trust'], 'Weekly', ARRAY[]::TEXT[], 'While you hold baby, introduce them to a trusted person. Let the person talk to baby from a comfortable distance. Gradually allow closer interaction if baby is comfortable.', 12000, true),
('Texture Food Introduction', 'Introduce different pureed textures to develop oral sensory processing and food awareness.', 'cognitive', 'Thinking Expansion', 4, 6, 15, 'easy', ARRAY['Develops oral sensory processing','Introduces food variety','Encourages adventurous eating'], '3 times per week', ARRAY['Pureed fruits','Pureed vegetables','Baby spoon'], 'Offer a small amount of a new pureed food. Watch baby''s expression. Name the food: "This is sweet potato!" Celebrate their exploration.', 11000, true),
('Bilat Arm Clapping', 'Guide baby to clap both hands together to develop bilateral coordination and rhythm.', 'physical', 'Bilateral Coordination', 4, 6, 5, 'easy', ARRAY['Develops bilateral coordination','Encourages midline crossing','Builds rhythm awareness'], 'Daily', ARRAY[]::TEXT[], 'Hold both of baby''s hands and gently guide them to clap together. Add a simple chant: "Clap, clap, clap!" Repeat rhythmically.', 13000, true);

-- ─── Month range 7-9 ─────────────────────────────────────────────────────────
INSERT INTO activities (title, description, category, sub_category, month_min, month_max, duration_minutes, difficulty_level, benefits, frequency, materials_needed, instructions, done_count, is_premium) VALUES
('Crawling Encouragement', 'Place enticing toys just out of reach during tummy time to encourage forward movement and crawling.', 'physical', 'Gross Motor', 7, 9, 15, 'medium', ARRAY['Develops crawling pattern','Strengthens arms and legs','Builds spatial awareness'], 'Daily', ARRAY['Play mat','Colorful toys','Tunnel'], 'During tummy time, place a favorite toy 12 inches in front of baby. Encourage them to reach. Help by gently supporting their tummy. Cheer every attempt.', 17000, false),
('Shape Sorter Introduction', 'Introduce a simple shape sorter to develop problem-solving, spatial reasoning, and fine motor skills.', 'cognitive', 'Concept Learning', 7, 9, 10, 'medium', ARRAY['Develops spatial reasoning','Builds problem-solving skills','Improves fine motor control'], 'Daily', ARRAY['Simple shape sorter (2-3 shapes)'], 'Show baby how to put a circle through the matching hole. Let them try. Offer guidance without taking over. Celebrate success enthusiastically.', 15000, false),
('First Words Pointing', 'Point to common objects around the home and say their names clearly to build vocabulary.', 'communication', 'Language Comprehension', 7, 9, 10, 'easy', ARRAY['Builds vocabulary','Teaches word-object association','Develops listening comprehension'], 'Daily', ARRAY['Picture books','Common household objects'], 'Walk around the room pointing to objects. Say each name clearly: "That is a chair." Repeat frequently. Use the same word consistently for each object.', 16000, false),
('Pull to Stand Practice', 'Use furniture or your hands to let baby practice pulling themselves to a standing position.', 'physical', 'Gross Motor', 7, 9, 10, 'medium', ARRAY['Strengthens leg muscles','Builds standing balance','Develops gross motor coordination'], 'Daily', ARRAY['Stable low furniture','Baby-safe table'], 'Hold your fingers out to baby while they are seated. Encourage them to grasp and pull themselves up. Provide minimal assistance. Applaud their effort.', 13000, true),
('Pincer Grasp Practice', 'Offer small safe snacks or objects to encourage baby to use their thumb and index finger together.', 'physical', 'Finger Dexterity', 7, 9, 10, 'medium', ARRAY['Develops pincer grasp','Strengthens finger control','Prepares for writing'], 'Daily', ARRAY['Puffs or small soft foods','Small textured objects'], 'Place small age-appropriate puffs on the high chair tray one at a time. Encourage baby to pick them up with two fingers. Demonstrate the motion yourself.', 14000, true),
('Memory Matching Game', 'Use two sets of identical simple pictures to introduce matching and memory concepts.', 'cognitive', 'Memory and Attention', 7, 9, 10, 'medium', ARRAY['Develops visual memory','Encourages matching skills','Builds concentration'], 'Daily', ARRAY['2 pairs of simple picture cards'], 'Show baby two identical pictures side by side. Point to one and say "Same!" Start with just 2 pairs. Let baby touch and explore the cards.', 12000, true),
('Wave Bye-Bye', 'Teach baby to wave goodbye by consistently modeling the gesture during departures.', 'communication', 'Speech Development', 7, 9, 8, 'easy', ARRAY['Develops gestural communication','Builds social awareness','Encourages imitation'], 'Daily', ARRAY[]::TEXT[], 'Every time you or someone leaves, wave and say "Bye-bye!" clearly. Guide baby''s hand to wave. Over time, baby will start initiating the gesture.', 18000, true),
('Stacking Cups', 'Provide a set of stacking cups to develop spatial awareness and hand-eye coordination through play.', 'physical', 'Hand-Eye-Spatial', 7, 9, 10, 'easy', ARRAY['Develops spatial awareness','Improves hand-eye coordination','Encourages cause-and-effect play'], 'Daily', ARRAY['Set of stacking cups'], 'Stack 3 cups and let baby knock them down. Then show how to stack them again. Describe actions: "Up! Now it''s tall. Knock it down!"', 20000, true),
('Music and Movement', 'Play upbeat music and move baby''s body in time with the rhythm to develop musical awareness.', 'social', 'Social Skills & Awareness', 7, 9, 10, 'easy', ARRAY['Develops rhythm awareness','Encourages body movement','Promotes joyful social interaction'], 'Daily', ARRAY['Music player','Age-appropriate music'], 'Hold baby and dance gently to music. Clap their hands in time. Name the rhythm: "Fast!" or "Slow!" Change movements with the music.', 17000, true),
('Articulation Sounds Practice', 'Teach baby to imitate consonant sounds like ba-ba, ma-ma, da-da through playful repetition.', 'communication', 'Articulation & Reasoning', 7, 9, 8, 'easy', ARRAY['Develops early consonant sounds','Builds speech foundations','Encourages imitation'], 'Daily', ARRAY[]::TEXT[], 'Get baby''s attention and say "ba-ba-ba" slowly and clearly. Wait for them to try. Reward any attempt with enthusiasm. Try different consonants each day.', 15000, true),
('Cause and Effect Banging', 'Give baby safe objects to bang together and on surfaces to explore cause and effect through sound.', 'cognitive', 'Thinking Expansion', 7, 9, 10, 'easy', ARRAY['Develops cause-and-effect reasoning','Explores sound production','Builds confidence in exploration'], 'Daily', ARRAY['Wooden spoon','Plastic containers','Pots'], 'Place baby in front of containers and a wooden spoon. Let them bang freely. Name the sounds: "Bang! Loud!" Introduce different surfaces.', 16000, true),
('Social Smile Imitation', 'Make exaggerated facial expressions for baby to imitate, building social-emotional connection.', 'social', 'Self Esteem', 7, 9, 8, 'easy', ARRAY['Develops emotional recognition','Builds facial imitation skills','Strengthens bonding'], 'Daily', ARRAY[]::TEXT[], 'Sit face to face with baby. Make a big smile, then look surprised, then sad. Name each expression. Wait for baby to try imitating. Celebrate their attempts.', 14000, true);

-- ─── Month range 10-12 ───────────────────────────────────────────────────────
INSERT INTO activities (title, description, category, sub_category, month_min, month_max, duration_minutes, difficulty_level, benefits, frequency, materials_needed, instructions, done_count, is_premium) VALUES
('Cruising Along Furniture', 'Encourage baby to walk sideways holding onto stable furniture to develop walking skills.', 'physical', 'Gross Motor', 10, 12, 15, 'medium', ARRAY['Strengthens leg muscles','Develops balance','Prepares for independent walking'], 'Daily', ARRAY['Stable sofa or table','Baby-proofed room'], 'Place interesting toys along a stable couch. Position baby at one end and encourage them to move sideways toward the toy. Stay close for safety.', 15000, false),
('Simple Puzzle Play', 'Introduce a 2-3 piece knob puzzle to develop problem-solving and fine motor skills.', 'cognitive', 'Concept Learning', 10, 12, 10, 'medium', ARRAY['Develops problem-solving','Builds fine motor skills','Introduces shapes and matching'], 'Daily', ARRAY['2-3 piece knob puzzle'], 'Remove all puzzle pieces. Show one piece and where it belongs. Let baby try to put it in. Provide guidance by gently rotating piece. Celebrate completion.', 14000, false),
('First Words Encouragement', 'Create situations that naturally elicit baby''s first words by pausing expectantly before key words.', 'communication', 'Speech Development', 10, 12, 10, 'easy', ARRAY['Encourages first words','Builds word-object association','Develops expressive language'], 'Daily', ARRAY['Favorite toys','Picture books'], 'Read a familiar book. When you get to a word baby knows, pause and look at them expectantly. When they attempt the word, celebrate enthusiastically.', 13000, false),
('Ball Roll Back-and-Forth', 'Roll a ball to baby and teach them to roll it back to develop turn-taking and social skills.', 'social', 'Social Skills & Awareness', 10, 12, 10, 'easy', ARRAY['Develops turn-taking skills','Builds social play skills','Improves gross motor control'], 'Daily', ARRAY['Soft ball'], 'Sit facing baby with legs spread. Roll a ball gently toward them. Say "Your turn!" and wait for them to push or roll it back. Celebrate the exchange.', 16000, true),
('Scribbling with Crayons', 'Give baby large non-toxic crayons on paper to begin exploring mark-making and creativity.', 'physical', 'Finger Dexterity', 10, 12, 10, 'easy', ARRAY['Develops grip strength','Introduces mark-making','Encourages creativity'], 'Daily', ARRAY['Large crayons','Thick paper'], 'Tape paper to a table or tray. Give baby a large crayon and show how to move it across the paper. Let them explore freely. Name the colors they use.', 12000, true),
('Body Part Naming', 'Name and touch different body parts to build vocabulary and body awareness.', 'cognitive', 'Early Knowledge', 10, 12, 8, 'easy', ARRAY['Builds body vocabulary','Develops self-awareness','Encourages listening comprehension'], 'Daily', ARRAY['Safe mirror'], 'Touch your nose and say "Nose!" then touch baby''s nose. Repeat with eyes, ears, mouth. Ask "Where is your nose?" and guide their hand if needed.', 17000, true),
('Imitation Play', 'Use pretend play tools like toy phones and spoons to encourage baby to imitate adult actions.', 'cognitive', 'Imagination', 10, 12, 10, 'easy', ARRAY['Develops imitation skills','Introduces pretend play','Builds cognitive connections'], 'Daily', ARRAY['Toy phone','Toy spoon','Toy brush'], 'Pretend to talk on a toy phone. Hand it to baby and see if they hold it to their ear. Pretend to eat with a spoon. Encourage baby to copy you.', 11000, true),
('Walking with Support', 'Hold both of baby''s hands and help them take steps to develop walking confidence and coordination.', 'physical', 'Gross Motor', 10, 12, 15, 'medium', ARRAY['Develops walking pattern','Builds leg strength','Boosts confidence'], 'Daily', ARRAY[]::TEXT[], 'Stand behind baby and hold both hands at shoulder height. Encourage them to step forward. Let them set the pace. Gradually reduce support as confidence grows.', 14000, true),
('Simple Story Telling', 'Tell baby simple 2-3 sentence stories with gestures to develop narrative understanding.', 'communication', 'Language Comprehension', 10, 12, 10, 'easy', ARRAY['Develops narrative comprehension','Builds vocabulary','Encourages listening attention'], 'Daily', ARRAY['Simple picture books'], 'Open a picture book and tell a very simple story about the pictures in 2-3 sentences. Point to characters and actions. Use expressive voice and gestures.', 13000, true),
('Emotion Mirror Play', 'Exaggerate emotions in front of a mirror with baby to develop emotional vocabulary.', 'social', 'Self Esteem', 10, 12, 8, 'easy', ARRAY['Builds emotional vocabulary','Develops self-recognition','Encourages empathy foundations'], 'Daily', ARRAY['Safe mirror'], 'Stand with baby in front of a mirror. Make a happy face: "Happy!" Then sad face: "Sad!" Then surprised. Point to baby''s reflection when they copy you.', 12000, true),
('Container Fill and Empty', 'Provide containers and safe objects to fill and empty to develop spatial reasoning and fine motor skills.', 'cognitive', 'Thinking Expansion', 10, 12, 10, 'easy', ARRAY['Develops spatial reasoning','Builds fine motor skills','Teaches in-and-out concepts'], 'Daily', ARRAY['Small bucket','Large blocks','Large balls'], 'Show baby how to drop blocks into a container and tip them out. Say "In!" and "Out!" as you play. Let baby repeat independently.', 15000, true),
('Clapping Rhythm Songs', 'Sing songs with actions and teach baby to clap along to develop rhythm and bilateral coordination.', 'physical', 'Bilateral Coordination', 10, 12, 8, 'easy', ARRAY['Develops rhythm','Builds bilateral coordination','Encourages musical engagement'], 'Daily', ARRAY[]::TEXT[], 'Sing "If You''re Happy and You Know It." Clap baby''s hands together on the clapping parts. Repeat multiple times until baby begins to anticipate the claps.', 16000, true);

-- ─── Month range 13-15 ───────────────────────────────────────────────────────
INSERT INTO activities (title, description, category, sub_category, month_min, month_max, duration_minutes, difficulty_level, benefits, frequency, materials_needed, instructions, done_count, is_premium) VALUES
('Independent Walking Practice', 'Create a safe path of interesting objects to motivate independent walking practice.', 'physical', 'Gross Motor', 13, 15, 20, 'medium', ARRAY['Develops independent walking','Improves balance','Builds confidence'], 'Daily', ARRAY['Baby-proofed space','Favorite toys'], 'Clear a safe walking path. Place a favorite toy at the end. Encourage baby to walk to it. Reduce hand-holding gradually. Celebrate every step.', 13000, false),
('Color Sorting Game', 'Sort objects by color into matching colored containers to develop color recognition and sorting skills.', 'cognitive', 'Concept Learning', 13, 15, 10, 'medium', ARRAY['Develops color recognition','Builds sorting skills','Encourages logical thinking'], 'Daily', ARRAY['Colored blocks or balls','Colored containers or cups'], 'Have 2 colors of blocks and 2 matching colored cups. Show baby how to put the red block in the red cup. Let them try. Praise every correct match.', 12000, false),
('Two-Word Request Practice', 'Teach baby to use two-word combinations by modeling and creating need situations.', 'communication', 'Speech Development', 13, 15, 10, 'easy', ARRAY['Develops two-word phrases','Builds expressive vocabulary','Encourages communication initiative'], 'Daily', ARRAY['Snacks','Favorite toys'], 'Hold a toy out of reach and wait. When baby reaches or grunts, model "More ball." Pause. If they attempt it, give the toy. Build on whatever words they already use.', 11000, false),
('Simple Puzzle Solving', 'Use a 4-6 piece simple puzzle to develop problem-solving, spatial reasoning, and persistence.', 'cognitive', 'Articulation & Reasoning', 13, 15, 15, 'medium', ARRAY['Builds problem-solving skills','Develops spatial reasoning','Encourages persistence'], 'Daily', ARRAY['4-6 piece knob puzzle'], 'Remove all pieces. Show baby the complete image. Let them choose a piece. Guide them by rotating the piece near its slot. Avoid solving it for them.', 10000, true),
('Block Building', 'Stack blocks with baby to develop spatial awareness, fine motor skills, and cause-and-effect play.', 'physical', 'Hand-Eye-Spatial', 13, 15, 10, 'medium', ARRAY['Develops spatial awareness','Builds fine motor control','Encourages cause-and-effect thinking'], 'Daily', ARRAY['Large soft blocks or wooden blocks'], 'Stack 3-4 blocks slowly. Let baby knock them down. Then help them stack. Count blocks as you add them: "One, two, three!"', 11000, true),
('Pretend Play Kitchen', 'Use toy kitchen items to engage in simple pretend play and develop imagination.', 'cognitive', 'Imagination', 13, 15, 15, 'easy', ARRAY['Develops imagination','Builds symbolic thinking','Encourages social role play'], 'Daily', ARRAY['Toy pots','Toy spoons','Play food'], 'Sit with baby and pretend to cook. Stir a pot and say "Yum, soup!" Offer them a pretend bite. Encourage them to stir and serve. Follow their lead.', 12000, true),
('Simple Instructions Following', 'Give baby one-step instructions like "Give me the ball" to develop comprehension and following directions.', 'communication', 'Language Comprehension', 13, 15, 10, 'easy', ARRAY['Develops instruction comprehension','Builds listening skills','Encourages cooperative communication'], 'Daily', ARRAY['Various toys'], 'Ask baby to "Give me the ball" or "Put the cup down." Start with objects they know. Wait patiently. Demonstrate if needed. Celebrate compliance.', 10000, true),
('Outdoor Walk Exploration', 'Take baby on a slow outdoor walk to explore the environment and develop sensory awareness and vocabulary.', 'cognitive', 'Early Knowledge', 13, 15, 20, 'easy', ARRAY['Develops sensory awareness','Builds vocabulary','Encourages curiosity about the world'], 'Weekly', ARRAY['Stroller or walking shoes'], 'Walk slowly and stop frequently. Point to things: "Flower! Dog! Car!" Let baby touch safe textures. Pick up a leaf and examine it together.', 14000, true),
('Parallel Play Playdate', 'Arrange a playdate with another toddler to encourage parallel play and social observation skills.', 'social', 'Social Skills & Awareness', 13, 15, 30, 'easy', ARRAY['Develops social awareness','Introduces parallel play','Builds peer interaction skills'], 'Weekly', ARRAY['Duplicate toys to reduce conflict'], 'Set up a space with duplicate toys. Allow toddlers to play near each other without forcing interaction. Narrate what each child is doing. Gently facilitate sharing.', 9000, true),
('Big Emotions Naming', 'Label baby''s emotions as they experience them to develop emotional vocabulary and self-regulation.', 'social', 'Self Esteem', 13, 15, 5, 'easy', ARRAY['Builds emotional vocabulary','Develops self-awareness','Lays foundation for self-regulation'], 'Daily', ARRAY[]::TEXT[], 'When baby shows an emotion, name it: "You seem frustrated." "You look so happy!" Stay calm and empathetic. Validate the feeling before redirecting.', 13000, true),
('Finger Dexterity Threading', 'Thread large beads on a thick cord to develop fine motor control and concentration.', 'physical', 'Finger Dexterity', 13, 15, 10, 'medium', ARRAY['Develops fine motor control','Builds concentration','Improves hand-eye coordination'], 'Daily', ARRAY['Large wooden beads','Thick cord or shoelace'], 'Show baby how to thread a bead onto a thick lace. Let them try. Start with large holes. Praise effort regardless of success. Make it a game not a test.', 8000, true),
('Scribble to Drawing', 'Introduce large sheets of paper and chunky crayons to develop intentional mark-making.', 'physical', 'Fine Motor', 13, 15, 10, 'easy', ARRAY['Develops fine motor skills','Encourages creative expression','Introduces intentional mark-making'], 'Daily', ARRAY['Large paper','Chunky crayons'], 'Tape a large paper to the floor. Give chunky crayons and let baby draw freely. Comment on their work: "I see a big circle!" Do not demonstrate what to draw.', 11000, true);

-- ─── Month range 16-18 ───────────────────────────────────────────────────────
INSERT INTO activities (title, description, category, sub_category, month_min, month_max, duration_minutes, difficulty_level, benefits, frequency, materials_needed, instructions, done_count, is_premium) VALUES
('Running and Stopping Game', 'Play games that involve running and stopping on command to develop gross motor control.', 'physical', 'Gross Motor', 16, 18, 15, 'medium', ARRAY['Develops running coordination','Builds stopping control','Improves gross motor planning'], 'Daily', ARRAY['Open outdoor space'], 'Play "Run, run, STOP!" in a safe open space. Run alongside baby. Freeze dramatically on "stop." Encourage them to freeze too. Giggle and restart.', 10000, false),
('Animal Sound Matching', 'Match toy animals to their sounds or pictures to develop vocabulary and logical association.', 'cognitive', 'Concept Learning', 16, 18, 10, 'medium', ARRAY['Builds vocabulary','Develops categorization skills','Encourages logical association'], 'Daily', ARRAY['Toy animals','Animal sound book'], 'Hold up a toy cow. Ask "What does the cow say?" Model "Moo!" Play with a few animals. Vary the order each time to check real understanding.', 9000, false),
('Three-Word Sentence Practice', 'Model and encourage three-word sentences to extend baby''s expressive language.', 'communication', 'Speech Development', 16, 18, 10, 'easy', ARRAY['Develops three-word phrases','Builds expressive vocabulary','Encourages sentence structure'], 'Daily', ARRAY['Snacks','Toys','Picture books'], 'When baby says a word like "more," expand it: "More juice please!" Repeat their words back in a sentence. Create situations where they need to ask.', 8000, false),
('Memory Book Making', 'Help toddler glue pictures into a simple photo album to develop memory, sequencing, and narrative skills.', 'cognitive', 'Memory and Attention', 16, 18, 20, 'easy', ARRAY['Develops memory and narrative','Builds sequencing skills','Strengthens identity and belonging'], '2 times per week', ARRAY['Simple photo album','Family photos','Safe glue stick'], 'Gather simple family photos. Help baby stick them into an album. Name people and events: "That is grandma at the park." Review the album together regularly.', 7000, true),
('Obstacle Course Navigation', 'Set up a simple indoor obstacle course to develop problem-solving and gross motor skills.', 'physical', 'Bilateral Coordination', 16, 18, 20, 'medium', ARRAY['Develops body coordination','Builds problem-solving','Encourages physical confidence'], '3 times per week', ARRAY['Cushions','Tunnels','Low steps'], 'Set up a simple course: crawl through tunnel, step over cushion, climb onto low step. Demonstrate each step. Let baby navigate independently. Cheer every section.', 6000, true),
('Pretend Play Dressing', 'Use a box of simple dress-up clothes to engage in imaginative play and develop self-care skills.', 'cognitive', 'Imagination', 16, 18, 20, 'easy', ARRAY['Develops imagination','Builds dressing skills','Encourages role play'], 'Daily', ARRAY['Simple dress-up hats','Shoes','Bags'], 'Put a hat on yourself and say "I am a firefighter!" Offer baby a hat. Follow their lead. Name their costume. Take photos to reinforce the play narrative.', 8000, true),
('Question Answering Practice', 'Ask baby simple yes/no questions to develop early reasoning and communication skills.', 'communication', 'Articulation & Reasoning', 16, 18, 8, 'easy', ARRAY['Develops yes/no reasoning','Builds communication confidence','Encourages early logical thinking'], 'Daily', ARRAY['Familiar objects'], 'Hold up a ball and ask "Is this a ball?" Wait for yes/no response. Then ask "Is this a dog?" (while holding ball). Celebrate correct answers with enthusiasm.', 9000, true),
('Finger Painting', 'Use safe finger paints on paper to develop sensory exploration and creative expression.', 'physical', 'Finger Dexterity', 16, 18, 15, 'easy', ARRAY['Develops tactile sensory processing','Encourages creative expression','Builds fine motor exploration'], 'Weekly', ARRAY['Non-toxic finger paints','Paper','Old clothes'], 'Put a small amount of paint on paper. Let baby explore freely with their fingers. Name colors they use. Display their artwork afterward to build pride.', 10000, true),
('Helping with Chores', 'Involve toddler in simple household tasks to develop responsibility, coordination, and sense of belonging.', 'social', 'Social Skills & Awareness', 16, 18, 15, 'easy', ARRAY['Builds sense of responsibility','Develops coordination','Encourages cooperation'], 'Daily', ARRAY['Child-safe household tools'], 'Give baby a small dustpan to sweep with you, or have them put soft laundry in a basket. Say "Thank you for helping!" Make it feel important.', 11000, true),
('Feelings Book Reading', 'Read books about feelings to help toddler identify and name emotions.', 'social', 'Self Esteem', 16, 18, 10, 'easy', ARRAY['Builds emotional vocabulary','Develops empathy','Encourages emotional expression'], 'Daily', ARRAY['Emotions picture book'], 'Read a simple book about feelings. Point to faces: "He looks sad. When do you feel sad?" Relate to baby''s own experiences. Never force answers.', 10000, true),
('Shape Tracing', 'Guide baby''s hand to trace simple shapes to develop spatial awareness and hand control.', 'physical', 'Hand-Eye-Spatial', 16, 18, 10, 'medium', ARRAY['Develops hand control','Builds shape recognition','Improves hand-eye coordination'], 'Daily', ARRAY['Shape cards','Finger paint or marker'], 'Draw a large circle. Guide baby''s finger around the outline. Say "Round and round!" Try square and triangle next. Progress to letting them trace alone.', 7000, true),
('Thinking Out Loud', 'Model thinking aloud while solving simple everyday problems to develop reasoning awareness.', 'cognitive', 'Thinking Expansion', 16, 18, 10, 'easy', ARRAY['Develops reasoning awareness','Builds problem-solving vocabulary','Encourages logical thinking'], 'Daily', ARRAY['Everyday objects'], 'While solving a small problem, say your thinking aloud: "The cup is too full, so I will pour some out." Ask baby what you should do next.', 6000, true);

-- ─── Month range 19-21 ───────────────────────────────────────────────────────
INSERT INTO activities (title, description, category, sub_category, month_min, month_max, duration_minutes, difficulty_level, benefits, frequency, materials_needed, instructions, done_count, is_premium) VALUES
('Kicking a Ball', 'Practice kicking a stationary ball to develop leg coordination, balance, and gross motor control.', 'physical', 'Gross Motor', 19, 21, 15, 'medium', ARRAY['Develops leg coordination','Builds balance on one foot','Improves gross motor planning'], 'Daily', ARRAY['Soft ball','Open space'], 'Place a soft ball on the ground. Stand next to baby and model kicking it. Encourage them to kick. Cheer any contact. Progress to a rolling ball.', 8000, false),
('Number Concept Introduction', 'Count small groups of objects to introduce the concept that numbers represent quantity.', 'cognitive', 'Concept Learning', 19, 21, 10, 'medium', ARRAY['Develops number sense','Introduces counting concepts','Builds mathematical foundation'], 'Daily', ARRAY['Small groups of objects (blocks, fruit)'], 'Place 2-3 objects in front of baby. Touch each one as you count: "One, two, three blocks." Let baby try counting. Any attempt is a success.', 7000, false),
('Story Retelling', 'After reading a familiar book, encourage toddler to retell what happened to develop narrative and memory.', 'communication', 'Thought Expression', 19, 21, 15, 'easy', ARRAY['Develops narrative skills','Builds memory and sequencing','Encourages expressive language'], 'Daily', ARRAY['Familiar picture book'], 'Read a familiar book. Close it and ask "What happened first?" Help with prompts: "And then?" Show pictures if needed. Accept any order or simplification.', 9000, false),
('Balance Beam Walking', 'Walk along a low tape line or balance beam to develop body balance and spatial awareness.', 'physical', 'Gross Motor', 19, 21, 15, 'medium', ARRAY['Develops balance','Builds spatial awareness','Improves core strength'], 'Daily', ARRAY['Tape or low balance board'], 'Put a strip of tape on the floor. Show baby how to walk along it putting one foot in front of the other. Hold their hand at first. Gradually reduce support.', 7000, true),
('Scissor Skills Introduction', 'Practice opening and closing child-safe scissors to develop hand strength and coordination.', 'physical', 'Fine Motor', 19, 21, 10, 'medium', ARRAY['Develops hand strength','Builds scissor skills','Improves bilateral hand coordination'], '3 times per week', ARRAY['Child-safe safety scissors','Paper strips'], 'Show baby how to open and close the scissors. Let them practice on thick paper strips. Guide their hand. Snipping in any direction is a success at first.', 5000, true),
('Nature Exploration Journal', 'Collect natural items on walks and create a simple nature journal to develop observation skills.', 'cognitive', 'Early Knowledge', 19, 21, 20, 'easy', ARRAY['Develops observation skills','Builds scientific curiosity','Encourages vocabulary expansion'], 'Weekly', ARRAY['Notebook','Safe collected leaves and flowers','Glue stick'], 'On a walk, collect safe items: leaves, flowers, pebbles. At home, examine them with a magnifier. Help baby glue them into a journal. Name and describe each item.', 6000, true),
('Dramatic Play Characters', 'Take on character roles in play scenarios to develop imagination and narrative thinking.', 'cognitive', 'Imagination', 19, 21, 20, 'easy', ARRAY['Develops narrative imagination','Builds social role understanding','Encourages creative expression'], 'Daily', ARRAY['Simple props','Dress-up clothes'], 'Set up a simple scenario: a shop, a hospital, a kitchen. Take on a character role and invite baby to take one too. Follow the story where they lead.', 8000, true),
('Why and How Questions', 'Ask simple why and how questions during play to develop reasoning and language skills.', 'communication', 'Articulation & Reasoning', 19, 21, 10, 'easy', ARRAY['Develops reasoning skills','Builds causal vocabulary','Encourages explanatory language'], 'Daily', ARRAY['Play scenarios'], 'During play, ask "Why is the bear sad?" or "How can we fix it?" Accept creative answers. Say "That is a great idea!" and build on their response.', 7000, true),
('Peer Play Cooperation', 'Arrange cooperative play scenarios with another child to practice sharing and joint goals.', 'social', 'Social Skills & Awareness', 19, 21, 30, 'medium', ARRAY['Develops cooperative play skills','Builds sharing and turn-taking','Encourages peer communication'], 'Weekly', ARRAY['Shared toys','Building blocks'], 'With another child, set a joint goal: build a tower together. Facilitate turns: "Now James puts a block." Narrate cooperation positively.', 6000, true),
('Proud Moment Sharing', 'Celebrate toddler achievements by encouraging them to show their work to others.', 'social', 'Self Esteem', 19, 21, 10, 'easy', ARRAY['Builds confidence','Develops sense of accomplishment','Encourages pride in effort'], 'Daily', ARRAY[]::TEXT[], 'When baby completes something, say "Show Daddy what you made!" Encourage them to present it. Celebrate the effort as much as the result.', 9000, true),
('Threading and Lacing', 'Thread laces through boards or large beads to develop fine motor precision and concentration.', 'physical', 'Finger Dexterity', 19, 21, 10, 'medium', ARRAY['Develops fine motor precision','Builds concentration','Improves hand-eye coordination'], 'Daily', ARRAY['Lacing board or large lacing beads'], 'Show baby how to push the lace through a hole in the lacing board. Let them try. Help only when they are truly stuck. Increase difficulty gradually.', 5000, true),
('Spatial Concept Play', 'Teach spatial concepts like in, on, under, beside by placing objects in different positions.', 'cognitive', 'Thinking Expansion', 19, 21, 10, 'easy', ARRAY['Develops spatial language','Builds spatial reasoning','Encourages following directions'], 'Daily', ARRAY['Box','Small toy animals'], 'Use a box and a toy. Put it in the box: "In!" Put it on top: "On!" Put it under: "Under!" Then ask baby to do it. Make it a guessing game.', 7000, true);

-- ─── Month range 22-24 ───────────────────────────────────────────────────────
INSERT INTO activities (title, description, category, sub_category, month_min, month_max, duration_minutes, difficulty_level, benefits, frequency, materials_needed, instructions, done_count, is_premium) VALUES
('Jumping Practice', 'Practice two-footed jumping on the spot and over small obstacles to develop gross motor coordination.', 'physical', 'Gross Motor', 22, 24, 15, 'medium', ARRAY['Develops jumping mechanics','Builds leg power','Improves bilateral coordination'], 'Daily', ARRAY['Open space','Low foam block'], 'Show baby how to bend their knees and jump with both feet. Let them practice on the spot. Place a thin foam block to jump over. Celebrate height and distance.', 8000, false),
('Opposite Concepts', 'Teach opposites like big-small, fast-slow through play to develop conceptual thinking.', 'cognitive', 'Concept Learning', 22, 24, 10, 'medium', ARRAY['Develops conceptual thinking','Builds comparative vocabulary','Encourages analytical observation'], 'Daily', ARRAY['Objects of different sizes and speeds'], 'Use objects to demonstrate: big block and small block. Say "Big!" loudly, "Small!" quietly. Move quickly "Fast!" and slowly "Slow!" Ask baby to show you.', 7000, false),
('Conversation Practice', 'Have real conversations with toddler about their day to develop complex language and memory.', 'communication', 'Thought Expression', 22, 24, 15, 'easy', ARRAY['Develops conversational skills','Builds narrative language','Encourages memory recall'], 'Daily', ARRAY[]::TEXT[], 'At a calm moment, ask "What did you do today?" Use photos to prompt memory. Expand their answers into sentences. Ask follow-up questions. Listen attentively.', 9000, false),
('Controlled Drawing', 'Practice drawing specific shapes and lines to develop fine motor control and intentional mark-making.', 'physical', 'Fine Motor', 22, 24, 10, 'medium', ARRAY['Develops fine motor control','Builds intentional drawing','Improves pencil grip'], 'Daily', ARRAY['Crayons','Paper'], 'Draw a large circle and ask baby to copy it. Then try a vertical line and horizontal line. Avoid correcting their form. Describe what you see: "A round circle!"', 6000, true),
('Memory Sequence Game', 'Build a simple sequence of 3 actions and ask toddler to copy the sequence to develop working memory.', 'cognitive', 'Memory and Attention', 22, 24, 10, 'medium', ARRAY['Develops working memory','Builds sequential thinking','Encourages attention and focus'], 'Daily', ARRAY['Simple household objects'], 'Perform 3 simple actions: tap table, clap hands, touch nose. Ask baby to copy the sequence. Start with 2 steps. Increase to 3 as they succeed.', 7000, true),
('Collaborative Building', 'Work together on a building project to develop cooperation, communication, and spatial planning.', 'social', 'Social Skills & Awareness', 22, 24, 20, 'medium', ARRAY['Develops cooperative skills','Builds spatial planning','Encourages communication during play'], 'Daily', ARRAY['Large DUPLO blocks or cardboard boxes'], 'Propose a shared building goal: "Let us build a house for the bear." Take turns adding pieces. Talk about what you are building. Problem-solve together.', 8000, true),
('Concept of Sharing Practice', 'Practice sharing snacks equally to develop the concept of fairness and sharing.', 'social', 'Self Esteem', 22, 24, 10, 'easy', ARRAY['Develops concept of fairness','Builds sharing skills','Encourages prosocial behavior'], 'Daily', ARRAY['Snacks','Plates'], 'At snack time, share items between you and baby. Count out loud: "One for you, one for me." Name the action: "We are sharing!" Acknowledge their generosity.', 10000, true),
('Nature Sorting', 'Sort natural materials by color, size, or type to develop categorization and observation skills.', 'cognitive', 'Early Knowledge', 22, 24, 15, 'easy', ARRAY['Develops categorization skills','Builds scientific observation','Encourages sorting and classification'], '3 times per week', ARRAY['Leaves of different sizes','Pebbles','Sticks'], 'Collect natural items on a walk. At home, sort them into groups together. Name the sorting rule: "All the big ones here." Change the rule: "Now by color."', 6000, true),
('Fantasy Story Creation', 'Create original short stories together using random picture cards to develop narrative imagination.', 'cognitive', 'Imagination', 22, 24, 15, 'medium', ARRAY['Develops creative narrative skills','Builds imagination','Encourages expressive language'], 'Daily', ARRAY['Picture cards or magazine cut-outs'], 'Draw 3 random picture cards. Say "Once there was a..." pointing to first card. Ask "What happened next?" and point to second card. Build the story together.', 7000, true),
('Following Multi-Step Instructions', 'Give toddler two-step instructions to develop attention, language comprehension, and self-regulation.', 'communication', 'Language Comprehension', 22, 24, 10, 'easy', ARRAY['Develops instruction comprehension','Builds working memory','Encourages self-regulation'], 'Daily', ARRAY['Household objects'], 'Give a two-step instruction: "Get your shoes and put them by the door." Wait. If stuck, break it into steps. Praise completion of both steps together.', 8000, true),
('Throwing and Catching', 'Practice throwing a ball underhanded and catching at close range to develop hand-eye coordination.', 'physical', 'Hand-Eye-Spatial', 22, 24, 15, 'medium', ARRAY['Develops hand-eye coordination','Builds throwing and catching mechanics','Improves spatial judgment'], 'Daily', ARRAY['Large soft ball'], 'Stand 3 feet from baby. Toss the ball softly underhanded. Encourage them to catch it in their arms. Toss back and forth. Move a little farther when successful.', 9000, true),
('Understanding Reasoning', 'Use simple logical problems in play to develop early reasoning and cause-and-effect thinking.', 'cognitive', 'Articulation & Reasoning', 22, 24, 10, 'medium', ARRAY['Develops logical reasoning','Builds cause-and-effect understanding','Encourages analytical thinking'], 'Daily', ARRAY['Simple toys','Everyday scenarios'], 'During play, present a small problem: "The bridge fell down. Why?" Let baby guess. Try solutions together. Ask "What would happen if...?" questions.', 6000, true);

-- ─── Month range 25-27 ───────────────────────────────────────────────────────
INSERT INTO activities (title, description, category, sub_category, month_min, month_max, duration_minutes, difficulty_level, benefits, frequency, materials_needed, instructions, done_count, is_premium) VALUES
('Tricycle Riding', 'Practice pedaling a tricycle to develop leg coordination, bilateral movement, and spatial navigation.', 'physical', 'Gross Motor', 25, 27, 20, 'medium', ARRAY['Develops pedaling coordination','Builds leg strength','Improves spatial navigation'], 'Daily', ARRAY['Tricycle or balance bike','Safe path'], 'Start by pushing baby on the tricycle. Encourage them to use pedals. Demonstrate pedaling motion. Practice steering simple curves. Celebrate independence.', 7000, false),
('Size Sequencing', 'Arrange objects in order from smallest to largest to develop sequencing and comparative thinking.', 'cognitive', 'Concept Learning', 25, 27, 10, 'medium', ARRAY['Develops sequencing skills','Builds comparative thinking','Encourages ordered reasoning'], 'Daily', ARRAY['3-5 objects of graduated sizes','Nesting cups'], 'Jumble up 3-5 nesting cups. Ask baby to put them in order from smallest to biggest. Model the process. Discuss: "This one is smaller, this one is bigger."', 6000, false),
('Show and Tell Practice', 'Let toddler share a favorite object and talk about it to develop oral language and confidence.', 'communication', 'Thought Expression', 25, 27, 10, 'easy', ARRAY['Develops oral language skills','Builds confidence','Encourages topic organization'], 'Weekly', ARRAY['Favorite toy or object'], 'Ask baby to choose something special. Encourage them to tell you about it: "What is it? What does it do? Who gave it to you?" Listen attentively. Ask follow-up questions.', 8000, false),
('Stair Climbing Independence', 'Practice going up and down stairs alternating feet to develop gross motor coordination and balance.', 'physical', 'Gross Motor', 25, 27, 15, 'medium', ARRAY['Develops stair coordination','Builds bilateral foot alternation','Improves balance'], 'Daily', ARRAY['Stairs with handrail','Non-slip socks'], 'Stay right behind baby on stairs. Encourage alternating feet: "Right foot, left foot." Hold handrail. Gradually reduce the support you provide. Celebrate each flight.', 6000, true),
('Handwriting Readiness', 'Practice drawing horizontal and vertical lines, circles, and crosses to develop pre-writing skills.', 'physical', 'Fine Motor', 25, 27, 10, 'medium', ARRAY['Develops pre-writing skills','Builds pencil control','Improves visual-motor integration'], 'Daily', ARRAY['Thick pencil','Lined paper','Dotted lines to trace'], 'Draw a dotted straight line and ask baby to draw over it. Try horizontal, vertical, circle. Move to independent copying. Do not rush to letters before control is ready.', 5000, true),
('Memory Card Matching', 'Play a simple memory card game with 4-6 pairs to develop visual memory and strategic thinking.', 'cognitive', 'Memory and Attention', 25, 27, 15, 'medium', ARRAY['Develops visual memory','Builds strategic thinking','Encourages concentration'], 'Daily', ARRAY['4-6 pairs of matching picture cards'], 'Lay cards face down. Take turns flipping two at a time. Name what you find. Keep matched pairs. Talk about your strategy: "I think the dog is over there."', 7000, true),
('Creative Story Extension', 'Extend a favorite story by asking what happens next to develop creative and narrative thinking.', 'cognitive', 'Imagination', 25, 27, 15, 'easy', ARRAY['Develops creative narrative','Builds story structure understanding','Encourages creative thinking'], 'Daily', ARRAY['Familiar picture book'], 'After reading a book, close it and ask "What do you think happened after?" Accept all answers. Build a new chapter together. Draw a picture of the new ending.', 7000, true),
('Explaining Thinking', 'Ask toddler to explain their choices and decisions to develop meta-cognitive language.', 'communication', 'Articulation & Reasoning', 25, 27, 10, 'easy', ARRAY['Develops meta-cognitive language','Builds reasoning skills','Encourages self-explanation'], 'Daily', ARRAY[]::TEXT[], 'After a choice, ask "Why did you pick that?" Accept and expand their answer. Model your own thinking: "I chose blue because it is my favorite." Make it conversational.', 6000, true),
('Peer Conflict Resolution', 'Coach toddler through conflict resolution with a peer using words to develop social problem-solving.', 'social', 'Social Skills & Awareness', 25, 27, 20, 'medium', ARRAY['Develops conflict resolution skills','Builds peer communication','Encourages problem-solving in social contexts'], 'Weekly', ARRAY[]::TEXT[], 'When conflict arises, stay calm. Ask both children "What do you want?" Help them hear each other. Suggest solutions. Ask them to choose. Praise all attempts to use words.', 5000, true),
('Feelings Vocabulary Expansion', 'Introduce nuanced feeling words beyond happy and sad to develop emotional literacy.', 'social', 'Self Esteem', 25, 27, 10, 'easy', ARRAY['Builds nuanced emotional vocabulary','Develops emotional literacy','Encourages emotional expression'], 'Daily', ARRAY['Feelings flashcards'], 'Introduce new feeling words: frustrated, excited, nervous, proud. Use them in context: "I feel proud when I help someone." Ask about their feelings during the day.', 8000, true),
('Two-Handed Coordination', 'Practice activities requiring both hands to work together on separate tasks.', 'physical', 'Bilateral Coordination', 25, 27, 10, 'medium', ARRAY['Develops bilateral coordination','Builds hand specialization','Improves motor planning'], 'Daily', ARRAY['Play dough','Scissors and paper','Container with lid'], 'Roll play dough while holding it steady with the other hand. Open and close containers with both hands doing different jobs. Name what each hand is doing.', 5000, true),
('World Knowledge Questions', 'Explore interesting facts about animals, weather, and the natural world to develop early knowledge.', 'cognitive', 'Early Knowledge', 25, 27, 15, 'easy', ARRAY['Builds world knowledge','Develops scientific curiosity','Encourages question-asking'], 'Daily', ARRAY['Non-fiction picture books','Nature magazines'], 'Read a fact: "Penguins cannot fly but they swim." Ask "Why do you think they cannot fly?" and "What do you know about penguins?" Encourage wonder.', 6000, true);

-- ─── Month range 28-30 ───────────────────────────────────────────────────────
INSERT INTO activities (title, description, category, sub_category, month_min, month_max, duration_minutes, difficulty_level, benefits, frequency, materials_needed, instructions, done_count, is_premium) VALUES
('Hopping on One Foot', 'Practice hopping on one foot to develop unilateral balance and gross motor control.', 'physical', 'Gross Motor', 28, 30, 15, 'hard', ARRAY['Develops single-leg balance','Builds gross motor control','Improves proprioceptive awareness'], 'Daily', ARRAY['Open space'], 'Show baby how to stand on one foot while holding your hand. Try to hop. Count hops together. Gradually reduce hand support. Try both feet equally.', 6000, false),
('Pattern Recognition and Creation', 'Create simple AB or ABB patterns with objects and encourage baby to continue them.', 'cognitive', 'Concept Learning', 28, 30, 10, 'medium', ARRAY['Develops pattern recognition','Builds mathematical thinking','Encourages logical sequencing'], 'Daily', ARRAY['Colored blocks','Stickers','Beads'], 'Lay out a color pattern: red, blue, red, blue... Ask "What comes next?" Let baby add the piece. Create new patterns together. Clap patterns rhythmically too.', 5000, false),
('Full Sentence Storytelling', 'Encourage toddler to tell stories in full sentences by providing a clear beginning, middle, and end structure.', 'communication', 'Thought Expression', 28, 30, 15, 'medium', ARRAY['Develops full sentence use','Builds narrative structure','Encourages complex language'], 'Daily', ARRAY['Story prompts or picture sets'], 'Give baby 3 picture cards. Say "Use each picture to tell your story." Prompt: "What is happening? What happened next? How did it end?" Celebrate full sentences.', 7000, false),
('Throwing with Aim', 'Practice throwing small beanbags at targets to develop accuracy and hand-eye coordination.', 'physical', 'Hand-Eye-Spatial', 28, 30, 15, 'medium', ARRAY['Develops throwing accuracy','Builds hand-eye coordination','Improves spatial judgment'], 'Daily', ARRAY['Beanbags','Large target (hoop or bucket)'], 'Place a large bucket 3 feet away. Show baby how to throw a beanbag underhanded into it. Count successful throws. Move the bucket gradually farther away.', 6000, true),
('Matching Letters to Words', 'Point out the first letter of familiar words to introduce letter-sound awareness.', 'cognitive', 'Early Knowledge', 28, 30, 10, 'medium', ARRAY['Introduces letter-sound awareness','Develops reading readiness','Encourages literacy interest'], 'Daily', ARRAY['Alphabet cards','Simple word cards'], 'Point to the letter B on a card and say "B says buh, like BALL!" Find objects starting with B. Look for letters in books. Keep it playful and low-pressure.', 4000, true),
('Original Song Creation', 'Create a simple original song about everyday events to develop creativity and language.', 'cognitive', 'Imagination', 28, 30, 15, 'easy', ARRAY['Develops creative expression','Builds musical thinking','Encourages language play'], 'Daily', ARRAY[]::TEXT[], 'Start a simple song: "We are eating breakfast, breakfast, breakfast..." Invite baby to add words. Sing the song with their contributions. Record it as a keepsake.', 5000, true),
('Perspective-Taking Stories', 'Discuss story characters'' feelings and motivations to develop perspective-taking and empathy.', 'communication', 'Articulation & Reasoning', 28, 30, 15, 'medium', ARRAY['Develops perspective-taking','Builds empathy','Encourages complex language and reasoning'], 'Daily', ARRAY['Picture books with characters'], 'Read a story. Ask "How do you think the little bear felt when...?" "Why did she do that?" "What would you do?" Connect to baby''s own experiences.', 6000, true),
('Community Helper Role Play', 'Role-play as community helpers (doctor, firefighter, chef) to develop social awareness and vocabulary.', 'social', 'Social Skills & Awareness', 28, 30, 20, 'easy', ARRAY['Develops social role awareness','Builds vocabulary','Encourages cooperative role play'], 'Weekly', ARRAY['Role play kits or simple props'], 'Set up a doctor''s office, fire station, or restaurant. Assign roles. Play the scenario. Switch roles. Discuss what helpers do in real life.', 7000, true),
('Independence Encouragement', 'Set up tasks that toddler can complete independently to build confidence and self-efficacy.', 'social', 'Self Esteem', 28, 30, 15, 'easy', ARRAY['Builds independence','Develops self-efficacy','Encourages mastery motivation'], 'Daily', ARRAY['Simple self-care tools','Child-sized tasks'], 'Set up a simple task: pouring from a small pitcher, putting on shoes, or making a sandwich. Let baby try completely alone. Help only if asked. Praise the attempt.', 8000, true),
('Fine Motor Precision Tools', 'Use tweezers or tongs to pick up small objects to develop fine motor precision and control.', 'physical', 'Finger Dexterity', 28, 30, 10, 'hard', ARRAY['Develops fine motor precision','Builds grip strength','Improves hand-eye coordination'], 'Daily', ARRAY['Child-safe tongs','Pompoms or cotton balls','Sorting tray'], 'Place pompoms in a tray. Show baby how to pick them up with tongs and sort by color into cups. Time the activity to add challenge. Make it a game.', 4000, true),
('Complex Pattern Clapping', 'Clap increasingly complex rhythmic patterns and have toddler echo them back.', 'physical', 'Bilateral Coordination', 28, 30, 10, 'medium', ARRAY['Develops rhythm and pattern processing','Builds bilateral coordination','Encourages auditory memory'], 'Daily', ARRAY[]::TEXT[], 'Clap a 4-beat pattern: clap, clap, pause, clap. Ask baby to copy. Start simple and add complexity. Use different body parts: clap, stomp, slap thighs.', 5000, true),
('Basic Science Experiments', 'Do simple sink-or-float experiments to develop hypothesis-testing and scientific thinking.', 'cognitive', 'Thinking Expansion', 28, 30, 15, 'medium', ARRAY['Develops hypothesis testing','Builds scientific thinking','Encourages prediction and observation'], '2 times per week', ARRAY['Bowl of water','Various small objects'], 'Before placing each object in water, ask "Will it sink or float?" Let baby predict, then test. Discuss results: "You were right, the rock sank!" Record results with drawings.', 5000, true);

-- ─── Month range 31-33 ───────────────────────────────────────────────────────
INSERT INTO activities (title, description, category, sub_category, month_min, month_max, duration_minutes, difficulty_level, benefits, frequency, materials_needed, instructions, done_count, is_premium) VALUES
('Skipping Introduction', 'Practice the skip movement pattern to develop complex bilateral gross motor coordination.', 'physical', 'Gross Motor', 31, 33, 20, 'hard', ARRAY['Develops complex bilateral movement','Builds rhythm and coordination','Improves gross motor sequencing'], 'Daily', ARRAY['Open space'], 'Show baby the skipping pattern: step, hop, step, hop. Hold their hand at first. Exaggerate the hop. Practice to music for natural rhythm. Celebrate any approximation.', 5000, false),
('Subtraction Concept', 'Use physical objects to introduce simple subtraction (taking away) to develop number sense.', 'cognitive', 'Concept Learning', 31, 33, 10, 'hard', ARRAY['Develops subtraction concept','Builds number sense','Encourages mathematical reasoning'], 'Daily', ARRAY['5 small objects'], 'Place 4 blocks. Say "There are 4. I will take 1 away." Remove a block. "Now how many?" Count remaining. Do this with different numbers up to 5.', 5000, false),
('Complex Multi-Sentence Stories', 'Create and tell original complex stories with beginning, problem, and resolution to develop advanced narrative skills.', 'communication', 'Thought Expression', 31, 33, 20, 'medium', ARRAY['Develops complex narrative skills','Builds story structure','Encourages creative and expressive language'], 'Daily', ARRAY['Story props','Picture cards'], 'Give baby a character, a problem, and a setting card. Ask them to tell you the whole story. Help with structure: "What was the problem? How did they fix it?"', 6000, false),
('Skipping Rope Introduction', 'Practice jumping over a stationary or slowly swinging rope to develop coordination and timing.', 'physical', 'Bilateral Coordination', 31, 33, 15, 'hard', ARRAY['Develops bilateral coordination','Builds timing and rhythm','Improves jump mechanics'], 'Daily', ARRAY['Rope or skipping rope'], 'Lay rope on the ground. Jump over it with two feet. Then slowly swing it on the ground as baby jumps. Progress at their pace. Celebrate every successful jump.', 4000, true),
('Letter Formation Practice', 'Practice writing letters of their name to develop early literacy and fine motor control.', 'physical', 'Fine Motor', 31, 33, 15, 'hard', ARRAY['Develops letter formation','Builds fine motor control','Introduces early writing skills'], 'Daily', ARRAY['Pencil','Paper','Dotted letter guides'], 'Trace baby''s name with dots. Guide their pencil along the dots for the first letter of their name. Celebrate every attempt. Avoid criticism of letter formation at this stage.', 4000, true),
('Advanced Memory Game', 'Play a memory game with 8-10 pairs and talk through memory strategies.', 'cognitive', 'Memory and Attention', 31, 33, 15, 'hard', ARRAY['Develops advanced visual memory','Builds strategic thinking','Encourages metacognitive awareness'], 'Daily', ARRAY['8-10 pairs of picture cards'], 'Play a memory card game. After flipping, ask "How do you remember where things are?" Discuss strategies: "I make a picture in my mind." Praise any strategy used.', 4000, true),
('Imaginative World Building', 'Create a miniature world with small figures and environments to develop complex imaginative play.', 'cognitive', 'Imagination', 31, 33, 30, 'medium', ARRAY['Develops complex imaginative play','Builds narrative world-building','Encourages creative problem-solving'], 'Daily', ARRAY['Small figures','Building blocks','Natural materials'], 'Provide a tray with small figures, blocks, fabric, and natural items. Say "Let us build a world." Follow baby''s lead. Ask questions to expand the narrative.', 5000, true),
('Debate and Justification', 'Engage toddler in gentle debates about preferences to develop reasoning and justification skills.', 'communication', 'Articulation & Reasoning', 31, 33, 10, 'medium', ARRAY['Develops justification skills','Builds reasoning language','Encourages intellectual confidence'], 'Daily', ARRAY[]::TEXT[], 'Gently disagree with baby: "I think dogs are better than cats. What do you think?" Ask "Why?" multiple times. Model using reasons: "I think cats because they are quiet."', 5000, true),
('Team Cooperation Games', 'Play simple team games requiring cooperation to achieve a shared goal.', 'social', 'Social Skills & Awareness', 31, 33, 20, 'medium', ARRAY['Develops cooperation skills','Builds team communication','Encourages shared goal pursuit'], 'Weekly', ARRAY['Balloon','Beanbags','Simple team game'], 'Keep a balloon in the air together without letting it touch the floor. Carry an egg in a spoon together. Frame it as "us against the problem, not each other."', 6000, true),
('Personal Goal Setting', 'Help toddler set a simple weekly goal to develop autonomy, planning, and self-efficacy.', 'social', 'Self Esteem', 31, 33, 15, 'easy', ARRAY['Develops autonomy','Builds goal-setting skills','Encourages personal responsibility'], 'Weekly', ARRAY['Paper','Crayons'], 'At the start of the week, ask baby to choose one thing they want to learn. Draw a picture of the goal. Check in daily. Celebrate at week''s end regardless of outcome.', 6000, true),
('Spatial Reasoning Puzzles', 'Complete 20+ piece puzzles to develop advanced spatial reasoning and problem-solving persistence.', 'physical', 'Hand-Eye-Spatial', 31, 33, 20, 'hard', ARRAY['Develops spatial reasoning','Builds problem-solving persistence','Improves fine motor control'], 'Daily', ARRAY['20-piece jigsaw puzzle'], 'Do not solve the puzzle for baby. Suggest strategies: "Look for edge pieces first." "Find pieces with the same color." Let them struggle productively. Celebrate completion.', 4000, true),
('Growth Mindset Stories', 'Share stories about characters who improve through effort to develop a growth mindset.', 'cognitive', 'Thinking Expansion', 31, 33, 15, 'easy', ARRAY['Develops growth mindset','Builds resilience thinking','Encourages effort-focused language'], 'Weekly', ARRAY['Growth mindset books'], 'Read a book where a character struggles and improves. Ask "How did they get better?" Connect to baby''s own experiences. Say "You are getting better at this every day."', 5000, true);

-- ─── Month range 34-36 ───────────────────────────────────────────────────────
INSERT INTO activities (title, description, category, sub_category, month_min, month_max, duration_minutes, difficulty_level, benefits, frequency, materials_needed, instructions, done_count, is_premium) VALUES
('Pumping Swing Independently', 'Teach toddler to pump their legs on a swing to develop advanced bilateral coordination and spatial body awareness.', 'physical', 'Gross Motor', 34, 36, 20, 'hard', ARRAY['Develops independent swing pumping','Builds spatial body awareness','Improves bilateral rhythm'], 'Weekly', ARRAY['Swing'], 'Show baby the leg pump motion: pull back when going forward, push out when going back. Let them practice while you give small pushes. Gradually stop pushing.', 4000, false),
('Addition Concept', 'Use physical objects to introduce simple addition to develop early mathematical thinking.', 'cognitive', 'Concept Learning', 34, 36, 10, 'hard', ARRAY['Develops addition concept','Builds number sense','Encourages early mathematical reasoning'], 'Daily', ARRAY['5 small identical objects'], 'Place 2 blocks. Say "There are 2. Let us add 1 more." Add a block. "Now how many? Count them!" Progress to 2+2, 1+3. Use fingers as well as objects.', 4000, false),
('Full Narrative Monologue', 'Encourage toddler to describe their day in detail using past and future tense to develop advanced language.', 'communication', 'Thought Expression', 34, 36, 15, 'hard', ARRAY['Develops past and future tense use','Builds complex narration','Encourages detailed expressive language'], 'Daily', ARRAY[]::TEXT[], 'At bedtime, ask baby to tell you about their whole day. Prompt with "What happened at breakfast?" Use their words: "So after that, you...?" Celebrate every detail.', 5000, false),
('Complex Obstacle Course', 'Navigate a multi-step obstacle course requiring balance, coordination, and agility.', 'physical', 'Gross Motor', 34, 36, 20, 'hard', ARRAY['Develops complex motor sequencing','Builds agility and coordination','Encourages physical confidence'], 'Weekly', ARRAY['Balance board','Tunnel','Low hurdles','Balance stepping stones'], 'Build a 5-step course. Walk through it once together. Time baby if they enjoy competition. Change it each week. Ask them to add one new element to the design.', 3000, true),
('Scissor Cutting Precision', 'Practice cutting along curved and angled lines to develop advanced scissor control.', 'physical', 'Fine Motor', 34, 36, 15, 'hard', ARRAY['Develops advanced scissor control','Builds fine motor precision','Improves bilateral hand coordination'], 'Daily', ARRAY['Child-safe scissors','Guided cutting sheets'], 'Draw wavy and zigzag lines on paper. Ask baby to cut along them. Encourage holding paper with the other hand. Celebrate staying on the line. Progress to cutting out shapes.', 3000, true),
('Strategic Memory Games', 'Develop and articulate memory strategies for a 12-pair memory card game.', 'cognitive', 'Memory and Attention', 34, 36, 20, 'hard', ARRAY['Develops strategic memory skills','Builds metacognition','Encourages competitive play skills'], 'Daily', ARRAY['12 pairs of picture cards'], 'Play the 12-pair memory game. After, ask "What strategy helped you?" Introduce the location strategy: mentally placing cards on a map. Play again using the strategy.', 3000, true),
('World-Building Narrative Play', 'Create an extended multi-day imaginative world with rules, characters, and history.', 'cognitive', 'Imagination', 34, 36, 40, 'hard', ARRAY['Develops complex sustained imagination','Builds narrative world-building','Encourages creative planning'], 'Daily', ARRAY['Small figures','Building materials','Art supplies'], 'Build a world over several days. Give it a name. Create characters with backstories. Add new locations and problems. Ask "What happened in our world today?"', 4000, true),
('Constructive Argument Practice', 'Practice making and listening to arguments about everyday choices to develop reasoning confidence.', 'communication', 'Articulation & Reasoning', 34, 36, 15, 'hard', ARRAY['Develops argumentative reasoning','Builds confident language use','Encourages listening to opposing views'], 'Daily', ARRAY[]::TEXT[], 'Debate a simple topic: "Should we have a pet cat or a pet dog?" Each person gives 3 reasons. Practice listening without interrupting. Vote at the end. Celebrate good reasoning.', 4000, true),
('Community Project Participation', 'Involve toddler in a simple neighborhood or family community project to develop social responsibility.', 'social', 'Social Skills & Awareness', 34, 36, 60, 'medium', ARRAY['Develops social responsibility','Builds community awareness','Encourages prosocial behavior'], 'Monthly', ARRAY['Project-specific materials'], 'Choose a simple project: pick up litter on a walk, make cards for elderly neighbors, plant flowers. Give baby a real meaningful role. Discuss why helping others matters.', 5000, true),
('Resilience Through Failure', 'Set up appropriately challenging tasks where failure is likely, coaching toddler through the discomfort.', 'social', 'Self Esteem', 34, 36, 20, 'hard', ARRAY['Develops resilience','Builds failure tolerance','Encourages growth mindset'], 'Weekly', ARRAY['Challenging age-appropriate tasks'], 'Set a genuinely challenging task. When baby fails, stay calm: "That was hard! What can we try differently?" Model your own failure. Celebrate persistence over success.', 5000, true),
('Letter Sequence Recognition', 'Practice recognizing and ordering letters of their first name to develop early literacy skills.', 'physical', 'Finger Dexterity', 34, 36, 15, 'hard', ARRAY['Develops letter recognition','Builds early literacy foundation','Improves fine motor through letter tracing'], 'Daily', ARRAY['Letter tiles or cards','Name card'], 'Jumble up the letters of baby''s name. Ask them to arrange them in the right order by comparing to a name card. Progress to doing it from memory. Trace each letter.', 3000, true),
('Comparative and Superlative Language', 'Practice using comparative and superlative adjectives to develop advanced vocabulary and grammar.', 'communication', 'Language Comprehension', 34, 36, 10, 'hard', ARRAY['Develops comparative grammar','Builds advanced vocabulary','Encourages precise language use'], 'Daily', ARRAY['Objects of different sizes and qualities'], 'Compare objects: "This is big. This one is bigger. This one is the biggest!" Play guessing games using comparatives. Ask baby to describe which is faster, softer, louder.', 4000, true);
