-- Migration 030: Seed milestone definitions extracted from ui/babyG/milestones screenshots
-- Generated by scripts/extract-ui-milestones.py.

DO $$
BEGIN
  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    31, 'cognitive', 'Understand the setup and purpose of different locations like office mall theater; garden, gym; etc',
    'Understand the setup and purpose of different locations like office mall theater; garden, gym; etc', 'Understand the setup and purpose of different locations like office mall theater; garden, gym; etc', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 31
      AND milestone_type = 'cognitive'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    31, 'cognitive', 'Understands the concept of lock and makes attempts to open a lock independently',
    'Understands the concept of lock and makes attempts to open a lock independently', 'Understands the concept of lock and makes attempts to open a lock independently', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 31
      AND milestone_type = 'cognitive'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    31, 'cognitive', 'Understands the concept of weight and can differentiate and tell apart a very heavy and light object',
    'Understands the concept of weight and can differentiate and tell apart a very heavy and light object', 'Understands the concept of weight and can differentiate and tell apart a very heavy and light object', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 31
      AND milestone_type = 'cognitive'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    31, 'cognitive', 'Can recognize logical patterns For example ifa part ofan object is missing from a or the drawing is incomplete; the baby Indarctandc it',
    'Can recognize logical patterns For example ifa part ofan object is missing from a or the drawing is incomplete; the baby Indarctandc it', 'Can recognize logical patterns For example ifa part ofan object is missing from a or the drawing is incomplete; the baby Indarctandc it', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 31
      AND milestone_type = 'cognitive'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    31, 'cognitive', 'Talks to the toys and engages with them as real people during playtime can play with them alone',
    'Talks to the toys and engages with them as real people during playtime can play with them alone', 'Talks to the toys and engages with them as real people during playtime can play with them alone', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 31
      AND milestone_type = 'cognitive'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    31, 'cognitive', 'Knows where things usually belong in the house and things back in their place',
    'Knows where things usually belong in the house and things back in their place', 'Knows where things usually belong in the house and things back in their place', NULL, 6, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 31
      AND milestone_type = 'cognitive'
      AND display_order = 6
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    31, 'communication', 'Can tell names of family members like my sister''s name is this and my grandfather''s name is this',
    'Can tell names of family members like my sister''s name is this and my grandfather''s name is this', 'Can tell names of family members like my sister''s name is this and my grandfather''s name is this', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 31
      AND milestone_type = 'communication'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    31, 'communication', 'Understands sentences with simple concepts,_ control on language understanding',
    'Understands sentences with simple concepts,_ control on language understanding', 'Understands sentences with simple concepts,_ control on language understanding', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 31
      AND milestone_type = 'communication'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    31, 'communication', 'Talks to the toys andengages with them as real people during playtime can play with them alone',
    'Talks to the toys andengages with them as real people during playtime can play with them alone', 'Talks to the toys andengages with them as real people during playtime can play with them alone', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 31
      AND milestone_type = 'communication'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    31, 'communication', 'Knows where things usually belong in the house and put things back in their place',
    'Knows where things usually belong in the house and put things back in their place', 'Knows where things usually belong in the house and put things back in their place', NULL, 6, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 31
      AND milestone_type = 'communication'
      AND display_order = 6
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    31, 'physical', 'Reaches the knob, turns, and opens the door independently',
    'Reaches the knob, turns, and opens the door independently', 'Reaches the knob, turns, and opens the door independently', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 31
      AND milestone_type = 'physical'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    31, 'physical', 'Can walk up or down the stairs without any support like an adult',
    'Can walk up or down the stairs without any support like an adult', 'Can walk up or down the stairs without any support like an adult', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 31
      AND milestone_type = 'physical'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    31, 'social_emotional', 'Makes clear expressions when prompted with an expression word like a smile, sad face laugh; crying face, angry face, surprised face etc',
    'Makes clear expressions when prompted with an expression word like a smile, sad face laugh; crying face, angry face, surprised face etc', 'Makes clear expressions when prompted with an expression word like a smile, sad face laugh; crying face, angry face, surprised face etc', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 31
      AND milestone_type = 'social_emotional'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    31, 'social_emotional', 'Interested in new experiences, shows excitement even before the event',
    'Interested in new experiences, shows excitement even before the event', 'Interested in new experiences, shows excitement even before the event', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 31
      AND milestone_type = 'social_emotional'
      AND display_order = 2
  );

END $$;
