-- Migration 030: Seed milestone definitions extracted from ui/babyG/milestones screenshots
-- Generated by scripts/extract-ui-milestones.py.

DO $$
BEGIN
  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'cognitive', 'Able to identify basic shapes among objects seen in daily life when prompted, like "What shape is this table?" MI What shape is the food plate?", etc',
    'Able to identify basic shapes among objects seen in daily life when prompted, like "What shape is this table?" MI What shape is the food plate?", etc', 'Able to identify basic shapes among objects seen in daily life when prompted, like "What shape is this table?" MI What shape is the food plate?", etc', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'cognitive'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'cognitive', 'Understands the concept of numbers as a representation of quantity',
    'Understands the concept of numbers as a representation of quantity', 'Understands the concept of numbers as a representation of quantity', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'cognitive'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'cognitive', 'Can recognize 10 or more alphabets randomly, not necessarily in the sequence',
    'Can recognize 10 or more alphabets randomly, not necessarily in the sequence', 'Can recognize 10 or more alphabets randomly, not necessarily in the sequence', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'cognitive'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'cognitive', 'Can identify and name 4-6 shapes like circle square, triangle, star; rectangle, etc',
    'Can identify and name 4-6 shapes like circle square, triangle, star; rectangle, etc', 'Can identify and name 4-6 shapes like circle square, triangle, star; rectangle, etc', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'cognitive'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'communication', 'Can identify and count 1to 10 numbers, with limited understanding of the quantity',
    'Can identify and count 1to 10 numbers, with limited understanding of the quantity', 'Can identify and count 1to 10 numbers, with limited understanding of the quantity', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'communication'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'communication', 'Can identify 5-8 vegetables when see pictures or real vegetables',
    'Can identify 5-8 vegetables when see pictures or real vegetables', 'Can identify 5-8 vegetables when see pictures or real vegetables', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'communication'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'communication', 'Asks for assistance when needed with appropriate phrases like "Help me", "Iam stuck", etc',
    'Asks for assistance when needed with appropriate phrases like "Help me", "Iam stuck", etc', 'Asks for assistance when needed with appropriate phrases like "Help me", "Iam stuck", etc', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'communication'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'communication', 'Often uses personal pronouns correctly (l you; he, it, me, etc)',
    'Often uses personal pronouns correctly (l you; he, it, me, etc)', 'Often uses personal pronouns correctly (l you; he, it, me, etc)', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'communication'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'communication', 'Correctly and clearly pronounces all vowel sounds A, E,I,0,U',
    'Correctly and clearly pronounces all vowel sounds A, E,I,0,U', 'Correctly and clearly pronounces all vowel sounds A, E,I,0,U', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'communication'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'communication', 'Requests or asks for permission when they want anything or do any activities',
    'Requests or asks for permission when they want anything or do any activities', 'Requests or asks for permission when they want anything or do any activities', NULL, 6, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'communication'
      AND display_order = 6
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'communication', 'Uses negative words for eg leave the phone no phone, don''t do it, etc',
    'Uses negative words for eg leave the phone no phone, don''t do it, etc', 'Uses negative words for eg leave the phone no phone, don''t do it, etc', NULL, 7, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'communication'
      AND display_order = 7
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'physical', 'Able to take off clothes such as socks or pants with little help or no help',
    'Able to take off clothes such as socks or pants with little help or no help', 'Able to take off clothes such as socks or pants with little help or no help', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'physical'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'physical', 'Can pour liquid from a bottle into a glass with some spilling',
    'Can pour liquid from a bottle into a glass with some spilling', 'Can pour liquid from a bottle into a glass with some spilling', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'physical'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'physical', 'Can make shapes from play clay using shape objects and molds independently or with minimal help',
    'Can make shapes from play clay using shape objects and molds independently or with minimal help', 'Can make shapes from play clay using shape objects and molds independently or with minimal help', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'physical'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'physical', 'Canjump off the ground a little into a specific area like a circle drawn on the ground',
    'Canjump off the ground a little into a specific area like a circle drawn on the ground', 'Canjump off the ground a little into a specific area like a circle drawn on the ground', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'physical'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'physical', 'Drawing skills have developed to a level where the baby can draw vertical and horizontal lines',
    'Drawing skills have developed to a level where the baby can draw vertical and horizontal lines', 'Drawing skills have developed to a level where the baby can draw vertical and horizontal lines', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'physical'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'physical', 'Can move and control the handle ofthe scooter or bicycle, paddling is developing as well',
    'Can move and control the handle ofthe scooter or bicycle, paddling is developing as well', 'Can move and control the handle ofthe scooter or bicycle, paddling is developing as well', NULL, 6, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'physical'
      AND display_order = 6
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'physical', 'Can mold the dough by rolling or punching but doesn''t make objects yet',
    'Can mold the dough by rolling or punching but doesn''t make objects yet', 'Can mold the dough by rolling or punching but doesn''t make objects yet', NULL, 7, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'physical'
      AND display_order = 7
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'physical', 'Can multiple large beads into a string',
    'Can multiple large beads into a string', 'Can multiple large beads into a string', NULL, 8, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'physical'
      AND display_order = 8
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'physical', 'Dances independently on favorite music but may lack understanding of beats Al^ Ima-t',
    'Dances independently on favorite music but may lack understanding of beats Al^ Ima-t', 'Dances independently on favorite music but may lack understanding of beats Al^ Ima-t', NULL, 9, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'physical'
      AND display_order = 9
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'physical', 'Pasting stickers using glue, maybe with little help',
    'Pasting stickers using glue, maybe with little help', 'Pasting stickers using glue, maybe with little help', NULL, 10, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'physical'
      AND display_order = 10
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'social_emotional', 'Loves to show things created by selfto family members and feels happy to praise',
    'Loves to show things created by selfto family members and feels happy to praise', 'Loves to show things created by selfto family members and feels happy to praise', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'social_emotional'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'social_emotional', 'Can on clothes like socks, shirt, pant; etc with some help',
    'Can on clothes like socks, shirt, pant; etc with some help', 'Can on clothes like socks, shirt, pant; etc with some help', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'social_emotional'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'social_emotional', 'Follows instructions around cleaning or organizing a place when an adult does it along',
    'Follows instructions around cleaning or organizing a place when an adult does it along', 'Follows instructions around cleaning or organizing a place when an adult does it along', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'social_emotional'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'social_emotional', 'Engages with same age baby for some time but only when an adult is nearby',
    'Engages with same age baby for some time but only when an adult is nearby', 'Engages with same age baby for some time but only when an adult is nearby', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'social_emotional'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'social_emotional', 'Requests or asks for permission when they want anything or do any activities',
    'Requests or asks for permission when they want anything or do any activities', 'Requests or asks for permission when they want anything or do any activities', NULL, 6, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'social_emotional'
      AND display_order = 6
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    27, 'social_emotional', 'Uses negative words for eg leave the phone no phone, don''t do it, etc',
    'Uses negative words for eg leave the phone no phone, don''t do it, etc', 'Uses negative words for eg leave the phone no phone, don''t do it, etc', NULL, 7, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 27
      AND milestone_type = 'social_emotional'
      AND display_order = 7
  );

END $$;
