-- Migration 030: Seed milestone definitions extracted from ui/babyG/milestones screenshots
-- Generated by scripts/extract-ui-milestones.py.

DO $$
BEGIN
  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'cognitive', 'Can identify and name 3-5 color of objects inside and outside the home',
    'Can identify and name 3-5 color of objects inside and outside the home', 'Can identify and name 3-5 color of objects inside and outside the home', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'cognitive'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'cognitive', 'Able to stack rings independently on the ring stacking toy in order; with no or little help',
    'Able to stack rings independently on the ring stacking toy in order; with no or little help', 'Able to stack rings independently on the ring stacking toy in order; with no or little help', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'cognitive'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'cognitive', 'Shows an understanding and imagination of places when you mention home, garden parking; office, clinic; shopping; etc',
    'Shows an understanding and imagination of places when you mention home, garden parking; office, clinic; shopping; etc', 'Shows an understanding and imagination of places when you mention home, garden parking; office, clinic; shopping; etc', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'cognitive'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'cognitive', 'Can identify primary color objects from a group of colored objects with some guidance',
    'Can identify primary color objects from a group of colored objects with some guidance', 'Can identify primary color objects from a group of colored objects with some guidance', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'cognitive'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'cognitive', 'Able to recognize an object by just listening to a sound (like says "phone'' when the phone rings)',
    'Able to recognize an object by just listening to a sound (like says "phone'' when the phone rings)', 'Able to recognize an object by just listening to a sound (like says "phone'' when the phone rings)', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'cognitive'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'communication', 'Can form phrases of 3 words to express thoughts or needs like Iwant curd, let''s go out, give me chocolate; etc',
    'Can form phrases of 3 words to express thoughts or needs like Iwant curd, let''s go out, give me chocolate; etc', 'Can form phrases of 3 words to express thoughts or needs like Iwant curd, let''s go out, give me chocolate; etc', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'communication'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'communication', 'Vocabulary has expanded to around 150-200 words with most ofthe things seen in everyday life can be recognized by the baby now',
    'Vocabulary has expanded to around 150-200 words with most ofthe things seen in everyday life can be recognized by the baby now', 'Vocabulary has expanded to around 150-200 words with most ofthe things seen in everyday life can be recognized by the baby now', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'communication'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'communication', 'Vocabulary of outdoor items is growing: Can name various objects seen outdoors like tree plant; parts ofa tree, path; road, sidewalk pole, signal, etc',
    'Vocabulary of outdoor items is growing: Can name various objects seen outdoors like tree plant; parts ofa tree, path; road, sidewalk pole, signal, etc', 'Vocabulary of outdoor items is growing: Can name various objects seen outdoors like tree plant; parts ofa tree, path; road, sidewalk pole, signal, etc', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'communication'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'communication', 'Can identify and name common actions like dancing; playing; jumping; running; driving etc',
    'Can identify and name common actions like dancing; playing; jumping; running; driving etc', 'Can identify and name common actions like dancing; playing; jumping; running; driving etc', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'communication'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'communication', 'Can name and identify 6-10 fruits when see pictures or real fruits',
    'Can name and identify 6-10 fruits when see pictures or real fruits', 'Can name and identify 6-10 fruits when see pictures or real fruits', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'communication'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'communication', 'Can identify and speak up to 5 alphabets',
    'Can identify and speak up to 5 alphabets', 'Can identify and speak up to 5 alphabets', NULL, 6, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'communication'
      AND display_order = 6
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'physical', 'Baby can dance by following few steps along with you; dance steps are forming now',
    'Baby can dance by following few steps along with you; dance steps are forming now', 'Baby can dance by following few steps along with you; dance steps are forming now', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'physical'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'physical', 'Able to turn the pages of a book one by one',
    'Able to turn the pages of a book one by one', 'Able to turn the pages of a book one by one', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'physical'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'physical', 'Can rolla ball towards a person and can stop a ball coming towards self',
    'Can rolla ball towards a person and can stop a ball coming towards self', 'Can rolla ball towards a person and can stop a ball coming towards self', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'physical'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'physical', 'Tries to take off shoes and down elastic pants with some help',
    'Tries to take off shoes and down elastic pants with some help', 'Tries to take off shoes and down elastic pants with some help', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'physical'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'physical', 'Gains good grip on spoon and fork and can eatthings withouit snilling much',
    'Gains good grip on spoon and fork and can eatthings withouit snilling much', 'Gains good grip on spoon and fork and can eatthings withouit snilling much', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'physical'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'physical', 'Able to press and roll modeling clay to shapes on them with little help & direction',
    'Able to press and roll modeling clay to shapes on them with little help & direction', 'Able to press and roll modeling clay to shapes on them with little help & direction', NULL, 6, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'physical'
      AND display_order = 6
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'physical', 'Can throw a ball over the head',
    'Can throw a ball over the head', 'Can throw a ball over the head', NULL, 7, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'physical'
      AND display_order = 7
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'social_emotional', 'Cooperates as a team member to perform tasks that can''tbe done alone',
    'Cooperates as a team member to perform tasks that can''tbe done alone', 'Cooperates as a team member to perform tasks that can''tbe done alone', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'social_emotional'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'social_emotional', 'Recognise self in old pictures and videos even from few months back, shows recall of events on longer time frame now',
    'Recognise self in old pictures and videos even from few months back, shows recall of events on longer time frame now', 'Recognise self in old pictures and videos even from few months back, shows recall of events on longer time frame now', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'social_emotional'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'social_emotional', 'Understands what it means to look good/ pretty/cute and likes to be praised for looks when experiment on selfwith new things',
    'Understands what it means to look good/ pretty/cute and likes to be praised for looks when experiment on selfwith new things', 'Understands what it means to look good/ pretty/cute and likes to be praised for looks when experiment on selfwith new things', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'social_emotional'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'social_emotional', 'Baby can brush when instructed from adult and follows the routine of morning and night to brush teeth',
    'Baby can brush when instructed from adult and follows the routine of morning and night to brush teeth', 'Baby can brush when instructed from adult and follows the routine of morning and night to brush teeth', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'social_emotional'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'social_emotional', 'Can name and identify 6-10 fruits when see pictures or real fruits',
    'Can name and identify 6-10 fruits when see pictures or real fruits', 'Can name and identify 6-10 fruits when see pictures or real fruits', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'social_emotional'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    24, 'social_emotional', 'Can identify self with their name and answer the question "What''s your name?"',
    'Can identify self with their name and answer the question "What''s your name?"', 'Can identify self with their name and answer the question "What''s your name?"', NULL, 6, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 24
      AND milestone_type = 'social_emotional'
      AND display_order = 6
  );

END $$;
