-- Migration 030: Seed milestone definitions extracted from ui/babyG/milestones screenshots
-- Generated by scripts/extract-ui-milestones.py.

DO $$
BEGIN
  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'cognitive', 'Understands the concept ofnarrow and wide in a comparative context',
    'Understands the concept ofnarrow and wide in a comparative context', 'Understands the concept ofnarrow and wide in a comparative context', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'cognitive'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'cognitive', 'Able to follow three-step instructions',
    'Able to follow three-step instructions', 'Able to follow three-step instructions', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'cognitive'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'cognitive', 'Understands various time references like morning; evening; in sometime; soon; later yesterday; tomorrow; etc',
    'Understands various time references like morning; evening; in sometime; soon; later yesterday; tomorrow; etc', 'Understands various time references like morning; evening; in sometime; soon; later yesterday; tomorrow; etc', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'cognitive'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'cognitive', 'Can explain past and present actions when you ask; like What are you drawing a Tree what did you make in morning - Monkey, etc But may not talk about the future',
    'Can explain past and present actions when you ask; like What are you drawing a Tree what did you make in morning - Monkey, etc But may not talk about the future', 'Can explain past and present actions when you ask; like What are you drawing a Tree what did you make in morning - Monkey, etc But may not talk about the future', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'cognitive'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'cognitive', 'Begins to explore volume measurement in daily activities (e.g. filling up a half cup of water when helping in the kitchen)',
    'Begins to explore volume measurement in daily activities (e.g. filling up a half cup of water when helping in the kitchen)', 'Begins to explore volume measurement in daily activities (e.g. filling up a half cup of water when helping in the kitchen)', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'cognitive'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'cognitive', 'Begins to develop a sense ofhumor; can laugh at self and others when funny accidents happen',
    'Begins to develop a sense ofhumor; can laugh at self and others when funny accidents happen', 'Begins to develop a sense ofhumor; can laugh at self and others when funny accidents happen', NULL, 6, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'cognitive'
      AND display_order = 6
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'cognitive', 'Names or points to tools used for different professions. For example scissors for cutting hair; hammer for a carpenter; tongs in the kitchen, etc',
    'Names or points to tools used for different professions. For example scissors for cutting hair; hammer for a carpenter; tongs in the kitchen, etc', 'Names or points to tools used for different professions. For example scissors for cutting hair; hammer for a carpenter; tongs in the kitchen, etc', NULL, 7, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'cognitive'
      AND display_order = 7
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'communication', 'To answer ''Why'' questions when prompted,not in detail though Like Why did you paint this? Why do you like this? etc',
    'to answer ''Why'' questions when prompted,not in detail though Like Why did you paint this? Why do you like this? etc', 'to answer ''Why'' questions when prompted,not in detail though Like Why did you paint this? Why do you like this? etc', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'communication'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'communication', 'Can explain the body state with sentence like ''I am hungry want a biscuit want to do peepee, etc',
    'Can explain the body state with sentence like ''I am hungry want a biscuit want to do peepee, etc', 'Can explain the body state with sentence like ''I am hungry want a biscuit want to do peepee, etc', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'communication'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'communication', 'Can narrate the experience about an event or activity of the by self with small sentences',
    'Can narrate the experience about an event or activity of the by self with small sentences', 'Can narrate the experience about an event or activity of the by self with small sentences', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'communication'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'communication', 'Understands and can answer when asked about belongings, like who''s pant; is it? who drives this car? who''s shoes are they',
    'Understands and can answer when asked about belongings, like who''s pant; is it? who drives this car? who''s shoes are they?', 'Understands and can answer when asked about belongings, like who''s pant; is it? who drives this car? who''s shoes are they?', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'communication'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'communication', 'Vocabulary has grown to around 600-1000 words',
    'Vocabulary has grown to around 600-1000 words', 'Vocabulary has grown to around 600-1000 words', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'communication'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'physical', 'Can fold a paper along a line with some precision and fold to multiple levels',
    'Can fold a paper along a line with some precision and fold to multiple levels', 'Can fold a paper along a line with some precision and fold to multiple levels', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'physical'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'physical', 'Tries to stand on one can maintain balance for few seconds',
    'Tries to stand on one can maintain balance for few seconds', 'Tries to stand on one can maintain balance for few seconds', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'physical'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'physical', 'Can fill colors in shapes with good accuracy and less overspill',
    'Can fill colors in shapes with good accuracy and less overspill', 'Can fill colors in shapes with good accuracy and less overspill', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'physical'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'physical', 'Can kick a moving ball while standing: Can also run and kick a stationary ball',
    'Can kick a moving ball while standing: Can also run and kick a stationary ball', 'Can kick a moving ball while standing: Can also run and kick a stationary ball', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'physical'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'physical', 'Drawing skills have developed to a level where baby can now make basic shapes roughly',
    'Drawing skills have developed to a level where baby can now make basic shapes roughly', 'Drawing skills have developed to a level where baby can now make basic shapes roughly', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'physical'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'physical', 'Able to jump ff the ground in a forward direction with both legs together and can widen the too',
    'Able to jump ff the ground in a forward direction with both legs together and can widen the too', 'Able to jump ff the ground in a forward direction with both legs together and can widen the too', NULL, 6, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'physical'
      AND display_order = 6
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'social_emotional', 'Can recognize the spelling of own name when only the name is written',
    'Can recognize the spelling of own name when only the name is written', 'Can recognize the spelling of own name when only the name is written', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'social_emotional'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'social_emotional', 'Knows what letter his/her name starts with',
    'Knows what letter his/her name starts with', 'Knows what letter his/her name starts with', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'social_emotional'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'social_emotional', 'Can differentiate her/his own name from a group of words',
    'Can differentiate her/his own name from a group of words', 'Can differentiate her/his own name from a group of words', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'social_emotional'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'social_emotional', 'Understands and can answer when asked about belongings, like who''s pant; is it? who drives this car? who''s shoes are they',
    'Understands and can answer when asked about belongings, like who''s pant; is it? who drives this car? who''s shoes are they?', 'Understands and can answer when asked about belongings, like who''s pant; is it? who drives this car? who''s shoes are they?', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'social_emotional'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    36, 'social_emotional', 'Understanding and imagination of places are good. Like home, garden; parking; shopping etc. Can tell why we go there and what we do at various places',
    'Understanding and imagination of places are good. Like home, garden; parking; shopping etc. Can tell why we go there and what we do at various places', 'Understanding and imagination of places are good. Like home, garden; parking; shopping etc. Can tell why we go there and what we do at various places', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 36
      AND milestone_type = 'social_emotional'
      AND display_order = 5
  );

END $$;
