-- Migration 030: Seed milestone definitions extracted from ui/babyG/milestones screenshots
-- Generated by scripts/extract-ui-milestones.py.

DO $$
BEGIN
  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    35, 'cognitive', 'Understands the concept of floating and sinking: Can identify objects which will sink or float from a familiar set of objects',
    'Understands the concept of floating and sinking: Can identify objects which will sink or float from a familiar set of objects', 'Understands the concept of floating and sinking: Can identify objects which will sink or float from a familiar set of objects', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 35
      AND milestone_type = 'cognitive'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    35, 'cognitive', 'Tries to draw familiar people in a very simple way: Like face, vertical and horizontal lines for body; etc',
    'Tries to draw familiar people in a very simple way: Like face, vertical and horizontal lines for body; etc', 'Tries to draw familiar people in a very simple way: Like face, vertical and horizontal lines for body; etc', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 35
      AND milestone_type = 'cognitive'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    35, 'cognitive', 'Understands and can give directions to others using words like up/down and right/ left',
    'Understands and can give directions to others using words like up/down and right/ left', 'Understands and can give directions to others using words like up/down and right/ left', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 35
      AND milestone_type = 'cognitive'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    35, 'cognitive', 'Can complete a new puzzle with 3 or 4 pieces independently',
    'Can complete a new puzzle with 3 or 4 pieces independently', 'Can complete a new puzzle with 3 or 4 pieces independently', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 35
      AND milestone_type = 'cognitive'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    35, 'cognitive', 'Show interest in science experiments when you show; Excitedly ask for it too sometimes',
    'Show interest in science experiments when you show; Excitedly ask for it too sometimes', 'Show interest in science experiments when you show; Excitedly ask for it too sometimes', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 35
      AND milestone_type = 'cognitive'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    35, 'cognitive', 'Attempts to solve problems by self perseverance is building to try for various solutions',
    'Attempts to solve problems by self perseverance is building to try for various solutions', 'Attempts to solve problems by self perseverance is building to try for various solutions', NULL, 6, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 35
      AND milestone_type = 'cognitive'
      AND display_order = 6
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    35, 'communication', 'Begins to use language for fantasies, jokes and teasing',
    'Begins to use language for fantasies, jokes and teasing', 'Begins to use language for fantasies, jokes and teasing', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 35
      AND milestone_type = 'communication'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    35, 'communication', 'Begins to exhibit social knowledge about festivals and holidays',
    'Begins to exhibit social knowledge about festivals and holidays', 'Begins to exhibit social knowledge about festivals and holidays', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 35
      AND milestone_type = 'communication'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    35, 'communication', 'Can converse with longer sentences of 4-5 words in a conversation style',
    'Can converse with longer sentences of 4-5 words in a conversation style', 'Can converse with longer sentences of 4-5 words in a conversation style', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 35
      AND milestone_type = 'communication'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    35, 'communication', 'Able to tell the name, age, gender; and birth date; at least 2 ofthese',
    'Able to tell the name, age, gender; and birth date; at least 2 ofthese', 'Able to tell the name, age, gender; and birth date; at least 2 ofthese', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 35
      AND milestone_type = 'communication'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    35, 'communication', 'Knows simple concepts and uses the words appropriately like big and small, in and out heavy and light; etc',
    'Knows simple concepts and uses the words appropriately like big and small, in and out heavy and light; etc', 'Knows simple concepts and uses the words appropriately like big and small, in and out heavy and light; etc', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 35
      AND milestone_type = 'communication'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    35, 'physical', 'Can draw simple shapes with rough precision like a circle, a line, a square; etc',
    'Can draw simple shapes with rough precision like a circle, a line, a square; etc', 'Can draw simple shapes with rough precision like a circle, a line, a square; etc', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 35
      AND milestone_type = 'physical'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    35, 'physical', 'Able to estimate and catches a bouncing ball most of the time',
    'Able to estimate and catches a bouncing ball most of the time', 'Able to estimate and catches a bouncing ball most of the time', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 35
      AND milestone_type = 'physical'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    35, 'physical', 'Able to ride and steer bicycle or scooter completely independently',
    'Able to ride and steer bicycle or scooter completely independently', 'Able to ride and steer bicycle or scooter completely independently', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 35
      AND milestone_type = 'physical'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    35, 'social_emotional', 'Understands, at a simple level, that feelings have causes. For example "The Teddy is sad because he lost his toy"',
    'Understands, at a simple level, that feelings have causes. For example "The Teddy is sad because he lost his toy"', 'Understands, at a simple level, that feelings have causes. For example "The Teddy is sad because he lost his toy"', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 35
      AND milestone_type = 'social_emotional'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    35, 'social_emotional', 'Imitates adults and friends in a fun way',
    'Imitates adults and friends in a fun way', 'Imitates adults and friends in a fun way', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 35
      AND milestone_type = 'social_emotional'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    35, 'social_emotional', 'Understands routine and may upset with change in routine',
    'Understands routine and may upset with change in routine', 'Understands routine and may upset with change in routine', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 35
      AND milestone_type = 'social_emotional'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    35, 'social_emotional', 'InAce+-rac V2'' ''ir^ 75a K ^ ''Al',
    'InAce+-rac V2'' ''ir^ 75a K ^ ''Al', 'InAce+-rac V2'' ''ir^ 75a K ^ ''Al', NULL, 9, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 35
      AND milestone_type = 'social_emotional'
      AND display_order = 9
  );

END $$;
