-- Migration 030: Seed milestone definitions extracted from ui/babyG/milestones screenshots
-- Generated by scripts/extract-ui-milestones.py.

DO $$
BEGIN
  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'cognitive', 'Understands object permanence: Knows that an object that is partially hidden is still available and can be reached out for',
    'Understands object permanence: Knows that an object that is partially hidden is still available and can be reached out for', 'Understands object permanence: Knows that an object that is partially hidden is still available and can be reached out for', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'cognitive'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'cognitive', 'Anticipation: Leans body from a vertical position in lap to look for anitem dropped from hand',
    'Anticipation: Leans body from a vertical position in lap to look for anitem dropped from hand', 'Anticipation: Leans body from a vertical position in lap to look for anitem dropped from hand', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'cognitive'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'cognitive', 'Attention span has increased. Engages in longer eye gazing, listens carefully to rhymes observes lip movements, etc',
    'Attention span has increased. Engages in longer eye gazing, listens carefully to rhymes observes lip movements, etc', 'Attention span has increased. Engages in longer eye gazing, listens carefully to rhymes observes lip movements, etc', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'cognitive'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'cognitive', 'When handed an object; takes an interest to explore the object by carefully looking at all sides and angles Vac Alc Almact',
    'When handed an object; takes an interest to explore the object by carefully looking at all sides and angles Vac Alc Almact', 'When handed an object; takes an interest to explore the object by carefully looking at all sides and angles Vac Alc Almact', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'cognitive'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'cognitive', 'Can understand and estimate distance, and acts differently when an object is near or far',
    'Can understand and estimate distance, and acts differently when an object is near or far', 'Can understand and estimate distance, and acts differently when an object is near or far', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'cognitive'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'cognitive', 'Bangs two objects together if given one in each hand to make a sound',
    'Bangs two objects together if given one in each hand to make a sound', 'Bangs two objects together if given one in each hand to make a sound', NULL, 6, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'cognitive'
      AND display_order = 6
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'cognitive', 'Begin to coordinate both hands together and holds things with them',
    'Begin to coordinate both hands together and holds things with them', 'Begin to coordinate both hands together and holds things with them', NULL, 8, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'cognitive'
      AND display_order = 8
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'communication', 'Makes two-letter sounds like ma, pa, da, ba etc: when prompted',
    'Makes two-letter sounds like ma, pa, da, ba etc: when prompted', 'Makes two-letter sounds like ma, pa, da, ba etc: when prompted', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'communication'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'communication', 'Expresses with different sounds for happiness, irritation; pain, fun time, etc',
    'Expresses with different sounds for happiness, irritation; pain, fun time, etc', 'Expresses with different sounds for happiness, irritation; pain, fun time, etc', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'communication'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'communication', 'Makes sound in response to the singing of a rhyme they like',
    'Makes sound in response to the singing of a rhyme they like', 'Makes sound in response to the singing of a rhyme they like', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'communication'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'communication', 'Can differentiate between various moods based on voice tone',
    'Can differentiate between various moods based on voice tone', 'Can differentiate between various moods based on voice tone', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'communication'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'communication', 'Able to differentiate multiple sounds and looks in the direction of new sounds',
    'Able to differentiate multiple sounds and looks in the direction of new sounds', 'Able to differentiate multiple sounds and looks in the direction of new sounds', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'communication'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'physical', 'Can stay in a sitting posture with the support of their own hands',
    'Can stay in a sitting posture with the support of their own hands', 'Can stay in a sitting posture with the support of their own hands', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'physical'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'physical', 'Able to roll over on both sides and go on a tummy-down position from a face-up position and vice versa',
    'Able to roll over on both sides and go on a tummy-down position from a face-up position and vice versa', 'Able to roll over on both sides and go on a tummy-down position from a face-up position and vice versa', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'physical'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'physical', 'Tries to come to a sitting position from a lying position on their own but needs a little support',
    'Tries to come to a sitting position from a lying position on their own but needs a little support', 'Tries to come to a sitting position from a lying position on their own but needs a little support', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'physical'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'physical', 'Extends body and tries to creep with arms to move the body to reach nearby objects',
    'Extends body and tries to creep with arms to move the body to reach nearby objects', 'Extends body and tries to creep with arms to move the body to reach nearby objects', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'physical'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'physical', 'Head control is very and stable, with no wobbling anymore',
    'Head control is very and stable, with no wobbling anymore', 'Head control is very and stable, with no wobbling anymore', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'physical'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'physical', 'When heldup on legs while holding from underarms; baby''s legs are able to take the bodyweight for a few seconds',
    'When heldup on legs while holding from underarms; baby''s legs are able to take the bodyweight for a few seconds', 'When heldup on legs while holding from underarms; baby''s legs are able to take the bodyweight for a few seconds', NULL, 6, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'physical'
      AND display_order = 6
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'physical', 'Reacts differently to hot and cold water',
    'Reacts differently to hot and cold water', 'Reacts differently to hot and cold water', NULL, 7, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'physical'
      AND display_order = 7
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'physical', 'Begin to coordinate both hands together and holds things with them',
    'Begin to coordinate both hands together and holds things with them', 'Begin to coordinate both hands together and holds things with them', NULL, 8, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'physical'
      AND display_order = 8
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'social_emotional', 'Prefers to go out and explore new surroundings, can be noted from baby''s ''demand moments'' inside home versus outside',
    'Prefers to go out and explore new surroundings, can be noted from baby''s ''demand moments'' inside home versus outside', 'Prefers to go out and explore new surroundings, can be noted from baby''s ''demand moments'' inside home versus outside', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'social_emotional'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'social_emotional', 'Understands when someone is calling their name and becomes attentive. Recognizes self with the name',
    'Understands when someone is calling their name and becomes attentive. Recognizes self with the name', 'Understands when someone is calling their name and becomes attentive. Recognizes self with the name', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'social_emotional'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'social_emotional', 'Interacts with their own mirror image by touching the image or making sounds',
    'Interacts with their own mirror image by touching the image or making sounds', 'Interacts with their own mirror image by touching the image or making sounds', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'social_emotional'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'social_emotional', 'Begins to recognize things like medicine playtime, bath time, etc; and protests when forced to doan unwanted thing',
    'Begins to recognize things like medicine playtime, bath time, etc; and protests when forced to doan unwanted thing', 'Begins to recognize things like medicine playtime, bath time, etc; and protests when forced to doan unwanted thing', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'social_emotional'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'social_emotional', 'Extends and shakes arms to fetch something they like Tries to grab facial features of family members',
    'Extends and shakes arms to fetch something they like Tries to grab facial features of family members', 'Extends and shakes arms to fetch something they like Tries to grab facial features of family members', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'social_emotional'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    6, 'social_emotional', 'To a varying degree, responds differently towards a family member than towards a stranger',
    'To a varying degree, responds differently towards a family member than towards a stranger', 'To a varying degree, responds differently towards a family member than towards a stranger', NULL, 6, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 6
      AND milestone_type = 'social_emotional'
      AND display_order = 6
  );

END $$;
