-- Migration 030: Seed milestone definitions extracted from ui/babyG/milestones screenshots
-- Generated by scripts/extract-ui-milestones.py.

DO $$
BEGIN
  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'cognitive', 'Object permanence improved as the baby can out partially hidden objects',
    'Object permanence improved as the baby can out partially hidden objects', 'Object permanence improved as the baby can out partially hidden objects', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'cognitive'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'cognitive', 'Understands cause and effect by anticipating the effect: Like when the doorbell rings, baby anticipates the arrival of someone or looks at the fan when they see the switch being turned on/off',
    'Understands cause and effect by anticipating the effect: Like when the doorbell rings, baby anticipates the arrival of someone or looks at the fan when they see the switch being turned on/off', 'Understands cause and effect by anticipating the effect: Like when the doorbell rings, baby anticipates the arrival of someone or looks at the fan when they see the switch being turned on/off', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'cognitive'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'cognitive', 'Remembers directions in the house and crawls back to a place when picked up and placed somewhere else',
    'Remembers directions in the house and crawls back to a place when picked up and placed somewhere else', 'Remembers directions in the house and crawls back to a place when picked up and placed somewhere else', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'cognitive'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'cognitive', 'Tries to crawl faster when they realize you are following behind to catch them; shows an understanding of speed and distance',
    'Tries to crawl faster when they realize you are following behind to catch them; shows an understanding of speed and distance', 'Tries to crawl faster when they realize you are following behind to catch them; shows an understanding of speed and distance', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'cognitive'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'cognitive', 'Able to play peek-a-boo and participates by removing hands or objects from parent''s face',
    'Able to play peek-a-boo and participates by removing hands or objects from parent''s face', 'Able to play peek-a-boo and participates by removing hands or objects from parent''s face', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'cognitive'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'communication', 'Tries to imitate sound made by the objects like drums, toys, etc as the baby explore them',
    'Tries to imitate sound made by the objects like drums, toys, etc as the baby explore them', 'Tries to imitate sound made by the objects like drums, toys, etc as the baby explore them', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'communication'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'communication', 'Starts to understand that ''No'' is a prohibitive word and hesitates to proceed when you say',
    'Starts to understand that ''No'' is a prohibitive word and hesitates to proceed when you say', 'Starts to understand that ''No'' is a prohibitive word and hesitates to proceed when you say', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'communication'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'communication', 'Produces sounds deliberately to express happiness, cooperation, disapproval, and anger',
    'Produces sounds deliberately to express happiness, cooperation, disapproval, and anger', 'Produces sounds deliberately to express happiness, cooperation, disapproval, and anger', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'communication'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'communication', 'Able to express a preference for selected foods, textures, toys, play, and people through body and facial actions',
    'Able to express a preference for selected foods, textures, toys, play, and people through body and facial actions', 'Able to express a preference for selected foods, textures, toys, play, and people through body and facial actions', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'communication'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'communication', 'Able to use long strings of sounds (blabber) to communicate about something in sight or something pointed by hand',
    'Able to use long strings of sounds (blabber) to communicate about something in sight or something pointed by hand', 'Able to use long strings of sounds (blabber) to communicate about something in sight or something pointed by hand', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'communication'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'communication', 'Starts speaking single syllable words like ma ta, etc No clear communication but feels like conversation sometimes',
    'Starts speaking single syllable words like ma ta, etc No clear communication but feels like conversation sometimes', 'Starts speaking single syllable words like ma ta, etc No clear communication but feels like conversation sometimes', NULL, 6, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'communication'
      AND display_order = 6
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'physical', 'Can come to a crawling position from sitting position and go back to sitting position with good balance',
    'Can come to a crawling position from sitting position and go back to sitting position with good balance', 'Can come to a crawling position from sitting position and go back to sitting position with good balance', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'physical'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'physical', 'Starts to clap hands when prompted by an adult',
    'Starts to clap hands when prompted by an adult', 'Starts to clap hands when prompted by an adult', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'physical'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'physical', 'Parachute Reflex fully developed where baby puts their hands forward to protect from falling when leaned forward in a falling action',
    'Parachute Reflex fully developed where baby puts their hands forward to protect from falling when leaned forward in a falling action', 'Parachute Reflex fully developed where baby puts their hands forward to protect from falling when leaned forward in a falling action', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'physical'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'physical', 'Is a crawling expert: Crawls fast and long distances and avoids obstructions by changing direction',
    'Is a crawling expert: Crawls fast and long distances and avoids obstructions by changing direction', 'Is a crawling expert: Crawls fast and long distances and avoids obstructions by changing direction', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'physical'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'physical', 'Can come to a sitting position from sleeping position',
    'Can come to a sitting position from sleeping position', 'Can come to a sitting position from sleeping position', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'physical'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'physical', 'Tries to stand up by holding objects and can maintain standing position with the support of surrounding objects',
    'Tries to stand up by holding objects and can maintain standing position with the support of surrounding objects', 'Tries to stand up by holding objects and can maintain standing position with the support of surrounding objects', NULL, 6, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'physical'
      AND display_order = 6
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'physical', 'Tries to stand on knees by raising both hands from crawling position',
    'Tries to stand on knees by raising both hands from crawling position', 'Tries to stand on knees by raising both hands from crawling position', NULL, 7, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'physical'
      AND display_order = 7
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'social_emotional', 'Starting to understand the meaning of ''No'' and looks at you before doing prohibited things',
    'Starting to understand the meaning of ''No'' and looks at you before doing prohibited things', 'Starting to understand the meaning of ''No'' and looks at you before doing prohibited things', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'social_emotional'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'social_emotional', 'Seeks appreciation by repeating actions or sounds which gets applause',
    'Seeks appreciation by repeating actions or sounds which gets applause', 'Seeks appreciation by repeating actions or sounds which gets applause', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'social_emotional'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'social_emotional', 'Becomes more comfortable with louder and crowded surroundings',
    'Becomes more comfortable with louder and crowded surroundings', 'Becomes more comfortable with louder and crowded surroundings', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'social_emotional'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'social_emotional', 'Starts to feed self by picking things and taking them into the mouth',
    'Starts to feed self by picking things and taking them into the mouth', 'Starts to feed self by picking things and taking them into the mouth', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'social_emotional'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    8, 'social_emotional', 'Starts to play alone for sometime with toys',
    'Starts to play alone for sometime with toys', 'Starts to play alone for sometime with toys', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 8
      AND milestone_type = 'social_emotional'
      AND display_order = 5
  );

END $$;
