-- Migration 030: Seed milestone definitions extracted from ui/babyG/milestones screenshots
-- Generated by scripts/extract-ui-milestones.py.

DO $$
BEGIN
  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'cognitive', 'Able to locate a hidden sound object/source by tracking the sound to the source',
    'Able to locate a hidden sound object/source by tracking the sound to the source', 'Able to locate a hidden sound object/source by tracking the sound to the source', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'cognitive'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'cognitive', 'Can go around obstacles to find hidden objects behind the obstacles',
    'Can go around obstacles to find hidden objects behind the obstacles', 'Can go around obstacles to find hidden objects behind the obstacles', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'cognitive'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'cognitive', 'Observes processes curiously and can repeat 1-2 steps of the process',
    'Observes processes curiously and can repeat 1-2 steps of the process', 'Observes processes curiously and can repeat 1-2 steps of the process', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'cognitive'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'cognitive', 'Takes interest in pictures and figures in books',
    'Takes interest in pictures and figures in books', 'Takes interest in pictures and figures in books', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'cognitive'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'communication', 'Becomes more comfortable to point at objects with hand when asked to point',
    'Becomes more comfortable to point at objects with hand when asked to point', 'Becomes more comfortable to point at objects with hand when asked to point', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'communication'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'communication', 'Uses hands or fingers to point at things that they needs or are interested in',
    'Uses hands or fingers to point at things that they needs or are interested in', 'Uses hands or fingers to point at things that they needs or are interested in', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'communication'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'communication', 'Responds to the instruction of "No" by stopping the action. Also, move head sideways to say "No" when don''t want to eat or do something',
    'Responds to the instruction of "No" by stopping the action. Also, move head sideways to say "No" when don''t want to eat or do something', 'Responds to the instruction of "No" by stopping the action. Also, move head sideways to say "No" when don''t want to eat or do something', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'communication'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'communication', 'Can imitate facial expressions like opening the mouth, tongue out; etc',
    'Can imitate facial expressions like opening the mouth, tongue out; etc', 'Can imitate facial expressions like opening the mouth, tongue out; etc', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'communication'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'communication', 'Tries to imitate simple sounds like Mama, Oo Bubu; Ho, Mum Mum; etc',
    'Tries to imitate simple sounds like Mama, Oo Bubu; Ho, Mum Mum; etc', 'Tries to imitate simple sounds like Mama, Oo Bubu; Ho, Mum Mum; etc', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'communication'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'communication', 'Blabbers back at the phone when they hear a phone conversation',
    'Blabbers back at the phone when they hear a phone conversation', 'Blabbers back at the phone when they hear a phone conversation', NULL, 6, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'communication'
      AND display_order = 6
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'communication', 'Pushes back with hands when do not want to be moved or disturbed',
    'Pushes back with hands when do not want to be moved or disturbed', 'Pushes back with hands when do not want to be moved or disturbed', NULL, 7, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'communication'
      AND display_order = 7
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'physical', 'Aklc++urr n #tirla Kacc nfhcarahaclc',
    'Aklc++urr n #tirla Kacc nfhcarahaclc', 'Aklc++urr n #tirla Kacc nfhcarahaclc', NULL, 0, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'physical'
      AND display_order = 0
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'physical', 'Can sit down from a standing position without support',
    'Can sit down from a standing position without support', 'Can sit down from a standing position without support', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'physical'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'physical', 'Able to pick and drop tiny objects into a box',
    'Able to pick and drop tiny objects into a box', 'Able to pick and drop tiny objects into a box', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'physical'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'physical', 'Baby can sit on a chair and come to a standing position by holding a supporting object or hand',
    'Baby can sit on a chair and come to a standing position by holding a supporting object or hand', 'Baby can sit on a chair and come to a standing position by holding a supporting object or hand', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'physical'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'physical', 'Starts to take walking steps while holding hands',
    'Starts to take walking steps while holding hands', 'Starts to take walking steps while holding hands', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'physical'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'physical', 'Baby can crawl down a single step without support',
    'Baby can crawl down a single step without support', 'Baby can crawl down a single step without support', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'physical'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'physical', 'Can take apart pieces of toys like lego blocks from stacking games, etc',
    'Can take apart pieces of toys like lego blocks from stacking games, etc', 'Can take apart pieces of toys like lego blocks from stacking games, etc', NULL, 6, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'physical'
      AND display_order = 6
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'physical', 'Finger dexterity has improved and baby can hold a container with one hand and take out small items with another hand',
    'Finger dexterity has improved and baby can hold a container with one hand and take out small items with another hand', 'Finger dexterity has improved and baby can hold a container with one hand and take out small items with another hand', NULL, 7, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'physical'
      AND display_order = 7
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'physical', 'Able to stand up against a wall with the support of a wall',
    'Able to stand up against a wall with the support of a wall', 'Able to stand up against a wall with the support of a wall', NULL, 8, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'physical'
      AND display_order = 8
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'physical', 'Able to turn multiple pages of board books',
    'Able to turn multiple pages of board books', 'Able to turn multiple pages of board books', NULL, 9, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'physical'
      AND display_order = 9
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'social_emotional', 'Tries to gel into the social mood by being happy when everyone is happy and laughing',
    'Tries to gel into the social mood by being happy when everyone is happy and laughing', 'Tries to gel into the social mood by being happy when everyone is happy and laughing', NULL, 1, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'social_emotional'
      AND display_order = 1
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'social_emotional', 'Starts to recognize self in recent videos Vac Nlo Almoct',
    'Starts to recognize self in recent videos Vac Nlo Almoct', 'Starts to recognize self in recent videos Vac Nlo Almoct', NULL, 2, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'social_emotional'
      AND display_order = 2
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'social_emotional', 'Understands simple play and repeats the play once shown, like touching the head, tapping nose, etc',
    'Understands simple play and repeats the play once shown, like touching the head, tapping nose, etc', 'Understands simple play and repeats the play once shown, like touching the head, tapping nose, etc', NULL, 3, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'social_emotional'
      AND display_order = 3
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'social_emotional', 'Understands the usage of everyday objects like a spoon, comb; phone; etc',
    'Understands the usage of everyday objects like a spoon, comb; phone; etc', 'Understands the usage of everyday objects like a spoon, comb; phone; etc', NULL, 4, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'social_emotional'
      AND display_order = 4
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'social_emotional', 'Able to repeat sounds or actions which draw people''s attention',
    'Able to repeat sounds or actions which draw people''s attention', 'Able to repeat sounds or actions which draw people''s attention', NULL, 5, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'social_emotional'
      AND display_order = 5
  );

  INSERT INTO milestone_definitions
    (month, milestone_type, title, description, question, related_activity, display_order, doctor_verified)
  SELECT
    10, 'social_emotional', 'Pushes back with hands when do not want to be moved or disturbed',
    'Pushes back with hands when do not want to be moved or disturbed', 'Pushes back with hands when do not want to be moved or disturbed', NULL, 7, false
  WHERE NOT EXISTS (
    SELECT 1 FROM milestone_definitions
    WHERE month = 10
      AND milestone_type = 'social_emotional'
      AND display_order = 7
  );

END $$;
