syntax = "proto3";
package bombio.battle;

import "common.proto";

message PlayerInput {
  uint32 sequence    = 1;
  bombio.Direction move_dir    = 2;
  bool   place_bomb  = 3;
  uint32 ability_slot = 4;
  uint32 character_id = 5;
}

message GameState {
  uint32 frame     = 1;
  uint32 timestamp = 2;
  repeated PlayerState    players          = 3;
  repeated BombState      bombs            = 4;
  repeated ExplosionEvent explosions       = 5;
  repeated TerrainUpdate  terrain_updates  = 6;
}

message PlayerState {
  uint32 player_id        = 1;
  uint32 character_id     = 2;
  bombio.Vector2 position = 3;
  bombio.Direction facing = 4;
  uint32 hp               = 5;
  uint32 max_hp           = 6;
  uint32 bombs_available  = 7;
  uint32 bombs_max        = 8;
  uint32 blast_radius     = 9;
  repeated AbilityState abilities = 10;
}

message BombState {
  uint32 bomb_id         = 1;
  uint32 owner_player_id = 2;
  bombio.Vector2 position = 3;
  uint32 fuse_ticks      = 4;
  uint32 blast_radius    = 5;
}

message ExplosionEvent {
  uint32 bomb_id                       = 1;
  repeated bombio.Vector2 affected_cells = 2;
  repeated uint32 hit_players          = 3;
}

message TerrainUpdate {
  bombio.Vector2 position      = 1;
  bombio.TerrainType new_type  = 2;
}

message AbilityState {
  uint32 ability_id          = 1;
  uint32 cooldown_remaining  = 2;
  bool   is_ready            = 3;
}
