syntax = "proto3";
package bombio.match;

enum RoomStatus {
  WAITING  = 0;
  STARTING = 1;
  IN_GAME  = 2;
  FINISHED = 3;
}

message CreateRoomRequest {
  uint32 player_id  = 1;
  string map_id     = 2;
  uint32 max_players = 3;
}

message JoinRoomRequest {
  uint32 player_id = 1;
  string room_id   = 2;
}

message RoomInfo {
  string      room_id       = 1;
  RoomStatus  status        = 2;
  repeated uint32 player_ids = 3;
  uint32      max_players   = 4;
  string      map_id        = 5;
  string      battle_server_host = 6;
  uint32      battle_server_port = 7;
}

message LobbyState {
  repeated RoomInfo rooms = 1;
}
