import { ResourceManager } from "@/components/ResourceManager";

export default function FoodsPage() {
  return (
    <ResourceManager
      title="Foods"
      description="Inspect the per-100g food dictionary: classification, nutrition, vitamins, pairings, timing, and caution notes."
      endpoint="/foods"
      searchPlaceholder="Search foods, Korean names, Chinese names, groups, classes, tags"
      columns={[
        { key: "imageUrl", label: "Image", kind: "image" },
        { key: "name", label: "Korean Name" },
        { key: "chineseName", label: "Chinese Name" },
        { key: "category", label: "Category" },
        { key: "foodSubgroup", label: "Class" },
        { key: "calories", label: "Kcal/100g" },
        { key: "macros.protein", label: "Protein g" },
        { key: "macros.fat", label: "Fat g" },
        { key: "macros.carbs", label: "Carbs g" },
        { key: "macros.fiber", label: "Fiber g" },
        { key: "sugar", label: "Sugar g" },
        { key: "transFat", label: "Trans g" },
        { key: "unsaturatedFat", label: "Unsat g" },
        { key: "minerals.sodium", label: "Sodium mg" },
        { key: "vitamins.vitaminC", label: "Vit C mg" },
        { key: "vitamins.vitaminD", label: "Vit D ug" },
        { key: "dailyValuePercent.protein", label: "%DV Protein" },
        { key: "oiliness", label: "Oiliness" },
        { key: "allergens", label: "Allergens" },
        { key: "dietUseCases", label: "Diet Uses" },
        { key: "koreanCautions", label: "Caution" },
        { key: "bestTimeToEat", label: "Best Time" },
        { key: "doctor_verified", label: "Doctor Verified", kind: "boolean" }
      ]}
      fields={[
        { name: "name", label: "Korean Display Name", type: "text", required: true },
        { name: "koreanName", label: "Korean Name", type: "text" },
        { name: "chineseName", label: "Chinese Source Name", type: "text" },
        { name: "brand", label: "Brand", type: "text" },
        { name: "category", label: "Category", type: "text", required: true },
        { name: "foodGroup", label: "Food Group", type: "text" },
        { name: "foodSubgroup", label: "Food Subgroup", type: "text" },
        { name: "servingSize", label: "Serving Size", type: "text", required: true },
        { name: "calories", label: "Calories per 100g", type: "number", required: true },
        { name: "macros.protein", label: "Protein g / 100g", type: "number" },
        { name: "macros.fat", label: "Fat g / 100g", type: "number" },
        { name: "macros.carbs", label: "Carbs g / 100g", type: "number" },
        { name: "macros.fiber", label: "Fiber g / 100g", type: "number" },
        { name: "saturatedFat", label: "Saturated Fat g / 100g", type: "number" },
        { name: "transFat", label: "Trans Fat g / 100g", type: "number" },
        { name: "unsaturatedFat", label: "Unsaturated Fat g / 100g", type: "number" },
        { name: "omega3", label: "Omega-3 g / 100g", type: "number" },
        { name: "omega6", label: "Omega-6 g / 100g", type: "number" },
        { name: "cholesterolMg", label: "Cholesterol mg / 100g", type: "number" },
        { name: "sugar", label: "Sugar g / 100g", type: "number" },
        { name: "glycemicIndex", label: "Glycemic Index", type: "number" },
        { name: "oiliness", label: "Oiliness", type: "select", options: ["낮음", "보통", "높음", "매우 높음"] },
        { name: "oilinessScore", label: "Oiliness Score 0-5", type: "number" },
        { name: "vitamins.vitaminA", label: "Vitamin A ug RAE / 100g", type: "number" },
        { name: "vitamins.vitaminB1", label: "Vitamin B1 mg / 100g", type: "number" },
        { name: "vitamins.vitaminB2", label: "Vitamin B2 mg / 100g", type: "number" },
        { name: "vitamins.vitaminB3", label: "Vitamin B3 mg / 100g", type: "number" },
        { name: "vitamins.vitaminB6", label: "Vitamin B6 mg / 100g", type: "number" },
        { name: "vitamins.vitaminB12", label: "Vitamin B12 ug / 100g", type: "number" },
        { name: "vitamins.vitaminC", label: "Vitamin C mg / 100g", type: "number" },
        { name: "vitamins.vitaminD", label: "Vitamin D ug / 100g", type: "number" },
        { name: "vitamins.vitaminE", label: "Vitamin E mg / 100g", type: "number" },
        { name: "vitamins.vitaminK", label: "Vitamin K ug / 100g", type: "number" },
        { name: "vitamins.folate", label: "Folate ug / 100g", type: "number" },
        { name: "minerals.calcium", label: "Calcium mg / 100g", type: "number" },
        { name: "minerals.iron", label: "Iron mg / 100g", type: "number" },
        { name: "minerals.magnesium", label: "Magnesium mg / 100g", type: "number" },
        { name: "minerals.potassium", label: "Potassium mg / 100g", type: "number" },
        { name: "minerals.sodium", label: "Sodium mg / 100g", type: "number" },
        { name: "minerals.zinc", label: "Zinc mg / 100g", type: "number" },
        { name: "bestTimeToEat", label: "Best Time To Eat", type: "tags" },
        { name: "goodPairings", label: "Good Pairings", type: "tags" },
        { name: "avoidPairings", label: "Avoid Pairings", type: "tags" },
        { name: "cautionGroups", label: "Caution Groups", type: "tags" },
        { name: "koreanCautions", label: "Korean Cautions", type: "textarea" },
        { name: "cautions", label: "Chinese Cautions", type: "textarea" },
        { name: "benefits", label: "Benefits", type: "textarea" },
        { name: "allergens", label: "Allergens", type: "tags" },
        { name: "ingredients", label: "Ingredients", type: "tags" },
        { name: "additives", label: "Additives", type: "tags" },
        { name: "dietUseCases", label: "Diet Use Cases", type: "tags" },
        { name: "dietUseNote", label: "Diet Use Note", type: "textarea" },
        { name: "dailyValuePercent.calories", label: "%DV Calories", type: "number" },
        { name: "dailyValuePercent.protein", label: "%DV Protein", type: "number" },
        { name: "dailyValuePercent.carbs", label: "%DV Carbs", type: "number" },
        { name: "dailyValuePercent.fat", label: "%DV Fat", type: "number" },
        { name: "dailyValuePercent.saturatedFat", label: "%DV Saturated Fat", type: "number" },
        { name: "dailyValuePercent.fiber", label: "%DV Fiber", type: "number" },
        { name: "dailyValuePercent.sugar", label: "%DV Sugar", type: "number" },
        { name: "dailyValuePercent.sodium", label: "%DV Sodium", type: "number" },
        { name: "dailyValuePercent.cholesterol", label: "%DV Cholesterol", type: "number" },
        { name: "dailyValuePercent.calcium", label: "%DV Calcium", type: "number" },
        { name: "dailyValuePercent.iron", label: "%DV Iron", type: "number" },
        { name: "dailyValuePercent.magnesium", label: "%DV Magnesium", type: "number" },
        { name: "dailyValuePercent.potassium", label: "%DV Potassium", type: "number" },
        { name: "dailyValuePercent.zinc", label: "%DV Zinc", type: "number" },
        { name: "dailyValuePercent.vitaminA", label: "%DV Vitamin A", type: "number" },
        { name: "dailyValuePercent.vitaminB1", label: "%DV Vitamin B1", type: "number" },
        { name: "dailyValuePercent.vitaminB2", label: "%DV Vitamin B2", type: "number" },
        { name: "dailyValuePercent.vitaminB3", label: "%DV Vitamin B3", type: "number" },
        { name: "dailyValuePercent.vitaminB6", label: "%DV Vitamin B6", type: "number" },
        { name: "dailyValuePercent.vitaminB12", label: "%DV Vitamin B12", type: "number" },
        { name: "dailyValuePercent.vitaminC", label: "%DV Vitamin C", type: "number" },
        { name: "dailyValuePercent.vitaminD", label: "%DV Vitamin D", type: "number" },
        { name: "dailyValuePercent.vitaminE", label: "%DV Vitamin E", type: "number" },
        { name: "dailyValuePercent.vitaminK", label: "%DV Vitamin K", type: "number" },
        { name: "dailyValuePercent.folate", label: "%DV Folate", type: "number" },
        { name: "dataSource", label: "Data Source", type: "text" },
        { name: "sourceNote", label: "Source Note", type: "textarea" },
        { name: "tags", label: "Tags", type: "tags" },
        { name: "barcode", label: "Barcode", type: "text" },
        { name: "imageUrl", label: "Image URL", type: "text" },
        { name: "imageSourceUrl", label: "Image Source URL", type: "text" },
        { name: "imagePageUrl", label: "Image Page URL", type: "text" },
        { name: "imageSource", label: "Image Source", type: "text" },
        { name: "imageLicense", label: "Image License", type: "text" },
        { name: "imageStatus", label: "Image Status", type: "select", options: ["missing", "downloaded", "download_failed", "needs_real_download"] },
        { name: "icon", label: "Icon", type: "text" },
        { name: "doctor_verified", label: "Doctor Verified", type: "boolean" }
      ]}
    />
  );
}
