"""Model Settings Management Module — YAML Read the file and create a settings object.

【Beginner's Guide】
  This file contains the entire program "settings board" is.
  `config/model_config.yaml` Read all numbers from the file
  Python Converts it to an object.

  Settings Structure:
    FullConfig
      ├── ModelConfig    — Neural network structure setup (number of floors, dimension etc.)
      ├── TrainConfig    — training settings (learning rate, number of repetitions, etc.)
      ├── TokenizerConfig — Tokenizer settings
      ├── DataConfig     — Data path settings
      └── InferenceConfig — Post creation settings

  How to use:
    from src.model.config import load_config
    cfg = load_config("config/model_config.yaml")
    print(cfg.model.n_layer)  # → 8
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml


@dataclass
class ModelConfig:
    """Neural network structure setup.

    【Beginner's Guide】
      The numbers here are from Transformer. "body size" decide.
      The larger the number, the bigger the model and the more you can learn.,
      More epiphanic memories(VRAM)Wow I need training time.
    """

    # Transformer Block(floor)number of
    # Default 8: Refined the relationships between letters 8 times
    # More complex patterns can be learned, but increases manifest memory consumption.
    n_layer: int = 8

    # head of attention mechanism(Head) number
    # Default 8: 8Analyzing relationships from different perspectives simultaneously
    # n_embd go n_head must be divided into (512 ÷ 8 = 64)
    n_head: int = 8

    # number of embedding dimensions (model "width")
    # Default 512: Each letter is expressed as a vector of 512 numbers.
    # The larger the size, the higher the expressive power, but the consumption of manifest memory also increases.
    n_embd: int = 512

    # Number of internal dimensions of the forwarding network
    # Default 2048: n_embd × 4 = 512 × 4
    # The transmission network processes knowledge in this large space and compresses it back to 512.
    ffn_dim: int = 2048

    # maximum context length (Maximum number of characters that can be processed at one time)
    # Default 1024: 1024You can see the context of every letter at once
    # GPU The larger the manifest memory allows, the better.
    block_size: int = 1024

    # vocabulary size (Maximum number of words generated by the tokenizer + 1)
    # Default 16384: 16 Korean words and morphemes,384Divide by unit
    # When training meta.json overwritten by the actual vocabulary size in
    vocab_size: int = 16384

    # dropout rate (Proportion of neurons randomly switched off during training)
    # Default 0.1: 10%Prevent overfitting by randomly disconnecting
    # Automatically becomes 0 during inference
    dropout: float = 0.1

    # bias(bias) Used or not
    # default False: Works well without bias and allows reducing number of parameters
    bias: bool = False

    # Whether weights are shared or not (Input Embedding ↔ output projection)
    # default True: Reduces the number of parameters by about 8 million by sharing the same matrix
    tie_weights: bool = True

    def num_params_estimate(self) -> int:
        """Returns an estimate of the total number of parameters.

        weight sharing(tie_weights)Calculated taking into account.
        May differ slightly from actual value (LayerNorm Excluding small scale, etc.).
        """
        # Token Embedding: vocab_size × n_embd
        emb = self.vocab_size * self.n_embd
        # Location Embedding: block_size × n_embd
        pos = self.block_size * self.n_embd
        # Parameters per block:
        #   attention mechanism: QKV(3×n_embd×n_embd) + output projection(n_embd×n_embd) = 4×n_embd²
        #   transmission network: expansion(n_embd×ffn_dim) + zoom out(ffn_dim×n_embd) = 2×n_embd×ffn_dim
        per_block = (
            4 * self.n_embd * self.n_embd      # attention mechanism (QKV + output)
            + 2 * self.n_embd * self.ffn_dim   # transmission network (expansion + zoom out)
        )
        blocks = per_block * self.n_layer  # n_layerdog block
        # LM head: 0 when sharing weight, When not shared vocab_size × n_embd
        head = 0 if self.tie_weights else self.vocab_size * self.n_embd
        return emb + pos + blocks + head


@dataclass
class TrainConfig:
    """Training Course Settings.

    【Beginner's Guide】
      These settings "how long, how to train" decide.
    """

    # Folder to store checkpoints and logs
    out_dir: str = "checkpoints"

    # Number of documents processed at one time (bundle size)
    # Default 16: 16Process multiple documents simultaneously → Slope average is more stable
    # The larger the manifest memory setting is, the higher the training stability will be.
    batch_size: int = 16

    # Gradient cumulative steps
    # Actual bundle size = batch_size × grad_accum_steps = 16 × 4 = 64
    # How to increase actual bundle size when manifest memory is insufficient
    grad_accum_steps: int = 4

    # highest learning rate (peak learning rate)
    # AdamW How much the optimizer will adjust the weights at a time
    # If it's too big, it diverges., Too small and learning is slow.
    learning_rate: float = 3.0e-4

    # lowest learning rate (Minimum value of cosine attenuation)
    # max_steps As you get closer to the end, the learning rate decreases to this value.
    min_lr: float = 3.0e-5

    # Number of warm-up steps
    # The first 100 steps set the learning rate from 0 to peakLinearly up to
    # Prevent unstable training in the beginning
    warmup_steps: int = 100

    # Total number of training steps
    # Default 5000: 5,000Calculate the slope and adjust the weights
    max_steps: int = 5000

    # weighted attenuation coefficient (Avoid overfitting)
    # A regularization term that prevents the weights from becoming too large.
    weight_decay: float = 0.1

    # AdamW beta 1: moving average coefficient of slope (short term memory)
    beta1: float = 0.9

    # AdamW beta 2: Moving average coefficient of slope squared (long term memory)
    beta2: float = 0.95

    # Gradient Crop Threshold
    # If the norm of the slope exceeds this value, truncate. → Prevent explosive tilt
    grad_clip: float = 1.0

    # Verification and checkpoint storage interval (number of steps)
    # 250Calculate verification loss at each step and store checkpoints
    eval_interval: int = 250

    # Number of bundles used during verification
    # 50Estimating validation loss with the average loss of a bunch of dogs
    eval_iters: int = 50

    # Training log output interval (number of steps)
    # 10Output loss and learning rate at each step
    log_interval: int = 10

    # Post creation example output interval (number of steps)
    # 500Create a short article with the current model at each step to check progress
    sample_interval: int = 500

    # Number of recent checkpoints to keep (Only without tags)
    # _best, _final Always keep things tagged
    ckpt_keep_last: int = 3

    # Floating-point format to use for training
    # "bfloat16": RTX 30xx Fast and stable above
    # "fp16": sphere GPU alternative
    # "float32": Slowest but safest
    dtype: str = "bfloat16"

    # torch.compile Used or not
    # TrueIt is about 15% It gets faster, but, WindowsLimited support in
    # default False: Windows 11 Disable safely in your environment
    compile: bool = False


@dataclass
class TokenizerConfig:
    """Tokenizer training setup.

    【Beginner's Guide】
      Tokenizer is a tool that converts Korean characters into integer numbers..
      SentencePiece BPE use a method.
      BPE: A method of grouping frequently occurring letter combinations into one unit.
    """

    # vocabulary size: How many units should the Korean language be divided into?
    # Automatically decreases when there is less data (train_tokenizer.py Note)
    vocab_size: int = 16384

    # Tokenizer model types
    # "bpe": Byte Pair Encoding — Method used in the current program
    model_type: str = "bpe"

    # Letter inclusion ratio
    # 0.9995: 99 of the letters in the entire corpus.95% Set to be included in vocabulary
    character_coverage: float = 0.9995

    # storage path prefix
    # After training dprk_sp.model and dprk_sp.vocab File created
    output_prefix: str = "tokenizer/dprk_sp"


@dataclass
class DataConfig:
    """Data path settings.

    【Beginner's Guide】
      Set the path for original data and preprocessed data..
    """

    # Original Materials Folder (text, JSON, PDF etc.)
    raw_dir: str = "data/raw"

    # Preprocessed data folder (train.bin, val.bin, meta.json)
    processed_dir: str = "data/processed"

    # training/Verification Split Ratio
    # 0.95: 95 of total material%to training, 5%used for verification
    train_split: float = 0.95


@dataclass
class InferenceConfig:
    """Create post(inference) default settings.

    【Beginner's Guide】
      Gradio UIThis is the default value for the values adjusted with the slider..
      generate.pyWow chat.pyUse these values in.
    """

    # Maximum characters to generate once(tag) number
    default_max_new_tokens: int = 256

    # temperature: Controlling generative diversity (The higher the more creative, The lower it is, the more repetitive it is.)
    default_temperature: float = 0.9

    # Top-K: top KLeave only the candidates and remove the rest
    default_top_k: int = 50

    # Top-P (nuclear sampling): cumulative probability POnly candidates up to
    default_top_p: float = 0.95

    # repetition penalty: Lower the probability of already generated letters (1.0 = No penalty points)
    default_repetition_penalty: float = 1.15


@dataclass
class FullConfig:
    """Top-level settings container that holds all settings.

    【Beginner's Guide】
      load_config() The function returns this object.
      cfg = load_config("config/model_config.yaml") After calling
      cfg.model.n_layer, cfg.train.batch_size Approach with your back.
    """
    model: ModelConfig = field(default_factory=ModelConfig)
    train: TrainConfig = field(default_factory=TrainConfig)
    tokenizer: TokenizerConfig = field(default_factory=TokenizerConfig)
    data: DataConfig = field(default_factory=DataConfig)
    inference: InferenceConfig = field(default_factory=InferenceConfig)


def _build(cls, raw: dict[str, Any] | None):
    """dictionary(dict)A helper function that creates a configuration class instance from.

    YAMLFor items not in , the default values of the class are used..
    YAMLItems that are not in the class are ignored, even if they are in (error prevention).
    """
    if raw is None:
        return cls()  # YAMLIf the section does not exist, create it as default.
    # Select and pass only the field names defined in the class
    return cls(**{k: v for k, v in raw.items() if k in cls.__dataclass_fields__})


def load_config(path: str | Path) -> FullConfig:
    """YAML read the file FullConfig Creates and returns an object.

    Example usage:
        cfg = load_config("config/model_config.yaml")
        print(cfg.model.n_layer)   # → 8
        print(cfg.train.max_steps) # → 5000

    argument:
        path: YAML Path to configuration file

    return value:
        FullConfig: An object containing all settings
    """
    with open(path, "r", encoding="utf-8") as f:
        raw: dict[str, Any] = yaml.safe_load(f) or {}  # YAML Read file as dictionary

    # Create a settings object for each section FullConfigReturn it in
    return FullConfig(
        model=_build(ModelConfig, raw.get("model")),           # [model] section
        train=_build(TrainConfig, raw.get("train")),           # [train] section
        tokenizer=_build(TokenizerConfig, raw.get("tokenizer")),  # [tokenizer] section
        data=_build(DataConfig, raw.get("data")),              # [data] section
        inference=_build(InferenceConfig, raw.get("inference")),  # [inference] section
    )


def save_config(cfg: FullConfig, path: str | Path) -> None:
    """FullConfig object YAML Save as file.

    argument:
        cfg:  Settings object to save
        path: to save YAML file path
    """
    # Convert each settings object to a dictionary
    raw = {
        "model": cfg.model.__dict__,
        "train": cfg.train.__dict__,
        "tokenizer": cfg.tokenizer.__dict__,
        "data": cfg.data.__dict__,
        "inference": cfg.inference.__dict__,
    }
    with open(path, "w", encoding="utf-8") as f:
        # allow_unicode=True: Save Korean characters without escaping
        yaml.safe_dump(raw, f, sort_keys=False, allow_unicode=True)
