"""Multi-turn chat session manager.

【Beginner's Guide】
  This file is GPT It contains classes that wrap the model so that it can be used like a chatbot..

  The basic model is a simple language model — "predict the next letter" I just do it.
  This file creates conversational prompts to act like a chatbot..

  conversation format:
    user: <Post entered by user>
    assistant: <Responses generated by the model>
    user: <Next user input>
    assistant: <The model continues to be created>

  history(history) management:
    The conversation record is attached to the prompt at each turn..
    If the record is too long, it is truncated starting from the oldest..
    (Maximum number of characters the model can see at one time = block_size = 1024)

  system prefix(system_prefix):
    Instructions that tell the model its role before starting a conversation.
    yes: "You are a guide to Joseon-style cooking methods.."
    Applies only when vocabulary size is 8000 or more.
    (Small vocabulary models lack the ability to follow instructions.)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterator

import torch

ROOT = Path(__file__).resolve().parents[2]  # project root path

from src.inference.generate import generate_stream  # Streaming post creation function
from src.model.config import FullConfig, ModelConfig, load_config
from src.model.transformer import GPT
from src.tokenizer.tokenizer import Tokenizer, load_tokenizer


# conversation type tag — The model looks at this tag and identifies who said it.
USER_TAG      = "user: "  # Tags added before user words
ASSISTANT_TAG = "assistant: "    # assistant(model) Tag attached before a word


@dataclass
class ChatTurn:
    """Data structure representing one conversation.

    argument:
        role: "user" (user) or "assistant" (assistant)
        text: Content of the article in question
    """
    role: str  # "user" or "assistant"
    text: str


@dataclass
class ChatSession:
    """conversation session — model, ticket analyzer, Manage conversation history.

    【Beginner's Guide】
      This class GPT between model and user "conversation window" play a role.
      chat() or chat_stream() Generates a response when called.

    field:
        model:         GPT model instance
        tokenizer:     Tag Analyzer Instance
        cfg:           full settings (FullConfig)
        device:        device with raised model (cuda or cpu)
        history:       History of conversations so far (ChatTurn list)
        system_prefix: Instructions before starting a conversation (selection)
    """
    model:         GPT
    tokenizer:     Tokenizer
    cfg:           FullConfig
    device:        torch.device
    history:       list[ChatTurn] = field(default_factory=list)
    system_prefix: str = ""  # optional system directive

    def reset(self) -> None:
        """Delete all conversation history (Start a new conversation)."""
        self.history.clear()

    def _format_prompt(self, user_message: str) -> str:
        """Combining user messages and conversation history into a prompt string.

        Output format example:
            You are a recipe guide assistant.   ← system prefix (Only when there is)
            user: hello              ← history: Previous Tables
            assistant: hello! How can I help you??
            user: How to make kimchi     ← Current user input
            assistant:                           ← The model is created from here

        argument:
            user_message: User input this time

        return value:
            The entire prompt string to include in the model.
        """
        parts: list[str] = []

        # If there is a system prefix, add it first
        if self.system_prefix:
            parts.append(self.system_prefix.rstrip() + "\n")

        # Add previous conversation history in order
        for turn in self.history:
            tag = USER_TAG if turn.role == "user" else ASSISTANT_TAG
            parts.append(f"{tag}{turn.text}")

        # Add user input this turn
        parts.append(f"{USER_TAG}{user_message}")

        # "assistant: " Just add tags and leave the content empty → The model is created from here
        parts.append(ASSISTANT_TAG.rstrip())

        return "\n".join(parts)

    def _truncate_history_to_fit(self, user_message: str, max_new_tokens: int) -> None:
        """Trim old conversation history if prompt exceeds context length.

        【Beginner's Guide】
          The model can be block_size(1024) Only 100 tickets can be processed..
          As the dialogue becomes longer, the prompt exceeds this limit..
          The oldest user at that time-Remove the assistant's turn pair first..

        budget calculation:
          budget = block_size(1024) - max_new_tokens(256) - 8(spare time)
                 = 760 tag

          Remove old records until the prompt is below 760 fishmarks.

        argument:
            user_message:   Current user input
            max_new_tokens: Maximum number of tickets to generate
        """
        # Prompt Maximum number of allowed marks minus a safety margin of 8
        budget = self.cfg.model.block_size - max_new_tokens - 8

        while self.history:
            prompt = self._format_prompt(user_message)
            # Count the number of wordmarks in the current prompt
            n = len(self.tokenizer.encode(prompt, add_bos=True))
            if n <= budget:
                return  # Ends when within budget

            # Remove oldest user table of contents
            self.history.pop(0)
            # Then, when it is the assistant's turn, they are eliminated together. (user-Removed by pair of assistants)
            if self.history and self.history[0].role == "assistant":
                self.history.pop(0)

    def chat_stream(
        self,
        user_message: str,
        *,
        max_new_tokens: int | None = None,
        temperature: float | None = None,
        top_k: int | None = None,
        top_p: float | None = None,
        repetition_penalty: float | None = None,
    ) -> Iterator[str]:
        """Generate streaming responses to user input.

        【Beginner's Guide】
          This function does not return response letters all at once.,
          It is exported little by little as soon as it is created. (streaming).
          Gradio UIThis is the effect of letters appearing one by one in.

          Stop responding conditions:
            1. EOS A tag has been created (generate_stream processed internally)
            2. The model "user:" Created a tag → Start acting as the next person yourself
               In this case "user:" Print only to the beginning and stop

          After creation, this turn history add to.

        argument:
            user_message:      User input text
            max_new_tokens:    Maximum number of tickets to generate (None = Setting default)
            temperature:       temperature (None = Setting default)
            top_k:             Top-K (None = Setting default)
            top_p:             Top-P (None = Setting default)
            repetition_penalty: repetition penalty (None = Setting default)

        generated value:
            Fragment string from response post (streaming)
        """
        ic = self.cfg.inference  # Inference Settings Shortcut Reference
        max_new = max_new_tokens or ic.default_max_new_tokens

        # Trim old records when prompt exceeds context length
        self._truncate_history_to_fit(user_message, max_new)

        # Configure final prompt
        prompt = self._format_prompt(user_message)

        produced_chunks: list[str] = []  # Article fragments created so far

        # Start creating a stream
        for delta in generate_stream(
            self.model, self.tokenizer, prompt,
            max_new_tokens=max_new,
            temperature=temperature if temperature is not None else ic.default_temperature,
            top_k=top_k          if top_k          is not None else ic.default_top_k,
            top_p=top_p          if top_p          is not None else ic.default_top_p,
            repetition_penalty=repetition_penalty if repetition_penalty is not None else ic.default_repetition_penalty,
            device=self.device,
        ):
            # All posts created so far (previous pieces + bird sculpture)
            running = "".join(produced_chunks) + delta

            # the model itself "user:" Stop when you start writing tags
            # (Prevents the model from trying to continue the conversation alone)
            if "\nuser:" in running or running.startswith("user:"):
                cut = running.find("user:")
                trimmed = running[:cut].rstrip()  # "user:" Valid only up to the front
                # Export only the remainder excluding the part already printed.
                already = "".join(produced_chunks)
                if len(trimmed) > len(already):
                    yield trimmed[len(already):]
                produced_chunks = [trimmed]
                break  # stop creating

            produced_chunks.append(delta)
            yield delta  # Immediately export new text fragments

        # Add all generated responses to conversation history
        full_response = "".join(produced_chunks).strip()
        self.history.append(ChatTurn(role="user",      text=user_message))
        self.history.append(ChatTurn(role="assistant", text=full_response))

    def chat(self, user_message: str, **kwargs) -> str:
        """Returns the entire response to user input all at once.

        chat_stream() Non-streaming version of.
        After the response is completely generated, it is returned as a single string..
        """
        return "".join(self.chat_stream(user_message, **kwargs))


def load_session_from_checkpoint(
    checkpoint_path: str | Path,
    config_path: str | Path = "config/model_config.yaml",
    device: str | torch.device = "auto",
    system_prefix: str = "",
) -> ChatSession:
    """In checkpoint file ChatSessionload.

    【Beginner's Guide】
      This function is the gateway to load the trained model and prepare it for use as a chatbot..
      gradio_app.pyCall this function when starting.

    Processing order:
      1. Read configuration file
      2. Device Decision (GPUautomatically if there is GPU)
      3. Load model weights and settings from checkpoint file
      4. With checkpoint settings ModelConfig restore (Setting priority when saving)
      5. GPT Load weights after creating a model instance
      6. torch.compile Remove packaging (When needed)
      7. Loading the tag analyzer
      8. ChatSession Return after creation

    argument:
        checkpoint_path: Trained checkpoint file path (.pt)
        config_path:     Configuration file path (.yaml)
        device:          device ("auto", "cpu", "cuda")
        system_prefix:   system directive string

    return value:
        ready to use ChatSession instance
    """
    cfg = load_config(config_path)  # Read configuration file

    # Device Decision
    if str(device) == "auto":
        # GPUIf there is GPU, If there is no CPU
        device_t = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        device_t = torch.device(device)

    # Load checkpoint file
    # weights_only=False: config To load the dictionary as well
    ckpt = torch.load(str(checkpoint_path), map_location=device_t, weights_only=False)

    # Restore model settings saved at a checkpoint
    # (in training block_size Because it may have been automatically adjusted, yamlpriority)
    saved_model_cfg = ckpt.get("config", {}).get("model")
    if saved_model_cfg:
        cfg.model = ModelConfig(
            **{k: v for k, v in saved_model_cfg.items() if k in ModelConfig.__dataclass_fields__}
        )

    # With restored settings GPT After creating the model, go to the designated device
    model = GPT(cfg.model).to(device_t)

    # Load weights
    state = ckpt["model_state"]
    # torch.compile If you wrote in the weight name "_orig_mod." prefixed
    # This must be removed GPT Can be loaded into models
    if any(k.startswith("_orig_mod.") for k in state.keys()):
        state = {k.replace("_orig_mod.", "", 1): v for k, v in state.items()}
    model.load_state_dict(state)
    model.eval()  # Setting inference mode (Disable dropout, etc.)

    # Loading the tag analyzer
    tokenizer = load_tokenizer(
        ROOT / "checkpoints" / f"{cfg.tokenizer.output_prefix}.model"
    )

    # ChatSession Return after creation
    return ChatSession(
        model=model,
        tokenizer=tokenizer,
        cfg=cfg,
        device=device_t,
        system_prefix=system_prefix,
    )
