-- Migration 032: Set recipe and nutrition material image URLs extracted from ui/babyG/nutritions.
-- Images are square 512x512 PNG files under backend/public/images/nutrition.

UPDATE recipes SET image_url = '/images/nutrition/recipes/acorn-squash-pasta.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Acorn Squash Pasta');
UPDATE recipes SET image_url = '/images/nutrition/recipes/almond-butter-toast.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Almond Butter Toast');
UPDATE recipes SET image_url = '/images/nutrition/recipes/almond-toast-with-smoothie.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Almond Toast with Smoothie');
UPDATE recipes SET image_url = '/images/nutrition/recipes/artichoke-tomato-pasta.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Artichoke Tomato Pasta');
UPDATE recipes SET image_url = '/images/nutrition/recipes/avocado-hemp-spears.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Avocado Hemp Spears');
UPDATE recipes SET image_url = '/images/nutrition/recipes/avocado-toast-and-berry-smoothie.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Avocado Toast & Berry Smoothie');
UPDATE recipes SET image_url = '/images/nutrition/recipes/avocado-toast-with-banana.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Avocado Toast with Banana');
UPDATE recipes SET image_url = '/images/nutrition/recipes/baby-omelette.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Baby Omelette');
UPDATE recipes SET image_url = '/images/nutrition/recipes/baked-ziti.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Baked Ziti');
UPDATE recipes SET image_url = '/images/nutrition/recipes/banana-muffin-with-almond.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Banana Muffin With Almond');
UPDATE recipes SET image_url = '/images/nutrition/recipes/banana-pancakes.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Banana Pancakes');
UPDATE recipes SET image_url = '/images/nutrition/recipes/banana-with-almond-butter.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Banana With Almond Butter');
UPDATE recipes SET image_url = '/images/nutrition/recipes/banana-with-chocolate-peanut-butter.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Banana with Chocolate Peanut Butter');
UPDATE recipes SET image_url = '/images/nutrition/recipes/bean-chili-with-corn-bread.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Bean Chili with Corn Bread');
UPDATE recipes SET image_url = '/images/nutrition/recipes/beef-and-rice-stuffed-pepper.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Beef & Rice Stuffed Pepper');
UPDATE recipes SET image_url = '/images/nutrition/recipes/beef-sliders.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Beef Sliders');
UPDATE recipes SET image_url = '/images/nutrition/recipes/berry-licious-muffin.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Berry-licious Muffin');
UPDATE recipes SET image_url = '/images/nutrition/recipes/black-bean-bites-with-savory-dip.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Black Bean Bites with Savory Dip');
UPDATE recipes SET image_url = '/images/nutrition/recipes/black-bean-mash-zucchini-spears.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Black Bean Mash Zucchini Spears');
UPDATE recipes SET image_url = '/images/nutrition/recipes/blueberry-muffin-with-banana-spear.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Blueberry Muffin with Banana Spear');
UPDATE recipes SET image_url = '/images/nutrition/recipes/blueberry-quinoa.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Blueberry Quinoa');
UPDATE recipes SET image_url = '/images/nutrition/recipes/boiled-egg-oat-bar.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Boiled Egg + Oat Bar');
UPDATE recipes SET image_url = '/images/nutrition/recipes/breakfast-fritters.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Breakfast Fritters');
UPDATE recipes SET image_url = '/images/nutrition/recipes/broccoli-pasta-salad.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Broccoli Pasta Salad');
UPDATE recipes SET image_url = '/images/nutrition/recipes/butter-toast-with-smoothie.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Butter Toast with Smoothie');
UPDATE recipes SET image_url = '/images/nutrition/recipes/cajun-fish.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Cajun Fish');
UPDATE recipes SET image_url = '/images/nutrition/recipes/cashew-cracker-crunch.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Cashew Cracker Crunch');
UPDATE recipes SET image_url = '/images/nutrition/recipes/cheddar-broccoli-soup.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Cheddar Broccoli Soup');
UPDATE recipes SET image_url = '/images/nutrition/recipes/cheese-quesadilla.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Cheese Quesadilla');
UPDATE recipes SET image_url = '/images/nutrition/recipes/cheese-sandwich-with-tomato-soup.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Cheese Sandwich with Tomato Soup');
UPDATE recipes SET image_url = '/images/nutrition/recipes/cheese-and-crackers.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Cheese and Crackers');
UPDATE recipes SET image_url = '/images/nutrition/recipes/cheesy-cracker-duo.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Cheesy Cracker Duo');
UPDATE recipes SET image_url = '/images/nutrition/recipes/cheesy-kiwi-delight.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Cheesy Kiwi Delight');
UPDATE recipes SET image_url = '/images/nutrition/recipes/cheesy-mushroom-quesadilla.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Cheesy Mushroom Quesadilla');
UPDATE recipes SET image_url = '/images/nutrition/recipes/cheesy-scrambled-egg.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Cheesy Scrambled Egg');
UPDATE recipes SET image_url = '/images/nutrition/recipes/cheesy-veggie-omelette.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Cheesy Veggie Omelette');
UPDATE recipes SET image_url = '/images/nutrition/recipes/chicken-chili.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Chicken Chili');
UPDATE recipes SET image_url = '/images/nutrition/recipes/chicken-noodle-soup.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Chicken Noodle Soup');
UPDATE recipes SET image_url = '/images/nutrition/recipes/chicken-pepper-egg-muffins.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Chicken Pepper Egg Muffins');
UPDATE recipes SET image_url = '/images/nutrition/recipes/chicken-rice.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Chicken Rice');
UPDATE recipes SET image_url = '/images/nutrition/recipes/chicken-sandwich.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Chicken Sandwich');
UPDATE recipes SET image_url = '/images/nutrition/recipes/choco-berry-chia-pudding.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Choco Berry Chia Pudding');
UPDATE recipes SET image_url = '/images/nutrition/recipes/chocolate-chia-pudding.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Chocolate Chia Pudding');
UPDATE recipes SET image_url = '/images/nutrition/recipes/chocolate-chip-energy-bites.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Chocolate Chip Energy Bites');
UPDATE recipes SET image_url = '/images/nutrition/recipes/cinnamon-apple-pancakes.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Cinnamon Apple Pancakes');
UPDATE recipes SET image_url = '/images/nutrition/recipes/cinnamon-apple-puree.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Cinnamon Apple Puree');
UPDATE recipes SET image_url = '/images/nutrition/recipes/cinnamon-oats-with-raspberry.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Cinnamon Oats With Raspberry');
UPDATE recipes SET image_url = '/images/nutrition/recipes/cinnamon-waffles.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Cinnamon Waffles');
UPDATE recipes SET image_url = '/images/nutrition/recipes/coconut-mango-spears.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Coconut Mango Spears');
UPDATE recipes SET image_url = '/images/nutrition/recipes/cod-burger.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Cod Burger');
UPDATE recipes SET image_url = '/images/nutrition/recipes/cottage-cheese-toast.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Cottage Cheese Toast');
UPDATE recipes SET image_url = '/images/nutrition/recipes/crackers-and-cheese.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Crackers & Cheese');
UPDATE recipes SET image_url = '/images/nutrition/recipes/crackers-with-feta-dip.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Crackers With Feta Dip');
UPDATE recipes SET image_url = '/images/nutrition/recipes/crackers-with-avocado.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Crackers with Avocado');
UPDATE recipes SET image_url = '/images/nutrition/recipes/deconstructed-taco.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Deconstructed Taco');
UPDATE recipes SET image_url = '/images/nutrition/recipes/deconstructed-taco-with-chicken.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Deconstructed Taco With Chicken');
UPDATE recipes SET image_url = '/images/nutrition/recipes/dill-salmon-with-cauliflower.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Dill Salmon with Cauliflower');
UPDATE recipes SET image_url = '/images/nutrition/recipes/dino-pancakes.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Dino Pancakes');
UPDATE recipes SET image_url = '/images/nutrition/recipes/egg-muffins.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Egg Muffins');
UPDATE recipes SET image_url = '/images/nutrition/recipes/egg-salad-pinwheel-and-kiwi.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Egg Salad Pinwheel & Kiwi');
UPDATE recipes SET image_url = '/images/nutrition/recipes/egg-salad-pinwheels.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Egg Salad Pinwheels');
UPDATE recipes SET image_url = '/images/nutrition/recipes/flax-and-cheese-beetroot-carrots.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Flax & Cheese Beetroot Carrots');
UPDATE recipes SET image_url = '/images/nutrition/recipes/flax-avocado-spear.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Flax Avocado Spear');
UPDATE recipes SET image_url = '/images/nutrition/recipes/fluffy-banana-spinach-pancakes.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Fluffy Banana Spinach Pancakes');
UPDATE recipes SET image_url = '/images/nutrition/recipes/french-fruit-nutty-crepes.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('French Fruit Nutty Crepes');
UPDATE recipes SET image_url = '/images/nutrition/recipes/french-toast.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('French Toast');
UPDATE recipes SET image_url = '/images/nutrition/recipes/french-toast-with-mashed-blackberries.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('French Toast with Mashed Blackberries');
UPDATE recipes SET image_url = '/images/nutrition/recipes/ginger-garlic-tofu.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Ginger Garlic Tofu');
UPDATE recipes SET image_url = '/images/nutrition/recipes/graham-crackers.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Graham Crackers');
UPDATE recipes SET image_url = '/images/nutrition/recipes/green-smoothie.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Green Smoothie');
UPDATE recipes SET image_url = '/images/nutrition/recipes/homemade-oatmeal-cookies.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Homemade Oatmeal Cookies');
UPDATE recipes SET image_url = '/images/nutrition/recipes/honey-ginger-tofu-stir-fry.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Honey Ginger Tofu Stir Fry');
UPDATE recipes SET image_url = '/images/nutrition/recipes/hummus-with-broccoli.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Hummus with Broccoli');
UPDATE recipes SET image_url = '/images/nutrition/recipes/iron-almond-cereal.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Iron Almond Cereal');
UPDATE recipes SET image_url = '/images/nutrition/recipes/iron-banana-cereal.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Iron Banana Cereal');
UPDATE recipes SET image_url = '/images/nutrition/recipes/iron-strawberry-cereal.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Iron Strawberry Cereal');
UPDATE recipes SET image_url = '/images/nutrition/recipes/italian-risotto.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Italian Risotto');
UPDATE recipes SET image_url = '/images/nutrition/recipes/lemon-chicken-orzo.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Lemon Chicken Orzo');
UPDATE recipes SET image_url = '/images/nutrition/recipes/lentil-and-veggie-stew.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Lentil and Veggie Stew');
UPDATE recipes SET image_url = '/images/nutrition/recipes/mango-chia-pudding.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Mango Chia Pudding');
UPDATE recipes SET image_url = '/images/nutrition/recipes/meat-sauce-pasta.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Meat Sauce Pasta');
UPDATE recipes SET image_url = '/images/nutrition/recipes/mixed-fruit-yogurt.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Mixed Fruit Yogurt');
UPDATE recipes SET image_url = '/images/nutrition/recipes/mixed-veggies-with-hummus.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Mixed Veggies With Hummus');
UPDATE recipes SET image_url = '/images/nutrition/recipes/mushroom-stuffed-shell.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Mushroom Stuffed Shell');
UPDATE recipes SET image_url = '/images/nutrition/recipes/naan-chickpea-spears.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Naan Chickpea Spears');
UPDATE recipes SET image_url = '/images/nutrition/recipes/nut-butter-overnight-oats.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Nut Butter Overnight Oats');
UPDATE recipes SET image_url = '/images/nutrition/recipes/oat-bar-with-kiwi.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Oat Bar With Kiwi');
UPDATE recipes SET image_url = '/images/nutrition/recipes/omelette-strips-with-grapefruit.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Omelette Strips with Grapefruit');
UPDATE recipes SET image_url = '/images/nutrition/recipes/orange-cream-cheese-toast.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Orange Cream Cheese Toast');
UPDATE recipes SET image_url = '/images/nutrition/recipes/orange-tofu.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Orange Tofu');
UPDATE recipes SET image_url = '/images/nutrition/recipes/overnight-oats.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Overnight Oats');
UPDATE recipes SET image_url = '/images/nutrition/recipes/pb-banana-sandwich.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('PB Banana Sandwich');
UPDATE recipes SET image_url = '/images/nutrition/recipes/parfait.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Parfait');
UPDATE recipes SET image_url = '/images/nutrition/recipes/peanut-butter-toast.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Peanut Butter Toast');
UPDATE recipes SET image_url = '/images/nutrition/recipes/pear-oatmeal.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Pear Oatmeal');
UPDATE recipes SET image_url = '/images/nutrition/recipes/pear-waffle-dippers-with-yogurt.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Pear Waffle Dippers with Yogurt');
UPDATE recipes SET image_url = '/images/nutrition/recipes/pesto-pasta-with-kiwi.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Pesto Pasta with Kiwi');
UPDATE recipes SET image_url = '/images/nutrition/recipes/pistachio-pear-ricotta-spears.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Pistachio Pear Ricotta Spears');
UPDATE recipes SET image_url = '/images/nutrition/recipes/pistachio-pear-ricotta-toast.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Pistachio Pear Ricotta Toast');
UPDATE recipes SET image_url = '/images/nutrition/recipes/pork-with-apple-sauce.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Pork with Apple Sauce');
UPDATE recipes SET image_url = '/images/nutrition/recipes/power-bananas.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Power Bananas');
UPDATE recipes SET image_url = '/images/nutrition/recipes/power-toast-with-fruit.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Power Toast with Fruit');
UPDATE recipes SET image_url = '/images/nutrition/recipes/protein-packed-breakfast.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Protein Packed Breakfast');
UPDATE recipes SET image_url = '/images/nutrition/recipes/pumpkin-overnight-oats.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Pumpkin Overnight Oats');
UPDATE recipes SET image_url = '/images/nutrition/recipes/pumpkin-pasta.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Pumpkin Pasta');
UPDATE recipes SET image_url = '/images/nutrition/recipes/pumpkin-toast-with-smoothie.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Pumpkin Toast with Smoothie');
UPDATE recipes SET image_url = '/images/nutrition/recipes/quinoa-bowl.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Quinoa Bowl');
UPDATE recipes SET image_url = '/images/nutrition/recipes/raspberry-oatmeal.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Raspberry Oatmeal');
UPDATE recipes SET image_url = '/images/nutrition/recipes/raspberry-yogurt-delight.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Raspberry Yogurt Delight');
UPDATE recipes SET image_url = '/images/nutrition/recipes/roasted-chicken-with-cannellini-beans.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Roasted Chicken with Cannellini Beans');
UPDATE recipes SET image_url = '/images/nutrition/recipes/salmon-and-mash.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Salmon & Mash');
UPDATE recipes SET image_url = '/images/nutrition/recipes/salmon-mash-with-cauliflower.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Salmon Mash with Cauliflower');
UPDATE recipes SET image_url = '/images/nutrition/recipes/salmon-patty.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Salmon Patty');
UPDATE recipes SET image_url = '/images/nutrition/recipes/salmon-smash.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Salmon Smash');
UPDATE recipes SET image_url = '/images/nutrition/recipes/salmon-with-zucchini-spears.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Salmon with Zucchini Spears');
UPDATE recipes SET image_url = '/images/nutrition/recipes/savory-egg-muffins.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Savory Egg Muffins');
UPDATE recipes SET image_url = '/images/nutrition/recipes/savory-steak.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Savory Steak');
UPDATE recipes SET image_url = '/images/nutrition/recipes/scrambled-eggs.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Scrambled Eggs');
UPDATE recipes SET image_url = '/images/nutrition/recipes/sesame-tofu-broccoli.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Sesame Tofu Broccoli');
UPDATE recipes SET image_url = '/images/nutrition/recipes/spinach-banana-pancakes.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Spinach Banana Pancakes');
UPDATE recipes SET image_url = '/images/nutrition/recipes/spinach-ricotta-beef-meatballs.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Spinach Ricotta Beef Meatballs');
UPDATE recipes SET image_url = '/images/nutrition/recipes/steak-strips-and-raspberries.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Steak Strips & Raspberries');
UPDATE recipes SET image_url = '/images/nutrition/recipes/steak-with-mashed-potatoes.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Steak with Mashed Potatoes');
UPDATE recipes SET image_url = '/images/nutrition/recipes/strawberry-french-toast.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Strawberry French Toast');
UPDATE recipes SET image_url = '/images/nutrition/recipes/stuffed-bell-peppers.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Stuffed Bell Peppers');
UPDATE recipes SET image_url = '/images/nutrition/recipes/sweet-potato-latkes.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Sweet Potato Latkes');
UPDATE recipes SET image_url = '/images/nutrition/recipes/sweet-potato-spears.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Sweet Potato Spears');
UPDATE recipes SET image_url = '/images/nutrition/recipes/thai-peanut-tofu-bowl.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Thai Peanut Tofu Bowl');
UPDATE recipes SET image_url = '/images/nutrition/recipes/toast-with-smoothie.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Toast with Smoothie');
UPDATE recipes SET image_url = '/images/nutrition/recipes/tomato-sandwich-soup.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Tomato Sandwich Soup');
UPDATE recipes SET image_url = '/images/nutrition/recipes/turkey-tomato-pasta.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Turkey Tomato Pasta');
UPDATE recipes SET image_url = '/images/nutrition/recipes/turkey-veggie-frittata.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Turkey Veggie Frittata');
UPDATE recipes SET image_url = '/images/nutrition/recipes/turkey-with-baked-fries.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Turkey with Baked Fries');
UPDATE recipes SET image_url = '/images/nutrition/recipes/vegetable-lentil-bell-pepper-medley.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Vegetable Lentil Bell Pepper Medley');
UPDATE recipes SET image_url = '/images/nutrition/recipes/veggie-burger.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Veggie Burger');
UPDATE recipes SET image_url = '/images/nutrition/recipes/veggie-fritters.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Veggie Fritters');
UPDATE recipes SET image_url = '/images/nutrition/recipes/veggie-mash.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Veggie Mash');
UPDATE recipes SET image_url = '/images/nutrition/recipes/veggie-quesadilla.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Veggie Quesadilla');
UPDATE recipes SET image_url = '/images/nutrition/recipes/veggie-tzatziki.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Veggie Tzatziki');
UPDATE recipes SET image_url = '/images/nutrition/recipes/veggies-with-hummus.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Veggies With Hummus');
UPDATE recipes SET image_url = '/images/nutrition/recipes/veggies-and-hummus.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Veggies and Hummus');
UPDATE recipes SET image_url = '/images/nutrition/recipes/waffle-strips-with-yogurt-and-fruit.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Waffle Strips With Yogurt & Fruit');
UPDATE recipes SET image_url = '/images/nutrition/recipes/waffle-with-blueberries.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Waffle with Blueberries');
UPDATE recipes SET image_url = '/images/nutrition/recipes/waffle-with-raspberry.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Waffle with Raspberry');
UPDATE recipes SET image_url = '/images/nutrition/recipes/white-fish-with-caprese-salad.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('White Fish with Caprese Salad');
UPDATE recipes SET image_url = '/images/nutrition/recipes/yogurt-with-fruit-and-crushed-nuts.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Yogurt With Fruit & Crushed Nuts');
UPDATE recipes SET image_url = '/images/nutrition/recipes/yogurt-with-fruit.png' WHERE target = 'baby' AND language = 'en' AND lower(title) = lower('Yogurt with Fruit');

UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/almond-butter.png' WHERE language = 'en' AND lower(name) = lower('Almond Butter');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/almonds.png' WHERE language = 'en' AND lower(name) = lower('Almonds');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/amaranth-seeds.png' WHERE language = 'en' AND lower(name) = lower('Amaranth Seeds');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/amaranth-seeds-rajgeer.png' WHERE language = 'en' AND lower(name) = lower('Amaranth Seeds (Rajgeer)');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/amla.png' WHERE language = 'en' AND lower(name) = lower('Amla');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/avocado.png' WHERE language = 'en' AND lower(name) = lower('Avocado');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/bajra.png' WHERE language = 'en' AND lower(name) = lower('Bajra');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/beans.png' WHERE language = 'en' AND lower(name) = lower('Beans');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/breast-milk-formula.png' WHERE language = 'en' AND lower(name) = lower('Breast Milk / Formula');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/carrot.png' WHERE language = 'en' AND lower(name) = lower('Carrot');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/cereals.png' WHERE language = 'en' AND lower(name) = lower('Cereals');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/cheese.png' WHERE language = 'en' AND lower(name) = lower('Cheese');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/chicken.png' WHERE language = 'en' AND lower(name) = lower('Chicken');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/chicken-liver.png' WHERE language = 'en' AND lower(name) = lower('Chicken Liver');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/dairy-products.png' WHERE language = 'en' AND lower(name) = lower('Dairy Products');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/edamame.png' WHERE language = 'en' AND lower(name) = lower('Edamame');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/egg.png' WHERE language = 'en' AND lower(name) = lower('Egg');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/egg-yolk.png' WHERE language = 'en' AND lower(name) = lower('Egg Yolk');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/egg-yolks.png' WHERE language = 'en' AND lower(name) = lower('Egg Yolks');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/eggs.png' WHERE language = 'en' AND lower(name) = lower('Eggs');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/fish.png' WHERE language = 'en' AND lower(name) = lower('Fish');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/fortified-grain-products.png' WHERE language = 'en' AND lower(name) = lower('Fortified Grain Products');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/fruits.png' WHERE language = 'en' AND lower(name) = lower('Fruits');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/fruits-and-vegetables.png' WHERE language = 'en' AND lower(name) = lower('Fruits & Vegetables');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/garden-cress-seeds.png' WHERE language = 'en' AND lower(name) = lower('Garden Cress Seeds');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/green-leafy-vegetables.png' WHERE language = 'en' AND lower(name) = lower('Green Leafy Vegetables');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/iodised-salt.png' WHERE language = 'en' AND lower(name) = lower('Iodised Salt');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/kiwi.png' WHERE language = 'en' AND lower(name) = lower('Kiwi');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/lentils.png' WHERE language = 'en' AND lower(name) = lower('Lentils');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/liver.png' WHERE language = 'en' AND lower(name) = lower('Liver');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/mango.png' WHERE language = 'en' AND lower(name) = lower('Mango');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/mashed-potato.png' WHERE language = 'en' AND lower(name) = lower('Mashed Potato');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/milk.png' WHERE language = 'en' AND lower(name) = lower('Milk');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/orange.png' WHERE language = 'en' AND lower(name) = lower('Orange');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/oranges.png' WHERE language = 'en' AND lower(name) = lower('Oranges');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/other-starchy-vegetables.png' WHERE language = 'en' AND lower(name) = lower('Other Starchy Vegetables');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/papaya.png' WHERE language = 'en' AND lower(name) = lower('Papaya');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/portobello-mushroom.png' WHERE language = 'en' AND lower(name) = lower('Portobello Mushroom');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/potato.png' WHERE language = 'en' AND lower(name) = lower('Potato');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/pulses-and-legumes.png' WHERE language = 'en' AND lower(name) = lower('Pulses & Legumes');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/pumpkin.png' WHERE language = 'en' AND lower(name) = lower('Pumpkin');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/quinoa.png' WHERE language = 'en' AND lower(name) = lower('Quinoa');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/ragi.png' WHERE language = 'en' AND lower(name) = lower('Ragi');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/salmon.png' WHERE language = 'en' AND lower(name) = lower('Salmon');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/seeds-like-sesame.png' WHERE language = 'en' AND lower(name) = lower('Seeds Like Sesame');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/soybean.png' WHERE language = 'en' AND lower(name) = lower('Soybean');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/sunlight-exposure.png' WHERE language = 'en' AND lower(name) = lower('Sunlight Exposure');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/sweet-lime.png' WHERE language = 'en' AND lower(name) = lower('Sweet Lime');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/tomato.png' WHERE language = 'en' AND lower(name) = lower('Tomato');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/vegetable-oils.png' WHERE language = 'en' AND lower(name) = lower('Vegetable Oils');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/vitamin-d-fortified-food.png' WHERE language = 'en' AND lower(name) = lower('Vitamin D Fortified Food');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/walnuts.png' WHERE language = 'en' AND lower(name) = lower('Walnuts');
UPDATE nutrition_foods SET image_url = '/images/nutrition/materials/whole-grains.png' WHERE language = 'en' AND lower(name) = lower('Whole Grains');

SELECT COUNT(*) AS recipe_images FROM recipes WHERE image_url LIKE '/images/nutrition/recipes/%';
SELECT COUNT(*) AS material_images FROM nutrition_foods WHERE image_url LIKE '/images/nutrition/materials/%';